//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AIConverters : NSObject
{
}

+ (struct Mat)UIImageToMat:(id)arg1;
+ (struct Mat)UIImageToMat:(id)arg1 alphaExists:(_Bool)arg2;
+ (Rect__68879466)bboxForImage:(id)arg1 withFaceRect:(struct CGRect)arg2;
+ (struct Mat)landmarksFromNSArray:(id)arg1;
+ (id)nsArrayFromLandmarks:(struct Mat)arg1;
+ (struct FaceZones)faceZonesFromData:(id)arg1 error:(id *)arg2;
+ (id)dataFromFaceZones:(struct FaceZones)arg1 error:(id *)arg2;
+ (struct Mat)cvMatFromDataPureJpg:(id)arg1 error:(id *)arg2;
+ (id)dataPureJpgFromCVMat:(struct Mat)arg1 error:(id *)arg2;
+ (struct Mat)cvMatFromData:(id)arg1 error:(id *)arg2;
+ (id)dataFromCVMat:(struct Mat)arg1 error:(id *)arg2;
+ (id)faceZonesHolderFromData:(id)arg1 error:(id *)arg2;
+ (id)dataFromFaceZonesHolder:(id)arg1 error:(id *)arg2;
+ (id)cvMatHolderFromDataPureJpg:(id)arg1 error:(id *)arg2;
+ (id)dataPureJpgFromCVMatHolder:(id)arg1 error:(id *)arg2;
+ (id)cvMatHolderFromData:(id)arg1 error:(id *)arg2;
+ (id)dataFromCVMatHolder:(id)arg1 error:(id *)arg2;

@end

