//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCObserver-Protocol.h"

@class NSLock;
@protocol SCObserver;

@interface CTPObserverDebounce : NSObject <SCObserver>
{
    id <SCObserver> _observer;
    double _timeout;
    CDUnknownBlockType _delayedBlock;
    NSLock *_delayedBlockLock;
}

- (void).cxx_destruct;
- (void)complete;
- (void)next:(id)arg1;
- (void)_timeoutEndedWithNext:(id)arg1;
- (id)initWithObserver:(id)arg1 timeout:(double)arg2;

@end

