//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol CTPSearchEngine, CTPSearchEngineConfig, CTPSearchInputProcessor, CTPSearchInputProvider, CTPSearchOutputProcessor, CTPSearchSession, CTPSearchStrategy, CTPSearchTaskScheduler;

@protocol CTPSearchEngineFactory <NSObject>
- (id <CTPSearchEngine>)createSearchEngineWithConfig:(id <CTPSearchEngineConfig>)arg1;
- (id <CTPSearchEngine>)createSearchEngineWithSession:(id <CTPSearchSession>)arg1 inputProvider:(id <CTPSearchInputProvider>)arg2 taskScheduler:(id <CTPSearchTaskScheduler>)arg3 inputProcessor:(id <CTPSearchInputProcessor>)arg4 strategy:(id <CTPSearchStrategy>)arg5 outputProcessor:(id <CTPSearchOutputProcessor>)arg6;
@end

