//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CVMatHolderImageConversions : NSObject
{
}

+ (id)CVMatHolderFromFile:(id)arg1 destColorSpace:(unsigned long long)arg2 error:(id *)arg3;
+ (id)CVMatHolderFromImage:(id)arg1 destColorSpace:(unsigned long long)arg2;
+ (id)convertToPixelBuffer:(id)arg1 sourceColorSpace:(unsigned long long)arg2 pixelBufferRef:(struct __CVBuffer **)arg3;
+ (id)imageFromCVMatHolder:(id)arg1 sourceColorSpace:(unsigned long long)arg2;

@end

