//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GADAdConfigurationRenderStatistics : NSObject
{
    // Error parsing type: {atomic_flag="_Value"AB}, name: _hasEndedRenderTiming
    NSString *_allocationIdentifier;
    NSString *_ruleLineExternalID;
    NSString *_networkClass;
    long long _startTimestampMilliseconds;
    NSString *_fillURLStatisticsString;
    NSString *_CSIURLStatisticsString;
}

@property(readonly, nonatomic) NSString *CSIURLStatisticsString; // @synthesize CSIURLStatisticsString=_CSIURLStatisticsString;
@property(readonly, nonatomic) NSString *fillURLStatisticsString; // @synthesize fillURLStatisticsString=_fillURLStatisticsString;
- (void).cxx_destruct;
- (void)endTimingWithExitStatus:(long long)arg1 errorMessage:(id)arg2;
- (void)startTiming;
- (id)initWithAdConfiguration:(id)arg1;

@end

