//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, NSString, SCSCOREUUID;

@interface GroupMetadata : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool autoSaveToMemories; // @dynamic autoSaveToMemories;
@property(nonatomic) long long createdTsMs; // @dynamic createdTsMs;
@property(nonatomic) int customStoryType; // @dynamic customStoryType;
@property(copy, nonatomic) NSString *displayName; // @dynamic displayName;
@property(retain, nonatomic) SCSCOREUUID *groupId; // @dynamic groupId;
@property(nonatomic) unsigned long long groupVersion; // @dynamic groupVersion;
@property(nonatomic) _Bool hasGroupId; // @dynamic hasGroupId;
@property(nonatomic) _Bool hasOwnerId; // @dynamic hasOwnerId;
@property(nonatomic) _Bool isDeleted; // @dynamic isDeleted;
@property(nonatomic) long long lastUpdatedTsMs; // @dynamic lastUpdatedTsMs;
@property(retain, nonatomic) NSMutableArray *membersArray; // @dynamic membersArray;
@property(readonly, nonatomic) unsigned long long membersArray_Count; // @dynamic membersArray_Count;
@property(retain, nonatomic) SCSCOREUUID *ownerId; // @dynamic ownerId;
@property(retain, nonatomic) NSMutableArray *pastMembersArray; // @dynamic pastMembersArray;
@property(readonly, nonatomic) unsigned long long pastMembersArray_Count; // @dynamic pastMembersArray_Count;

@end

