//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface IMPInsightsSubscribeInsights : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) long long profileViewsSinceCreation; // @dynamic profileViewsSinceCreation;
@property(nonatomic) long long profileViewsSinceLastMonth; // @dynamic profileViewsSinceLastMonth;
@property(nonatomic) long long profileViewsSinceLastWeek; // @dynamic profileViewsSinceLastWeek;
@property(nonatomic) long long profileViewsSincePreviousMonth; // @dynamic profileViewsSincePreviousMonth;
@property(nonatomic) long long profileViewsSincePreviousWeek; // @dynamic profileViewsSincePreviousWeek;
@property(nonatomic) long long subscribesSinceCreation; // @dynamic subscribesSinceCreation;
@property(nonatomic) long long subscribesSinceLastMonth; // @dynamic subscribesSinceLastMonth;
@property(nonatomic) long long subscribesSinceLastWeek; // @dynamic subscribesSinceLastWeek;
@property(nonatomic) long long subscribesSincePreviousMonth; // @dynamic subscribesSincePreviousMonth;
@property(nonatomic) long long subscribesSincePreviousWeek; // @dynamic subscribesSincePreviousWeek;

@end

