//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class Asset, MapRecords, NSString;

@interface MemoriesAsset : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *URL; // @dynamic URL;
@property(retain, nonatomic) Asset *asset; // @dynamic asset;
@property(nonatomic) _Bool hasAsset; // @dynamic hasAsset;
@property(nonatomic) _Bool hasUploadHeaders; // @dynamic hasUploadHeaders;
@property(copy, nonatomic) NSString *md5; // @dynamic md5;
@property(nonatomic) unsigned long long size; // @dynamic size;
@property(retain, nonatomic) MapRecords *uploadHeaders; // @dynamic uploadHeaders;

@end

