//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSMutableArray, SCAdsAdPosition;

@interface SCAdsAdServeItem : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *adData; // @dynamic adData;
@property(copy, nonatomic) NSData *adId; // @dynamic adId;
@property(retain, nonatomic) SCAdsAdPosition *adPosition; // @dynamic adPosition;
@property(copy, nonatomic) NSData *adRenderData; // @dynamic adRenderData;
@property(nonatomic) int adType; // @dynamic adType;
@property(nonatomic) int demandSource; // @dynamic demandSource;
@property(retain, nonatomic) NSMutableArray *eligibleThirdPartyAdNetworkTrackInfoArray; // @dynamic eligibleThirdPartyAdNetworkTrackInfoArray;
@property(readonly, nonatomic) unsigned long long eligibleThirdPartyAdNetworkTrackInfoArray_Count; // @dynamic eligibleThirdPartyAdNetworkTrackInfoArray_Count;
@property(copy, nonatomic) NSData *encryptedAdTrackData; // @dynamic encryptedAdTrackData;
@property(nonatomic) _Bool hasAdPosition; // @dynamic hasAdPosition;
@property(copy, nonatomic) NSData *serveItemId; // @dynamic serveItemId;
@property(copy, nonatomic) NSData *viewReceipt; // @dynamic viewReceipt;

@end

