//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, SCQueuePerformer, UIView;

@interface SCAdViewDebugViewer : NSObject
{
    UIView *_backgroundView;
    NSMutableDictionary *_adProductTypeToFilledAdViewCountMap;
    NSMutableDictionary *_adProductTypeToNoFillAdViewCountMap;
    NSMutableDictionary *_adProductTypeToLabelMap;
    SCQueuePerformer *_queuePerformer;
}

- (void).cxx_destruct;
- (id)_displayString:(unsigned long long)arg1 filledAdViewed:(long long)arg2 noFillAdViewed:(long long)arg3;
- (void)_updateLabelText;
- (void)_updateLabels;
- (void)_updateAdViewed:(unsigned long long)arg1 isFill:(_Bool)arg2;
- (void)updateAdViewed:(unsigned long long)arg1 isFill:(_Bool)arg2;
- (id)init;

@end

