//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCADiscoverAdSkip : SCAUserTrackedEvent
{
}

- (void)setViewSessionId:(id)arg1;
- (void)setThirdPartyDemandSourceEligibleList:(id)arg1;
- (void)setSource:(long long)arg1;
- (void)setSnapIndexPos:(long long)arg1;
- (void)setSnapIndexCount:(long long)arg1;
- (void)setScanActionId:(id)arg1;
- (void)setPublisherId:(id)arg1;
- (void)setPriorContentStoryTypeSpecific:(long long)arg1;
- (void)setPriorContentSnapId:(id)arg1;
- (void)setPetraQueryId:(id)arg1;
- (void)setFollowingContentStoryTypeSpecific:(long long)arg1;
- (void)setFollowingContentSnapId:(id)arg1;
- (void)setErrorInfo:(id)arg1;
- (void)setEntryEvent:(long long)arg1;
- (void)setEditionId:(id)arg1;
- (void)setDemandSource:(long long)arg1;
- (void)setDeepLinkId:(id)arg1;
- (void)setAdsnapPlacementId:(id)arg1;
- (void)setAdsnapLineItemId:(id)arg1;
- (void)setAdsnapId:(id)arg1;
- (void)setAdditionalInfo:(long long)arg1;
- (void)setAdUnitId:(id)arg1;
- (void)setAdSkipCount:(long long)arg1;
- (void)setAdServeItemId:(id)arg1;
- (void)setAdResolveTimeSec:(double)arg1;
- (void)setAdRequestId:(id)arg1;
- (void)setAdRequestClientId:(id)arg1;
- (void)setAdIndexPos:(long long)arg1;
- (void)setAdIndexCount:(long long)arg1;
- (void)setAdId:(id)arg1;
- (long long)getEventQoS;
- (id)getEventName;

@end

