//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, SCAdsDeviceInfo;

@interface SCAdsLensExplorerImpressionTrack : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCAdsDeviceInfo *deviceInfo; // @dynamic deviceInfo;
@property(nonatomic) _Bool hasDeviceInfo; // @dynamic hasDeviceInfo;
@property(retain, nonatomic) NSMutableArray *lensTileImpressionsArray; // @dynamic lensTileImpressionsArray;
@property(readonly, nonatomic) unsigned long long lensTileImpressionsArray_Count; // @dynamic lensTileImpressionsArray_Count;

@end

