//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCAMapTrayClose : SCAUserTrackedEvent
{
}

- (void)prepareDictionary:(id)arg1;
- (void)setWorldUpdateStoryViewCount:(long long)arg1;
- (void)setType:(long long)arg1;
- (void)setTraySessionId:(long long)arg1;
- (void)setSectionSummaries:(id)arg1;
- (void)setSearchTapCount:(long long)arg1;
- (void)setOpenTimeSeconds:(long long)arg1;
- (void)setMapSessionId:(long long)arg1;
- (void)setMapBestFriendCount:(long long)arg1;
- (void)setFriendTapCount:(long long)arg1;
- (void)setFriendActivityStoryViewCount:(long long)arg1;
- (void)setFriendActivityProfileViewCount:(long long)arg1;
- (void)setFriendActivityChatCreateCount:(long long)arg1;
- (void)setCloseMethod:(long long)arg1;
- (void)setBestFriendTapCount:(long long)arg1;
- (long long)getEventQoS;
- (id)getEventName;

@end

