//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@interface SCAMapTrayAction : SCAUserTrackedEvent
{
}

- (void)setType:(long long)arg1;
- (void)setTraySessionId:(long long)arg1;
- (void)setSectionItemIndex:(long long)arg1;
- (void)setSectionItemCount:(long long)arg1;
- (void)setSectionIndex:(long long)arg1;
- (void)setSectionCount:(long long)arg1;
- (void)setSection:(long long)arg1;
- (void)setMapSessionId:(long long)arg1;
- (void)setItemAgeSeconds:(long long)arg1;
- (void)setIsBestFriend:(_Bool)arg1;
- (void)setAction:(long long)arg1;
- (long long)getEventQoS;
- (id)getEventName;

@end

