//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, SCAppNotification, UIApplicationShortcutItem;
@protocol SCTConversationMetadata;

@protocol SCApplicationLifecycleNavigationHandler
- (void)handleApplicationWillEnterForegroundFromCallIntent:(NSString *)arg1 convoMetadata:(id <SCTConversationMetadata>)arg2 isVideo:(_Bool)arg3;
- (void)handleApplicationWillEnterForegroundFromNotification:(SCAppNotification *)arg1;
- (void)handleApplicationDidEnterBackground;
- (void)handleActionedAppNotification:(SCAppNotification *)arg1;
- (void)handleActionedShortcutItem:(UIApplicationShortcutItem *)arg1;
@end

