//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCArroyoChatLogging-Protocol.h"

@class SCLazy;

@interface SCArroyoChatLogger : NSObject <SCArroyoChatLogging>
{
    SCLazy *_logger;
    SCLazy *_feedPositionLogger;
    SCLazy *_unlockableViewTracker;
}

- (void).cxx_destruct;
- (void)_fetchCellPositionWithConversationId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)logChatMediaSendWithMessageSendResult:(id)arg1;
- (void)_logChatChatUnsave:(id)arg1 isGroupConversation:(_Bool)arg2 cellPosition:(long long)arg3;
- (void)logChatChatUnsave:(id)arg1 isGroupConversation:(_Bool)arg2;
- (void)_logChatChatSave:(id)arg1 isGroupConversation:(_Bool)arg2 messageRetentionInMinutes:(unsigned long long)arg3 cellPosition:(long long)arg4;
- (void)logChatChatSave:(id)arg1 isGroupConversation:(_Bool)arg2 messageRetentionInMinutes:(unsigned long long)arg3;
- (void)_logChatChatSendWithMessageSendResult:(id)arg1 cellPosition:(long long)arg2;
- (void)logChatChatSendWithMessageSendResult:(id)arg1;
- (void)logDirectSnapSendWithMessageSendResult:(id)arg1;
- (void)_logDirectSnapScreenshotWithMessage:(id)arg1 updateType:(long long)arg2 cellPosition:(long long)arg3 isGroupConversation:(_Bool)arg4;
- (void)logDirectSnapScreenshotWithMessage:(id)arg1 updateType:(long long)arg2 isGroupConversation:(_Bool)arg3;
- (void)_logGeofilterDirectSnapViewWithMessage:(id)arg1 mediaViewInfo:(id)arg2 venueId:(id)arg3;
- (void)_logDirectSnapReplayView:(id)arg1 contents:(id)arg2 mediaViewInfo:(id)arg3 isGroupConversation:(_Bool)arg4 cellPosition:(long long)arg5;
- (void)_logDirectSnapViewWithMessage:(id)arg1 contents:(id)arg2 mediaViewInfo:(id)arg3 isGroupConversation:(_Bool)arg4 cellPosition:(long long)arg5;
- (void)_logChatSnapViewWithMessage:(id)arg1 contents:(id)arg2 mediaViewInfo:(id)arg3 isGroupConversation:(_Bool)arg4 cellPosition:(long long)arg5;
- (void)logMediaViewWithMessage:(id)arg1 mediaViewInfo:(id)arg2 replayedByCurrentUser:(_Bool)arg3 isGroupConversation:(_Bool)arg4;
- (void)_logChatChatScreenshotWithResult:(id)arg1 cellPosition:(long long)arg2;
- (void)logChatChatScreenshotWithResult:(id)arg1;
- (void)_logChatChatViewWithUnseenMessage:(id)arg1 isGroupConversation:(_Bool)arg2 cellPosition:(long long)arg3;
- (void)logChatChatViewWithUnseenMessage:(id)arg1 isGroupConversation:(_Bool)arg2;
- (void)logSendMessageWithMessageResult:(id)arg1;
- (void)didSendComplete:(id)arg1;
- (void)didConversationUpdateForConversationId:(id)arg1 conversation:(id)arg2 updatedMessages:(id)arg3 removedMessages:(id)arg4;
- (void)didRemoveConversation:(id)arg1;
- (void)didCreateConversation:(id)arg1;
- (id)initWithUserTrackedLogger:(id)arg1 feedPositionLogger:(id)arg2 unlockableViewTracker:(id)arg3;

@end

