//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCArroyoFeedDataUpdateListener-Protocol.h"
#import "SCChatConversationMetadataUpdaterListener-Protocol.h"
#import "SCChatViewableSnapsUpdateProvider-Protocol.h"

@class NSArray, NSDictionary, NSString;
@protocol SCChatMetadataStore, SCChatViewableSnapsUpdateListener;

@interface SCArroyoOperaSnapProvider : NSObject <SCChatViewableSnapsUpdateProvider, SCArroyoFeedDataUpdateListener, SCChatConversationMetadataUpdaterListener>
{
    NSString *_conversationId;
    NSArray *_viewableSnaps;
    id <SCChatViewableSnapsUpdateListener> _listener;
    id <SCChatMetadataStore> _metadataStore;
    NSDictionary *_cachedMetadata;
}

- (void).cxx_destruct;
- (void)didFeedEntriesArrive:(id)arg1 fetchContext:(id)arg2;
- (void)didFetchFeedCompleteFeedEntries:(id)arg1 multiRecipientFeedEntries:(id)arg2 fetchContext:(id)arg3;
- (void)didQueryFeedCompleteFeedEntries:(id)arg1 hasNoMore:(_Bool)arg2 fetchContext:(id)arg3;
- (void)didFetchAndSyncFeedCompleteUpdatedFeedEntries:(id)arg1 multiRecipientFeedEntries:(id)arg2 deletedFeedEntries:(id)arg3 fetchContext:(id)arg4;
- (void)didSyncFeedCompleteUpdatedFeedEntries:(id)arg1 multiRecipientFeedEntries:(id)arg2 deletedFeedEntries:(id)arg3 fetchContext:(id)arg4;
- (void)didUpdateFeedEntries:(id)arg1 multiRecipientFeedEntries:(id)arg2 deletedFeedEntries:(id)arg3 multiRecipientFeedEntriesDeleted:(id)arg4;
- (void)_announceSnapUpdateWithMessages:(id)arg1;
- (void)conversationDidUpdate:(id)arg1 metadata:(id)arg2;
- (void)getViewableSnaps:(CDUnknownBlockType)arg1;
- (void)setListener:(id)arg1;
- (id)initWithConversationId:(id)arg1 initialViewableSnaps:(id)arg2 metadataStore:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

