//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SCStickerPackMetadataLoadingService;

@interface SCBitmojiStickerPackMetadataLoader : NSObject
{
    id <SCStickerPackMetadataLoadingService> _metadataLoadingServices;
}

- (void).cxx_destruct;
- (id)_targetFromSubpack:(id)arg1;
- (id)processUpdates:(id)arg1 deletions:(id)arg2 withStickerPack:(id)arg3 andExistingMegaPackMetadata:(id)arg4;
- (void)downloadStickerPackMetadata:(id)arg1 existingMegaPackMetadata:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)canGenerateGroupKeyFromStickerPack:(id)arg1;
- (id)initWithMetadataLoadingService:(id)arg1;

@end

