//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCBloopsTargetCandidatesCellOutput-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UICollectionView;
@protocol SCBloopsTargetCandidatesViewOutput;

@interface SCBloopsTargetCandidatesDisplayManager : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, SCBloopsTargetCandidatesCellOutput>
{
    UICollectionView *_collectionView;
    id <SCBloopsTargetCandidatesViewOutput> _ouput;
    NSMutableArray *_cellModels;
}

- (void).cxx_destruct;
- (void)targetCandidatesCellDidTap:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)setTargetCandidatesCellModels:(id)arg1;
- (void)updateCellAtIndex:(unsigned long long)arg1 withItem:(id)arg2 animated:(_Bool)arg3;
- (id)initWithCollectionView:(id)arg1 output:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

