//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIViewController;
@protocol SCBloopsModel;

@protocol SCBloopsExportPresenter <NSObject>
- (void)presentSharingViewFrom:(UIViewController *)arg1 sectionAnalyticId:(NSString *)arg2 nickName:(NSString *)arg3 withBloopsModel:(id <SCBloopsModel>)arg4 completion:(void (^)(NSString *, _Bool, NSError *))arg5;
@end

