//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCBloopsAPIListener-Protocol.h"
#import "SCBloopsDataCoordinator-Protocol.h"

@class NSString, SCDataCoordinatorListenerAnnouncer;
@protocol SCBloopsAPI;

@interface SCBloopsDataCoordinatorImpl : NSObject <SCBloopsAPIListener, SCBloopsDataCoordinator>
{
    SCDataCoordinatorListenerAnnouncer *_eventAnnouncer;
    id <SCBloopsAPI> _bloopsAPI;
}

+ (id)dataCoordinatorIdentifier;
- (void).cxx_destruct;
- (void)_announceDataCoordinatorUpdateWithDataRequest:(id)arg1;
- (void)_didUpdatePersonsSource:(id)arg1;
- (void)bloopsAPIDidResetPersonsSource:(id)arg1;
- (void)bloopsAPIDidSaveMainPerson:(id)arg1;
- (void)bloopsAPI:(id)arg1 didChangeBloopsFeatureStatus:(_Bool)arg2;
- (void)handleDataRequest:(id)arg1;
- (id)initWithBloopsAPI:(id)arg1;
- (void)removeDataUpdateListener:(id)arg1;
- (void)addDataUpdateListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

