//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "SCBloopsPreviewsViewInput-Protocol.h"
#import "SPPreviewsModuleOutput-Protocol.h"

@class NSString, Splendid;
@protocol SCBloopsPreviewsDataSource, SCBloopsPreviewsViewOutput, SPPreviewsModuleInput;

@interface SCBloopsPreviewsViewImpl : UICollectionViewCell <SPPreviewsModuleOutput, SCBloopsPreviewsViewInput>
{
    Splendid *_splendidInstance;
    _Bool _isHorizontalScrollDirection;
    double _topMargin;
    id <SPPreviewsModuleInput> _previewsModuleInput;
    id <SCBloopsPreviewsViewOutput> _delegate;
    id <SCBloopsPreviewsDataSource> _dataSource;
}

@property(retain, nonatomic) id <SCBloopsPreviewsDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SCBloopsPreviewsViewOutput> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_experimentManager;
- (void)_copyVersionsInfo;
- (void)_updatePreviewsFrame;
- (void)spPreviewsModuleDidTapRetakeSelfieSectionCloseButton:(id)arg1;
- (void)spPreviewsModuleDidTapRetakeSelfieSectionButton:(id)arg1;
- (void)spPreviewsModuleDidTapEnableTwoPersonBottomSectionButton:(id)arg1;
- (void)spPreviewsModuleDidTapEnableTwoPersonTopSectionCloseButton:(id)arg1;
- (void)spPreviewsModuleDidTapEnableTwoPersonTopSectionButton:(id)arg1;
- (void)spPreviewsModuleDidResetSelection:(id)arg1;
- (void)spPreviewsModule:(id)arg1 willStartPlayScenarioAtIndex:(unsigned long long)arg2;
- (void)spPreviewsModule:(id)arg1 didHideScenarioAtIndex:(unsigned long long)arg2;
- (void)spPreviewsModule:(id)arg1 willShowScenarioAtIndex:(unsigned long long)arg2;
- (void)spPreviewsModule:(id)arg1 beginDragging:(id)arg2;
- (void)spPreviewsModule:(id)arg1 didDoubleTapOnScenarioAtIndex:(unsigned long long)arg2;
- (void)spPreviewsModule:(id)arg1 didLongTapOnScenarioAtIndex:(unsigned long long)arg2 pressHoldGuideIsVisible:(_Bool)arg3;
- (void)spPreviewsModule:(id)arg1 didTapOnScenarioAtIndex:(unsigned long long)arg2 inScenarios:(id)arg3 pressHoldGuideIsVisible:(_Bool)arg4;
- (void)spPreviewsModule:(id)arg1 didObtainScenarios:(id)arg2 tags:(id)arg3 topic:(id)arg4 iconScenario:(id)arg5;
- (void)spPreviewsModule:(id)arg1 encounteredError:(id)arg2;
- (id)getAttributionOfItemAtIndex:(unsigned long long)arg1;
@property(nonatomic) _Bool scrollEnabled;
- (void)setNeedsShowRetakeSelfieSection:(_Bool)arg1 withPanelImage:(id)arg2 animated:(_Bool)arg3;
- (void)hidePressHoldGuide;
- (void)showPressHoldGuideIfNeeded;
- (void)setNeedsShowEnableTwoPersonBottomSection:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setNeedsShowEnableTwoPersonTopSection:(_Bool)arg1 animated:(_Bool)arg2;
- (id)getThumbnailForBloopsModel:(id)arg1;
- (void)resetSelection;
- (_Bool)isHorizontalScrollDirection;
- (id)getViewFromItemAtIndex:(unsigned long long)arg1;
- (unsigned long long)getPreviewsHeight;
- (void)didChangeMutedState:(_Bool)arg1;
- (void)didChangeVolume:(double)arg1;
- (void)tuneViewDueToDrawerSizeChanged:(double)arg1 toolbarHeight:(double)arg2;
- (id)getBloopIdForIndex:(unsigned long long)arg1;
- (void)exitVisibleState;
- (void)enterVisibleState;
- (_Bool)isItemFullyVisibleAtIndex:(unsigned long long)arg1;
- (_Bool)isItemAtIndexInLastRow:(unsigned long long)arg1;
- (id)getSelectedIndex;
- (_Bool)isInSelectedState;
- (void)selectItemAtIndex:(unsigned long long)arg1;
- (void)scrollToItemAtIndex:(unsigned long long)arg1 animated:(_Bool)arg2;
- (id)getBloops;
- (id)uiState;
- (void)restoreUIState:(id)arg1;
- (void)setupPreviewsDataSource:(id)arg1 previewsViewLayout:(id)arg2;
@property(nonatomic) struct UIEdgeInsets scrollViewContentInsets;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)prepareForReuse;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

