//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SPScenario, UIImage;
@protocol SCBloopsStickersPreviewsViewInput;

@protocol SCBloopsStickersPreviewsViewOutput <NSObject>
- (void)stickersPreviewsViewDidTapNewSelfieBottomButton:(id <SCBloopsStickersPreviewsViewInput>)arg1;
- (void)stickersPreviewsViewDidTapEnableTwoPersonBottomButton:(id <SCBloopsStickersPreviewsViewInput>)arg1;
- (void)stickersPreviewsViewDidTapEnableTwoPersonTopSectionCloseButton:(id <SCBloopsStickersPreviewsViewInput>)arg1;
- (void)stickersPreviewsViewDidTapEnableTwoPersonTopSectionButton:(id <SCBloopsStickersPreviewsViewInput>)arg1;
- (_Bool)stickersPreviewsViewShouldShowEnableTwoPersonBottomButton:(id <SCBloopsStickersPreviewsViewInput>)arg1;
- (_Bool)stickersPreviewsViewShouldShowEnableTwoPersonTopSectionButton:(id <SCBloopsStickersPreviewsViewInput>)arg1;
- (void)stickersPreviewsView:(id <SCBloopsStickersPreviewsViewInput>)arg1 didSelectScenario:(SPScenario *)arg2 image:(UIImage *)arg3 index:(unsigned long long)arg4 cellCenter:(struct CGPoint)arg5;
@end

