//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCMainCameraScope, SCNavigationServices, SCScopeExposer, SCServicesExposer, SCUserSessionScope;

@interface SCCameraToGallerySwipeTransitionCoordinatorEntryPoint : SCEntryPoint
{
    SCUserSessionScope *_userSessionScope;
    SCNavigationServices *_navigationServices;
    SCMainCameraScope *_mainCameraScope;
    SCScopeExposer *_memoriesScopeExposer;
    SCServicesExposer *_cameraToGallerySwipeTransitionCoordinatorServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *cameraToGallerySwipeTransitionCoordinatorServicesExposer; // @synthesize cameraToGallerySwipeTransitionCoordinatorServicesExposer=_cameraToGallerySwipeTransitionCoordinatorServicesExposer;
@property(retain, nonatomic) SCScopeExposer *memoriesScopeExposer; // @synthesize memoriesScopeExposer=_memoriesScopeExposer;
@property(nonatomic) __weak SCMainCameraScope *mainCameraScope; // @synthesize mainCameraScope=_mainCameraScope;
@property(nonatomic) __weak SCNavigationServices *navigationServices; // @synthesize navigationServices=_navigationServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
- (void).cxx_destruct;
- (void)begin;

@end

