//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCBitmojiPasteDelegate-Protocol.h"
#import "SCBloopsPickerAccessoryOutput-Protocol.h"
#import "SCBloopsStickersTooltipPresenterOutput-Protocol.h"
#import "SCBloopsStickersTooltipPresenterViewProvider-Protocol.h"
#import "SCChatConversationUpdaterListener-Protocol.h"
#import "SCChatDrawerLogger-Protocol.h"
#import "SCChatInputDrawerRenderable-Protocol.h"
#import "SCChatInputStickerLogProvider-Protocol.h"
#import "SCChatInputTextViewListener-Protocol.h"
#import "SCChatStickerFuzzySearchDelegate-Protocol.h"
#import "SCChatStickerManagerListener-Protocol.h"
#import "SCCustomStickerManagerListener-Protocol.h"
#import "SCStickerPickerMenuDelegate-Protocol.h"
#import "SCStickerStoryReplyViewControllerDelegate-Protocol.h"
#import "SCTraceEnabled-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSMutableSet, NSString, SCBitmojiPasteManager, SCBloopsPickerSuperCategory, SCBloopsSearchIconQuery, SCChatInputItem, SCChatInputViewController, SCChatStickerFavoritesGenerator, SCLazy, SCStickerDataProvider, SCStickerPageDataSource, SCStickerStoryReplyViewController, SCUserSession, SOJUSticker, UIScrollView;
@protocol SCBitmojiAvatarBuilderRouterDelegate, SCBloopsPickerAccessory, SCCanceling, SCChatInputStickerAccessorySender, SCChatInputStickerAudioDelegate, SCChatInputStickerStoryCarouselDelegate;

@interface SCChatInputStickerAccessory : UIViewController <SCChatStickerManagerListener, SCChatStickerFuzzySearchDelegate, SCTraceEnabled, SCStickerPickerMenuDelegate, SCCustomStickerManagerListener, SCBitmojiPasteDelegate, UIGestureRecognizerDelegate, SCStickerStoryReplyViewControllerDelegate, SCBloopsPickerAccessoryOutput, SCBloopsStickersTooltipPresenterViewProvider, SCBloopsStickersTooltipPresenterOutput, SCChatDrawerLogger, SCChatInputDrawerRenderable, SCChatInputTextViewListener, SCChatConversationUpdaterListener, SCChatInputStickerLogProvider>
{
    NSArray *_autocompleteStickers;
    _Bool _notifySearchResults;
    long long _sentItems;
    UIScrollView *_dummyScrollView;
    SCLazy *_stickerPickerController;
    SCStickerDataProvider *_stickerDataProvider;
    SCChatStickerFavoritesGenerator *_chatStickerFavorites;
    SCLazy *_chatStickerSearch;
    CDUnknownBlockType _stickerSearchBlock;
    SCUserSession *_userSession;
    id <SCBitmojiAvatarBuilderRouterDelegate> _bitmojiAvatarBuilderRouterDelegate;
    id <SCChatInputStickerStoryCarouselDelegate> _chatInputStickerStoryCarouselDelegate;
    id <SCChatInputStickerAudioDelegate> _chatInputStickerAudioDelegate;
    UIViewController *_fullscreenPresentingViewController;
    SCStickerPageDataSource *_recentPageDataSource;
    SCStickerPageDataSource *_searchPageDataSource;
    SCStickerPageDataSource *_homeTabPageDataSource;
    SCBloopsPickerSuperCategory *_bloopsSuperCategory;
    NSArray *_stickerPackages;
    NSArray *_geoStickerPackages;
    NSArray *_bitmojiStickerPackages;
    id <SCCanceling> _inputItemImageRequest;
    SOJUSticker *_currentInputItemSticker;
    SCLazy *_stickerAutocompleteViewControllerV2;
    NSString *_activeConversationId;
    SCLazy *_stickerAutosuggestTooltip;
    SCStickerStoryReplyViewController *_stickerStoryReplyViewController;
    _Bool _highlightTextOnBecomeFirstResponder;
    SCBitmojiPasteManager *_bitmojiPasteManager;
    struct CGSize _lastSize;
    _Bool _shouldClearSearchResults;
    NSString *_currentSearchTerm;
    _Bool _drawerRequiresUpdateOnActivation;
    NSMutableSet *_stickerPackageDirtyFlags;
    unsigned long long _inputItemState;
    id <SCBloopsPickerAccessory> _bloopsPickerAccessory;
    SCLazy *_bloopsSearchIconProvider;
    SCBloopsSearchIconQuery *_bloopsSearchIconQuery;
    SCLazy *_bloopsStickersTooltipPresenter;
    _Bool _isUpdateSpecialPackagesInProgress;
    _Bool _showCustomTextInBloopsCategories;
    _Bool _shouldOpenBloopsSuperCategoryByDeeplink;
    _Bool _shouldEnableHometab;
    long long _recentsCategoryBackfillMax;
    long long _hometabCategoryBackfillMax;
    _Bool _isHomeTabHorizontalScrolling;
    _Bool _shouldOpenDrawerMaximized;
    long long _currentlySelectedSuperCategory;
    SCChatInputItem *_inputItem;
    SCChatInputViewController *_inputController;
    double _defaultDrawerHeight;
    id <SCChatInputStickerAccessorySender> _sender;
}

@property(nonatomic) __weak id <SCChatInputStickerAccessorySender> sender; // @synthesize sender=_sender;
@property(nonatomic) double defaultDrawerHeight; // @synthesize defaultDrawerHeight=_defaultDrawerHeight;
@property(nonatomic) __weak SCChatInputViewController *inputController; // @synthesize inputController=_inputController;
@property(nonatomic) __weak SCChatInputItem *inputItem; // @synthesize inputItem=_inputItem;
- (void).cxx_destruct;
- (void)_reportStickerChatPickForType:(id)arg1 stickerLocation:(long long)arg2;
- (void)_reportStickerChatPickForSticker:(id)arg1 stickerLocation:(long long)arg2;
- (void)_reportStickerChatPickForBloop:(id)arg1 stickerLocation:(long long)arg2;
- (void)_reloadStickerDataProvider;
- (id)_createBloopsSuperCategory;
- (_Bool)_haveBloopsInSearchResult;
- (_Bool)_isCurrentDrawer;
- (void)_categoryCellScrollViewWillBeginDragging:(id)arg1;
- (void)_openBloopsSuperCategoryIfNeeded;
- (void)bloopsCustomTextTooltipPresenterDidEndShowTooltip:(id)arg1;
- (void)bloopsCustomTextTooltipPresenterWillShowTooltip:(id)arg1;
- (void)bloopsOnboardingTooltipPresenterDidEndShowTooltip:(id)arg1;
- (void)bloopsOnboardingTooltipPresenterWillShowTooltip:(id)arg1;
- (id)bloopsPickerTooltipSuperView;
- (id)bloopsPickerTooltipTargetView;
- (void)bloopsPickerController:(id)arg1 didOverridingMuteSwitch:(_Bool)arg2;
- (void)bloopsPickerScrollViewWillBeginDragging:(id)arg1 isHorizontalScrollDirection:(_Bool)arg2;
- (void)bloopsPickerControllerDidSetUserTargetInOnboarding:(id)arg1;
- (void)bloopsPickerControllerDidChangeData:(id)arg1;
- (void)bloopsPickerController:(id)arg1 didTapSendBloopWithMediaContentProvider:(id)arg2 gridIndex:(unsigned long long)arg3 fromFullscreen:(_Bool)arg4 dataSource:(id)arg5 viewTimeInMilliseconds:(unsigned long long)arg6 sentBloopFeatures:(id)arg7 notSentBloopFeatures:(id)arg8;
- (id)bloopsPickerFullscreenViewController:(id)arg1;
- (id)_createHomeTabPageDataSource;
- (id)_createRecentPageDataSource;
- (id)_createSearchPageDataSource;
- (void)stickerStoryReplyViewController:(id)arg1 stickerTapped:(id)arg2 fromPosition:(unsigned long long)arg3 fromSource:(long long)arg4;
- (_Bool)_allowBloopsForAdditionalCategories;
- (void)_fetchSticker:(id)arg1 contexts:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_updateInputItemWithImage:(id)arg1 selectedImage:(id)arg2 sticker:(id)arg3 animationStyle:(unsigned long long)arg4;
- (void)_updateInputItemWithSticker:(id)arg1 animationStyle:(unsigned long long)arg2;
- (long long)previewIconProvider;
- (_Bool)openedWithSearch;
- (long long)sentItemCount;
- (long long)drawerType;
- (double)_topMargin;
- (void)friendmojiAvatarPickerClosedWithFriendmojiType:(long long)arg1 selectedStickerId:(id)arg2;
- (_Bool)friendmojiHintRequestedWithTargetView:(id)arg1 delegate:(id)arg2;
- (_Bool)avatarPickerRequestedWithBitmojiUsers:(id)arg1 targetView:(id)arg2 delegate:(id)arg3;
- (void)stickerPickerCategoryCellScrollViewWillBeginDragging:(id)arg1;
- (void)stickerPickerMenu:(id)arg1 didSelectSticker:(id)arg2 center:(struct CGPoint)arg3 thumbnail:(id)arg4 stickerIndex:(unsigned long long)arg5 categoryIndex:(unsigned long long)arg6 isFromRecents:(_Bool)arg7 searchTag:(id)arg8;
- (void)closedStickerPickerMenuAtCategory:(id)arg1 sticker:(id)arg2 enterSearchCount:(long long)arg3 pretypeStickerTagSelectCount:(long long)arg4 prefixMatchStickerTagSelectCount:(long long)arg5;
- (void)openedStickerPickerMenuAtCategory:(id)arg1;
- (void)_updateStoryReplyViewWithStickers:(id)arg1;
- (void)updateMiniatureView;
- (void)searchResultDidChangeBecauseOfAutoCorrection;
- (void)setNotifySearchResults:(_Bool)arg1 searchTerm:(id)arg2;
- (void)customStickerAutoSectionDataDidChange;
- (void)customStickerDataDidChange;
- (void)_handleStickerPackagesDidChangeWithCategoryType:(long long)arg1;
- (void)stickerPackagesDidChangeWithCategoryType:(long long)arg1;
- (id)stickerAutosuggestTooltip;
- (void)_showStickerTooltip;
- (id)dummyScrollView;
- (struct CGRect)_maximumDrawerFrame;
- (id)_updateUnlockedStickersIfNecessary;
- (id)_updateSnapchatAndSnapartStickersIfNecessary;
- (id)_updateBitmojiStickersIfNecessary;
- (id)_updateHomeTabStickersIfNecessary;
- (id)_updateRecentStickersIfNecessary;
- (id)_updateSearchStickersIfNecessary;
- (id)_updateBloopsIfNecessary;
- (id)_updateStickerDataProvider;
- (void)_updateStickerPackageIfNecessary;
- (void)_scrollToTopOfCategory;
- (void)_openToInitialStickerPickerCategory;
- (void)_updateStickerManager:(CDUnknownBlockType)arg1;
- (void)_insertStickerPickerControllerConetentView:(id)arg1;
- (id)_stickerPickerController;
- (void)_resetAutosuggestViewWithAnimationStyle:(unsigned long long)arg1;
- (void)_clearStickerPickerSearchCategoryImmediately:(_Bool)arg1;
- (void)_clearStickerSearchImmediately:(_Bool)arg1;
- (void)_stickerSearch:(id)arg1;
- (void)_stopStickerSearch;
- (void)_startStickerSearch:(id)arg1 immediately:(_Bool)arg2;
- (void)_updateStickerSearch:(id)arg1 immediately:(_Bool)arg2;
- (void)inputViewController:(id)arg1 textViewDidReturn:(id)arg2;
- (void)inputViewController:(id)arg1 textViewDidBeginEditing:(id)arg2;
- (void)inputViewController:(id)arg1 textViewDidEndEditing:(id)arg2;
- (void)inputViewController:(id)arg1 textViewDidChange:(id)arg2;
- (void)_resetDrawerOnConversationChange;
- (void)didConversationViewModelChange:(id)arg1;
- (void)bitmojiKeyboardDidPasteBitmojiSticker:(id)arg1;
- (void)didActivateDrawerWithDeeplinkIdentifier:(id)arg1 subitemDeeplinkIdentifier:(id)arg2;
- (void)willSuspendActive;
- (void)willResumeActive;
- (void)didResignActive;
- (void)willResignActive;
- (void)didBecomeActive;
- (void)willBecomeActive;
- (void)sizeDidChange:(struct CGSize)arg1;
- (void)didEndPanningToState:(unsigned long long)arg1;
- (void)willEndPanningToState:(unsigned long long)arg1;
- (void)didPanFromState:(unsigned long long)arg1;
- (void)willBeginPanningFromState:(unsigned long long)arg1;
- (_Bool)canPanDrawer;
- (double)maximumDrawerHeight;
- (void)_addStickerStoryReplyViewToController;
- (void)_addAutocompleteViewToController;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_longPressDidCancel;
- (void)_longPressDidEnd:(struct CGPoint)arg1;
- (void)_longPressDidChange:(struct CGPoint)arg1;
- (void)_longPressDidBegin;
- (void)_handleLongPress:(id)arg1;
- (id)bloopsChatDrawerActioMetadataForActionType:(long long)arg1;
- (_Bool)isBitmojiTabVisible;
- (void)loadView;
- (void)dealloc;
- (id)initWithChatStickerSearch:(id)arg1 userSession:(id)arg2 stickerFavorites:(id)arg3 sender:(id)arg4 bitmojiAvatarBuilderRouterDelegate:(id)arg5 chatInputStickerStoryCarouselDelegate:(id)arg6 chatInputStickerAudioDelegate:(id)arg7 bloopsPickerAccessory:(id)arg8 bloopsSearchIconProvider:(id)arg9 bloopsStickersTooltipPresenter:(id)arg10 fullscreenPresentingViewController:(id)arg11 showCustomTextInBloopsCategories:(_Bool)arg12;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

