//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"

@class NSString, SCChatMediaReferenceManager, SCChatV3ConversationStore, SCChatV3FeedUpdater, SCChatV3MediaExtensionCacheHandler, SCChatV3MetadataStore, SCLazy;
@protocol SCChatLogger, SCMediaSendTaskManager, SCPerforming;

@interface SCChatV3MessageStateHandler : NSObject <SCTraceEnabled>
{
    SCChatV3FeedUpdater *_feedUpdater;
    SCChatMediaReferenceManager *_mediaReferenceManager;
    id <SCMediaSendTaskManager> _mediaSendTaskManager;
    SCChatV3ConversationStore *_conversationStore;
    SCChatV3MediaExtensionCacheHandler *_mediaExtensionCacheHandler;
    SCChatV3MetadataStore *_metadataStore;
    SCLazy *_groupsDataMutator;
    id <SCPerforming> _performer;
    id <SCChatLogger> _chatLogger;
    SCLazy *_autoShakeToReporter;
    NSString *_username;
}

- (void).cxx_destruct;
- (id)_updateLastInteractionTimestampIfNecessary:(id)arg1;
- (id)applyEraseMessage:(id)arg1 toConversation:(id)arg2;
- (id)applyOneOnOneSnapStateMessage:(id)arg1 toConversation:(id)arg2;
- (id)_modifySnapState:(id)arg1 withOneOnOneSnapStateMessage:(id)arg2;
- (id)_modifySnapState:(id)arg1 withSnapStateMessage:(id)arg2;
- (id)applySnapStateMessage:(id)arg1 toConversation:(id)arg2;
- (id)_modifyChatMessage:(id)arg1 withPreservationMessage:(id)arg2;
- (id)_modifyChatMessage:(id)arg1 withStateMessage:(id)arg2;
- (id)deleteExParticipantMessagesFromConversation:(id)arg1;
- (id)deleteExpiredMessagesFromConversation:(id)arg1;
- (void)deleteExpiredMessages:(id)arg1;
- (void)deleteExpiredMessagesFromConversationId:(id)arg1;
- (id)applyPreservationMessage:(id)arg1 toConversation:(id)arg2;
- (id)applyStateMessage:(id)arg1 toConversation:(id)arg2;
- (id)updateMessages:(id)arg1 conversation:(id)arg2;
- (id)releaseSnapsInConversation:(id)arg1;
- (id)releaseSnapsInConversation:(id)arg1 before:(id)arg2;
- (id)releaseMessages:(id)arg1 inConversation:(id)arg2 forUsername:(id)arg3 atTime:(id)arg4;
- (id)addOneOnOneSnapMessage:(id)arg1 toConversation:(id)arg2;
- (id)addMessages:(id)arg1 toConversation:(id)arg2;
- (id)replaceMessages:(id)arg1 inConversation:(id)arg2;
- (void)_removeMediaSendTasksForMessageIds:(id)arg1 inConversation:(id)arg2;
- (void)_removeCachedContentsForMessagesByIds:(id)arg1 inConversation:(id)arg2;
- (void)_removeCacheContentsForMessages:(id)arg1 convId:(id)arg2;
- (void)_removeMetadataFromStoreAndFeedForMessageIds:(id)arg1 conversationId:(id)arg2;
- (id)removeMessagesWithMessageIds:(id)arg1 inConversation:(id)arg2;
- (void)dealloc;
- (id)initWithfeedUpdater:(id)arg1 withMediaReferenceManager:(id)arg2 conversationStore:(id)arg3 metadataStore:(id)arg4 groupsDataMutator:(id)arg5 performer:(id)arg6 chatLogger:(id)arg7 username:(id)arg8 autoShakeToReporter:(id)arg9 mediaSendTaskManager:(id)arg10 mediaExtensionCacheHandler:(id)arg11;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

