//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCChatLoadConversationHistoryActionData : NSObject <NSCopying>
{
    _Bool _shouldRetry;
    NSString *_conversationId;
    NSString *_sinceMessageId;
}

@property(readonly, nonatomic) _Bool shouldRetry; // @synthesize shouldRetry=_shouldRetry;
@property(readonly, copy, nonatomic) NSString *sinceMessageId; // @synthesize sinceMessageId=_sinceMessageId;
@property(readonly, copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithConversationId:(id)arg1 sinceMessageId:(id)arg2 shouldRetry:(_Bool)arg3;

@end

