//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCNContentManagerContentRetrievalMetrics;

@interface SCChatContentDeliveryLogItem : NSObject <NSCopying>
{
    unsigned long long _subtype;
    NSString *_downloadItem_mediaId;
    long long _downloadItem_status;
    SCNContentManagerContentRetrievalMetrics *_downloadItem_metrics;
    double _downloadItem_startTimestampSeconds;
    double _downloadItem_endTimestampSeconds;
    NSString *_retrieveContent_mediaId;
    long long _retrieveContent_status;
    SCNContentManagerContentRetrievalMetrics *_retrieveContent_metrics;
    double _retrieveContent_startTimestampSeconds;
    double _retrieveContent_endTimestampSeconds;
    NSString *_registerZipContents_mediaId;
    long long _registerZipContents_result;
    double _registerZipContents_startTimestampSeconds;
    double _registerZipContents_endTimestampSeconds;
    NSString *_storeMedia_mediaId;
    long long _storeMedia_result;
    double _storeMedia_startTimestampSeconds;
    double _storeMedia_endTimestampSeconds;
    NSString *_generateThumbnail_mediaId;
    long long _generateThumbnail_result;
    double _generateThumbnail_startTimestampSeconds;
    double _generateThumbnail_endTimestampSeconds;
}

+ (id)storeMediaWithMediaId:(id)arg1 result:(long long)arg2 startTimestampSeconds:(double)arg3 endTimestampSeconds:(double)arg4;
+ (id)retrieveContentWithMediaId:(id)arg1 status:(long long)arg2 metrics:(id)arg3 startTimestampSeconds:(double)arg4 endTimestampSeconds:(double)arg5;
+ (id)registerZipContentsWithMediaId:(id)arg1 result:(long long)arg2 startTimestampSeconds:(double)arg3 endTimestampSeconds:(double)arg4;
+ (id)generateThumbnailWithMediaId:(id)arg1 result:(long long)arg2 startTimestampSeconds:(double)arg3 endTimestampSeconds:(double)arg4;
+ (id)downloadItemWithMediaId:(id)arg1 status:(long long)arg2 metrics:(id)arg3 startTimestampSeconds:(double)arg4 endTimestampSeconds:(double)arg5;
- (void).cxx_destruct;
- (void)matchDownloadItem:(CDUnknownBlockType)arg1 retrieveContent:(CDUnknownBlockType)arg2 registerZipContents:(CDUnknownBlockType)arg3 storeMedia:(CDUnknownBlockType)arg4 generateThumbnail:(CDUnknownBlockType)arg5;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

