//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCActiveUserSessionScope, SCLocationSharingServices, SCServicesExposer, SCSnapTokenServices, SCUserFeatureConfigurationServices;

@interface SCCheckInServicesEntryPoint : SCEntryPoint
{
    SCActiveUserSessionScope *_activeUserSessionScope;
    SCUserFeatureConfigurationServices *_userFeatureConfigurationServices;
    SCLocationSharingServices *_locationSharingServices;
    SCSnapTokenServices *_snapTokenServices;
    SCServicesExposer *_checkInServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *checkInServicesExposer; // @synthesize checkInServicesExposer=_checkInServicesExposer;
@property(nonatomic) __weak SCSnapTokenServices *snapTokenServices; // @synthesize snapTokenServices=_snapTokenServices;
@property(nonatomic) __weak SCLocationSharingServices *locationSharingServices; // @synthesize locationSharingServices=_locationSharingServices;
@property(nonatomic) __weak SCUserFeatureConfigurationServices *userFeatureConfigurationServices; // @synthesize userFeatureConfigurationServices=_userFeatureConfigurationServices;
@property(nonatomic) __weak SCActiveUserSessionScope *activeUserSessionScope; // @synthesize activeUserSessionScope=_activeUserSessionScope;
- (void).cxx_destruct;
- (id)_updater;
- (id)_optionReporter;
- (id)_optionFetcher;
- (void)begin;

@end

