//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSArray, NSDictionary, SCFriendsFeedFetchContext;

@protocol SCChatConversationBatchFetching
- (void)batchFetchConversationsFromServerByIds:(NSArray *)arg1;
- (void)batchFetchConversationsWithClientSyncData:(NSDictionary *)arg1 serverSyncData:(NSDictionary *)arg2 updateType:(long long)arg3 fetchContext:(SCFriendsFeedFetchContext *)arg4;
@end

