//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCGroupActionHandler-Protocol.h"

@class SCChatV3ConversationStore, SCLazy;

@interface SCChatV3GroupActionHandler : NSObject <SCGroupActionHandler>
{
    SCChatV3ConversationStore *_conversationStore;
    SCLazy *_groupsDataFetcher;
    SCLazy *_groupsDataMutator;
}

- (void).cxx_destruct;
- (void)getGroupByParticipants:(id)arg1 completion:(CDUnknownBlockType)arg2 callbackQueue:(id)arg3;
- (void)_updateChatConversationWithGroup:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)grantGroupExemptBlockedUsersWithId:(id)arg1 newBlockedParticipantExceptions:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithConversationStore:(id)arg1 groupsDataFetcher:(id)arg2 groupsDataMutator:(id)arg3;

@end

