//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCChangeLanguageInSettingsActionRecordingServices, SCChangeLanguageInSettingsPromptWorkflow, SCDisposableObserverLifecycle, SCDynamicLocaleEventServices, SCSystemScope;

@interface SCChangeLanguageInSettingsPromptEntryPoint : SCEntryPoint
{
    SCDisposableObserverLifecycle *_dynamicLocaleEventLifecycle;
    SCChangeLanguageInSettingsPromptWorkflow *_workflow;
    SCSystemScope *_systemScope;
    SCDynamicLocaleEventServices *_dynamicLocaleEventServices;
    SCChangeLanguageInSettingsActionRecordingServices *_changeLanguageInSettingsActionRecordingServices;
}

@property(nonatomic) __weak SCChangeLanguageInSettingsActionRecordingServices *changeLanguageInSettingsActionRecordingServices; // @synthesize changeLanguageInSettingsActionRecordingServices=_changeLanguageInSettingsActionRecordingServices;
@property(nonatomic) __weak SCDynamicLocaleEventServices *dynamicLocaleEventServices; // @synthesize dynamicLocaleEventServices=_dynamicLocaleEventServices;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
- (void).cxx_destruct;
- (void)_startPromptWorkflow;
- (void)begin;

@end

