//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class NSMutableArray, SCContextV3ActionPerformerScope, SCNavigationServices, SCSnapchatterServices;

@interface SCContextV3ActionRegistryEntryPoint : SCEntryPoint
{
    NSMutableArray *_deregister;
    SCNavigationServices *_navigationServices;
    SCSnapchatterServices *_snapchatterServices;
    SCContextV3ActionPerformerScope *_actionPerformerScope;
}

@property(nonatomic) __weak SCContextV3ActionPerformerScope *actionPerformerScope; // @synthesize actionPerformerScope=_actionPerformerScope;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;
@property(nonatomic) __weak SCNavigationServices *navigationServices; // @synthesize navigationServices=_navigationServices;
- (void).cxx_destruct;
- (void)registerActionPerformerWithActionCase:(int)arg1 provider:(CDUnknownBlockType)arg2;
- (id)_createUserProfileActionPerformer;
- (id)_createStoryReplyActionPerformer;
- (id)_createStoryInviteActionPerformer;
- (id)_createPublicProfileActionPerformer;
- (id)_createLinkActionPerformer;
- (id)_createLensActionPerformer;
- (id)_createGroupInviteActionPerformer;
- (id)_createGameActionPerformer;
- (id)_createCameraActionPerformer;
- (id)end;
- (void)begin;

@end

