//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCBusinessLogic.h"

@class NSArray, NSError, NSString, SCCommerceCheckoutDataModel, SCQueuePerformer;
@protocol SCCommerceAccountInfoFetching, SCCommerceAccountInfoMutating, SCCommerceCheckoutCoordinating, SCCommerceEventLogger, SCCommerceShippingSelectDelegate;

@interface SCCommerceCheckoutShippingBusinessLogic : SCBusinessLogic
{
    SCCommerceCheckoutDataModel *_checkout;
    SCQueuePerformer *_queuePerformer;
    NSArray *_allShippingAddresses;
    _Bool _isFooterActive;
    _Bool _footerLoading;
    _Bool _onboarding;
    _Bool _screenLoading;
    NSError *_error;
    NSString *_inputFirstName;
    NSString *_inputLastName;
    NSString *_inputAddress;
    NSString *_inputSecondaryAddress;
    NSString *_inputCity;
    NSString *_inputState;
    NSString *_inputZipCode;
    id <SCCommerceAccountInfoFetching> _accountInfoFetcher;
    id <SCCommerceAccountInfoMutating> _accountInfoMutator;
    id <SCCommerceShippingSelectDelegate> _delegate;
    id <SCCommerceCheckoutCoordinating> _checkoutCoordinator;
    id <SCCommerceEventLogger> _eventLogger;
}

- (void).cxx_destruct;
- (void)_updateZipCode:(id)arg1;
- (void)_updateState:(id)arg1;
- (void)_updateCity:(id)arg1;
- (void)_updateSecondaryAddress:(id)arg1;
- (void)_updateAddress:(id)arg1;
- (void)_updateLastName:(id)arg1;
- (void)_updateFirstName:(id)arg1;
- (void)_updateCheckoutObject:(id)arg1 error:(id)arg2;
- (void)_saveAddressCompletion:(id)arg1 error:(id)arg2;
- (void)_saveAddress;
- (void)_updateNewAddress:(id)arg1 error:(id)arg2;
- (void)_logButtonTap:(long long)arg1;
- (void)_selectedShippingAddress:(unsigned long long)arg1;
- (void)handleAction:(id)arg1;
- (id)viewModel;
- (void)_updateFooter;
- (_Bool)_inputStringCheck;
- (void)fetchShippingAddresses:(id)arg1;
- (id)initWithCheckout:(id)arg1 delegate:(id)arg2 accountInfoFetcher:(id)arg3 accountInfoMutator:(id)arg4 checkoutCoordinator:(id)arg5 onboarding:(_Bool)arg6 eventLogger:(id)arg7;

@end

