//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCCognacShareToCameraAttachment : NSObject <NSCopying>
{
    NSString *_cognacAppId;
    NSString *_cognacAppShareInfo;
}

@property(readonly, copy, nonatomic) NSString *cognacAppShareInfo; // @synthesize cognacAppShareInfo=_cognacAppShareInfo;
@property(readonly, copy, nonatomic) NSString *cognacAppId; // @synthesize cognacAppId=_cognacAppId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCognacAppId:(id)arg1 cognacAppShareInfo:(id)arg2;

@end

