//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLazy;

@interface SCCognacMessageSendingServices : NSObject
{
    SCLazy *_cognacMessageSender;
}

@property(readonly, nonatomic) SCLazy *cognacMessageSender; // @synthesize cognacMessageSender=_cognacMessageSender;
- (void).cxx_destruct;
- (id)initWithCognacMessageSender:(id)arg1;

@end

