//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCCommerceSession;

@interface SCCommerceOperationalMetrics : NSObject
{
    SCCommerceSession *_commerceSession;
    unsigned long long _context;
}

+ (id)shared;
@property(nonatomic) unsigned long long context; // @synthesize context=_context;
@property(retain, nonatomic) SCCommerceSession *commerceSession; // @synthesize commerceSession=_commerceSession;
- (void).cxx_destruct;
- (long long)restActionForUserAction:(unsigned long long)arg1;
- (long long)commerceEndpointForODPEndpoint:(unsigned long long)arg1;
- (void)logOperationalMetricForUserAction:(unsigned long long)arg1 endpoint:(unsigned long long)arg2 statusCode:(long long)arg3 duration:(double)arg4 payloadSize:(unsigned long long)arg5 error:(id)arg6 jsonMetadata:(id)arg7 userSession:(id)arg8;

@end

