//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCContextV3TappableElementsProviding-Protocol.h"

@class NSString, SCExperimentManager, SCLazy;

@interface SCContextV3TappableElementsProvider : NSObject <SCContextV3TappableElementsProviding>
{
    SCLazy *_embeddedContextCardsProvider;
    SCExperimentManager *_experimentManager;
}

- (void).cxx_destruct;
- (id)createTappableElementsWithContextSession:(id)arg1 excludedCards:(id)arg2;
- (id)initWithEmbeddedContextCardsProvider:(id)arg1 experimentManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

