//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCCTXCTAElement;

@interface SCContextV3CtaElementViewModel : NSObject <NSCopying>
{
    _Bool _isFlexible;
    SCCTXCTAElement *_element;
    long long _elementIndex;
    long long _maxElementIndex;
}

@property(readonly, nonatomic) _Bool isFlexible; // @synthesize isFlexible=_isFlexible;
@property(readonly, nonatomic) long long maxElementIndex; // @synthesize maxElementIndex=_maxElementIndex;
@property(readonly, nonatomic) long long elementIndex; // @synthesize elementIndex=_elementIndex;
@property(readonly, copy, nonatomic) SCCTXCTAElement *element; // @synthesize element=_element;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithElement:(id)arg1 elementIndex:(long long)arg2 maxElementIndex:(long long)arg3 isFlexible:(_Bool)arg4;

@end

