//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCContextV3PostSnapDataServices, SCUserJobProviderScope, SCUserJobSchedulerServices;

@interface SCContextV3PostSnapDataCleanUpJobEntryPoint : SCEntryPoint
{
    SCContextV3PostSnapDataServices *_postSnapDataServices;
    SCUserJobSchedulerServices *_userJobSchedulerService;
    SCUserJobProviderScope *_userJobProviderScope;
}

@property(nonatomic) __weak SCUserJobProviderScope *userJobProviderScope; // @synthesize userJobProviderScope=_userJobProviderScope;
@property(nonatomic) __weak SCUserJobSchedulerServices *userJobSchedulerService; // @synthesize userJobSchedulerService=_userJobSchedulerService;
@property(nonatomic) __weak SCContextV3PostSnapDataServices *postSnapDataServices; // @synthesize postSnapDataServices=_postSnapDataServices;
- (void).cxx_destruct;
- (id)_createCleanupJobProcessor:(id)arg1;
- (void)_setupCleanupJob:(id)arg1;
- (void)begin;

@end

