//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCArroyoChatLoggingServices, SCBitmojiFetchServices, SCChatStatusSendingServices, SCContentDeliveryServices, SCContextV3PostSnapDataServices, SCConversationIdServices, SCCoreMessagingServices, SCEntryPointCleanup, SCForceAppTerminationServices, SCFriendsFeedLoggingServices, SCFriendsFeedUFSServices, SCGrapheneServices, SCGroupServices, SCLegacyLensDataFetcherServices, SCLegacySnapchatterServices, SCNativeConversationServices, SCNativeMessagingServices, SCPinnedConversationsServices, SCReceiveMessageLoggerServices, SCSecurityServices, SCSendMessageLoggerServices, SCServicesExposer, SCShakeToReportServices, SCSnapTokenServices, SCSnapchatterServices, SCSoundServices, SCStoriesServices, SCTextSendingServices, SCUserInfoServices, SCUserSessionScope, SCUserStorageServices;
@protocol SCChatConversationManager;

@interface SCConversationServicesEntryPoint : SCEntryPoint
{
    id <SCChatConversationManager> _conversationManager;
    SCEntryPointCleanup *_cleanup;
    SCSoundServices *_soundServices;
    SCUserSessionScope *_userSessionScope;
    SCUserStorageServices *_userStorageServices;
    SCFriendsFeedUFSServices *_friendsFeedUFSServices;
    SCLegacySnapchatterServices *_legacySnapchatterServices;
    SCSnapchatterServices *_snapchatterServices;
    SCGroupServices *_groupServices;
    SCStoriesServices *_storiesServices;
    SCNativeMessagingServices *_nativeMessagingServices;
    SCNativeConversationServices *_nativeConversationServices;
    SCContentDeliveryServices *_contentDeliveryServices;
    SCSecurityServices *_SCSecurityServices;
    SCPinnedConversationsServices *_pinnedConversationsServices;
    SCBitmojiFetchServices *_bitmojiFetchServices;
    SCReceiveMessageLoggerServices *_receiveMessageLoggerServices;
    SCSendMessageLoggerServices *_sendMessageLoggerServices;
    SCFriendsFeedLoggingServices *_friendsFeedLoggingServices;
    SCArroyoChatLoggingServices *_arroyoChatLoggingServices;
    SCConversationIdServices *_conversationIdServices;
    SCCoreMessagingServices *_coreMessagingServices;
    SCShakeToReportServices *_shakeToReportServices;
    SCSnapTokenServices *_snapTokenServices;
    SCTextSendingServices *_textSendingServices;
    SCChatStatusSendingServices *_chatStatusSendingServices;
    SCContextV3PostSnapDataServices *_contextPostSnapDataServices;
    SCLegacyLensDataFetcherServices *_legacyLensDataFetcherServices;
    SCUserInfoServices *_userInfoServices;
    SCGrapheneServices *_grapheneServices;
    SCForceAppTerminationServices *_forceAppTerminationServices;
    SCServicesExposer *_conversationServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *conversationServicesExposer; // @synthesize conversationServicesExposer=_conversationServicesExposer;
@property(nonatomic) __weak SCForceAppTerminationServices *forceAppTerminationServices; // @synthesize forceAppTerminationServices=_forceAppTerminationServices;
@property(nonatomic) __weak SCGrapheneServices *grapheneServices; // @synthesize grapheneServices=_grapheneServices;
@property(nonatomic) __weak SCUserInfoServices *userInfoServices; // @synthesize userInfoServices=_userInfoServices;
@property(nonatomic) __weak SCLegacyLensDataFetcherServices *legacyLensDataFetcherServices; // @synthesize legacyLensDataFetcherServices=_legacyLensDataFetcherServices;
@property(nonatomic) __weak SCContextV3PostSnapDataServices *contextPostSnapDataServices; // @synthesize contextPostSnapDataServices=_contextPostSnapDataServices;
@property(nonatomic) __weak SCChatStatusSendingServices *chatStatusSendingServices; // @synthesize chatStatusSendingServices=_chatStatusSendingServices;
@property(nonatomic) __weak SCTextSendingServices *textSendingServices; // @synthesize textSendingServices=_textSendingServices;
@property(nonatomic) __weak SCSnapTokenServices *snapTokenServices; // @synthesize snapTokenServices=_snapTokenServices;
@property(nonatomic) __weak SCShakeToReportServices *shakeToReportServices; // @synthesize shakeToReportServices=_shakeToReportServices;
@property(nonatomic) __weak SCCoreMessagingServices *coreMessagingServices; // @synthesize coreMessagingServices=_coreMessagingServices;
@property(nonatomic) __weak SCConversationIdServices *conversationIdServices; // @synthesize conversationIdServices=_conversationIdServices;
@property(nonatomic) __weak SCArroyoChatLoggingServices *arroyoChatLoggingServices; // @synthesize arroyoChatLoggingServices=_arroyoChatLoggingServices;
@property(nonatomic) __weak SCFriendsFeedLoggingServices *friendsFeedLoggingServices; // @synthesize friendsFeedLoggingServices=_friendsFeedLoggingServices;
@property(nonatomic) __weak SCSendMessageLoggerServices *sendMessageLoggerServices; // @synthesize sendMessageLoggerServices=_sendMessageLoggerServices;
@property(nonatomic) __weak SCReceiveMessageLoggerServices *receiveMessageLoggerServices; // @synthesize receiveMessageLoggerServices=_receiveMessageLoggerServices;
@property(nonatomic) __weak SCBitmojiFetchServices *bitmojiFetchServices; // @synthesize bitmojiFetchServices=_bitmojiFetchServices;
@property(nonatomic) __weak SCPinnedConversationsServices *pinnedConversationsServices; // @synthesize pinnedConversationsServices=_pinnedConversationsServices;
@property(nonatomic) __weak SCSecurityServices *SCSecurityServices; // @synthesize SCSecurityServices=_SCSecurityServices;
@property(nonatomic) __weak SCContentDeliveryServices *contentDeliveryServices; // @synthesize contentDeliveryServices=_contentDeliveryServices;
@property(nonatomic) __weak SCNativeConversationServices *nativeConversationServices; // @synthesize nativeConversationServices=_nativeConversationServices;
@property(nonatomic) __weak SCNativeMessagingServices *nativeMessagingServices; // @synthesize nativeMessagingServices=_nativeMessagingServices;
@property(nonatomic) __weak SCStoriesServices *storiesServices; // @synthesize storiesServices=_storiesServices;
@property(nonatomic) __weak SCGroupServices *groupServices; // @synthesize groupServices=_groupServices;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;
@property(nonatomic) __weak SCLegacySnapchatterServices *legacySnapchatterServices; // @synthesize legacySnapchatterServices=_legacySnapchatterServices;
@property(nonatomic) __weak SCFriendsFeedUFSServices *friendsFeedUFSServices; // @synthesize friendsFeedUFSServices=_friendsFeedUFSServices;
@property(nonatomic) __weak SCUserStorageServices *userStorageServices; // @synthesize userStorageServices=_userStorageServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCSoundServices *soundServices; // @synthesize soundServices=_soundServices;
- (void).cxx_destruct;
- (id)_clearConversationActionHandler;
- (id)_chatConversationManager;
- (id)end;
- (void)begin;

@end

