//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCContextV3ExcludedCards-Protocol.h"

@class NSSet, NSString;

@interface SCContextV3TappableElementsExperimentContextExcludedCards : NSObject <SCContextV3ExcludedCards>
{
    NSSet *_cardTypes;
}

- (void).cxx_destruct;
- (id)toEnumArray;
- (_Bool)isCardTypeExcluded:(int)arg1;
- (id)initWithCardTypes:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

