//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class SCLazy, SCObservable, UIViewController;
@protocol SCContextV3Cta, SCPageNameLogging;

@protocol SCContextV3CtaProviding
- (id <SCContextV3Cta>)createContextV3CtaWithCtaParamsObserverable:(SCObservable *)arg1 operaNavigationStyle:(long long)arg2 actionHandler:(SCLazy *)arg3 baseViewController:(UIViewController<SCPageNameLogging> *)arg4;
@end

