//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCCommerceAddPaymentAction : NSObject <NSCopying>
{
    unsigned long long _subtype;
    unsigned long long _billingAddressSelect_index;
    NSString *_editCardNumber_cardNumber;
    NSString *_editExpiration_expiration;
    NSString *_editCVC_cvc;
    NSString *_editFirstName_firstName;
    NSString *_editLastName_lastName;
    NSString *_editAddress_address;
    NSString *_editSecondaryAddress_secondaryAddress;
    NSString *_editCity_city;
    NSString *_editState_state;
    NSString *_editZipCode_zipCode;
}

+ (id)savePaymentMethodHeader;
+ (id)savePaymentMethodFooter;
+ (id)editZipCodeWithZipCode:(id)arg1;
+ (id)editStateWithState:(id)arg1;
+ (id)editSecondaryAddressWithSecondaryAddress:(id)arg1;
+ (id)editLastNameWithLastName:(id)arg1;
+ (id)editFirstNameWithFirstName:(id)arg1;
+ (id)editExpirationWithExpiration:(id)arg1;
+ (id)editCityWithCity:(id)arg1;
+ (id)editCardNumberWithCardNumber:(id)arg1;
+ (id)editCVCWithCvc:(id)arg1;
+ (id)editAddressWithAddress:(id)arg1;
+ (id)billingAddressSelectWithIndex:(unsigned long long)arg1;
+ (id)back;
- (void).cxx_destruct;
- (void)matchBack:(CDUnknownBlockType)arg1 billingAddressSelect:(CDUnknownBlockType)arg2 editCardNumber:(CDUnknownBlockType)arg3 editExpiration:(CDUnknownBlockType)arg4 editCVC:(CDUnknownBlockType)arg5 editFirstName:(CDUnknownBlockType)arg6 editLastName:(CDUnknownBlockType)arg7 editAddress:(CDUnknownBlockType)arg8 editSecondaryAddress:(CDUnknownBlockType)arg9 editCity:(CDUnknownBlockType)arg10 editState:(CDUnknownBlockType)arg11 editZipCode:(CDUnknownBlockType)arg12 savePaymentMethodHeader:(CDUnknownBlockType)arg13 savePaymentMethodFooter:(CDUnknownBlockType)arg14;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

