//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCCTPCTConfig, SCCTPCTItem_Entity, SCCTPCompositeId;

@interface SCCTPCTItem : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCCTPCTConfig *config; // @dynamic config;
@property(retain, nonatomic) SCCTPCTItem_Entity *entity; // @dynamic entity;
@property(nonatomic) _Bool hasConfig; // @dynamic hasConfig;
@property(nonatomic) _Bool hasEntity; // @dynamic hasEntity;
@property(nonatomic) _Bool hasId_p; // @dynamic hasId_p;
@property(retain, nonatomic) SCCTPCompositeId *id_p; // @dynamic id_p;

@end

