//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCCustomStoryActionMenuRouter-Protocol.h"
#import "SCCustomStoryMembersDelegate-Protocol.h"
#import "SCUnifiedActionMenuPresenterDelegate-Protocol.h"
#import "SIGDialogDelegate-Protocol.h"

@class NSString, SCLazy, SCScopeExposer, SCUnifiedActionMenuPresenter, SIGAlertDialog, UIViewController;
@protocol SCCustomStoryActionMenuActionHandlerDelegate, SCCustomStoryDeleteAlertDelegate, SCCustomStoryLeaveAlertDelegate, SCCustomStoryRenameAlertDelegate, SCCustomStorySeeMembersDelegate, SCUIContainer;

@interface SCCustomStoryActionMenuRouterImpl : NSObject <SCUnifiedActionMenuPresenterDelegate, SIGDialogDelegate, SCCustomStoryMembersDelegate, SCCustomStoryActionMenuRouter>
{
    id <SCUIContainer> _uiContainer;
    UIViewController *_presentingViewController;
    SCScopeExposer *_membersScopeExposer;
    NSString *_publicationId;
    long long _options;
    SCLazy *_customStoriesDataFetcher;
    SCLazy *_customStoriesDataSyncer;
    long long _sourcePageType;
    NSString *_currentUserId;
    SCUnifiedActionMenuPresenter *_actionMenuPresenter;
    id <SCCustomStoryActionMenuActionHandlerDelegate> _actionMenuActionHandlerDelegate;
    _Bool _didExplicitlyEndActionMenu;
    SIGAlertDialog *_deleteAlert;
    id <SCCustomStoryDeleteAlertDelegate> _deleteAlertDelegate;
    SIGAlertDialog *_leaveAlert;
    id <SCCustomStoryLeaveAlertDelegate> _leaveAlertDelegate;
    SIGAlertDialog *_renameAlert;
    id <SCCustomStoryRenameAlertDelegate> _renameAlertDelegate;
    id <SCCustomStorySeeMembersDelegate> _seeMembersDelegate;
}

- (void).cxx_destruct;
- (void)dialogDidDismiss:(id)arg1;
- (void)didDismissCustomStoryMembers;
- (void)presentMembersListForCustomStory:(id)arg1 delegate:(id)arg2;
- (void)presentRenameCustomStory:(id)arg1 delegate:(id)arg2;
- (void)confirmLeaveCustomStory:(id)arg1 delegate:(id)arg2;
- (void)confirmDeleteCustomStory:(id)arg1 delegate:(id)arg2;
- (void)unifiedActionMenuPresenterDidDismiss:(id)arg1;
- (void)dismissCustomStoryActionMenuWithCompletion:(CDUnknownBlockType)arg1;
- (void)presentCustomStoryActionMenuWithDelegate:(id)arg1;
- (id)initWithUiContainer:(id)arg1 presentingViewController:(id)arg2 membersScopeExposer:(id)arg3 publicationId:(id)arg4 options:(long long)arg5 customStoriesDataFetcher:(id)arg6 customStoriesDataSyncer:(id)arg7 sourcePageType:(long long)arg8 currentUserId:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

