//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCDeltaforceProperty;

@interface SCDeltaforcePropertyCondition : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCDeltaforceProperty *eq; // @dynamic eq;
@property(retain, nonatomic) SCDeltaforceProperty *greaterThan; // @dynamic greaterThan;
@property(retain, nonatomic) SCDeltaforceProperty *greaterThanOrEq; // @dynamic greaterThanOrEq;
@property(retain, nonatomic) SCDeltaforceProperty *lessThan; // @dynamic lessThan;
@property(retain, nonatomic) SCDeltaforceProperty *lessThanOrEq; // @dynamic lessThanOrEq;
@property(retain, nonatomic) SCDeltaforceProperty *notEq; // @dynamic notEq;
@property(retain, nonatomic) SCDeltaforceProperty *notSet; // @dynamic notSet;
@property(readonly, nonatomic) int propConditionTypeOneOfCase; // @dynamic propConditionTypeOneOfCase;

@end

