//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface SCDiscoverPublisherStoryPlayableDataModelBuilder : NSObject
{
    NSString *_identifier;
    NSArray *_snapPlayableDataModels;
}

+ (id)discoverPublisherStoryPlayableDataModelFromExistingDiscoverPublisherStoryPlayableDataModel:(id)arg1;
+ (id)discoverPublisherStoryPlayableDataModel;
- (void).cxx_destruct;
- (id)withSnapPlayableDataModels:(id)arg1;
- (id)withIdentifier:(id)arg1;
- (id)build;

@end

