//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCDiscoverFeedStoryIHEventFloat;

@interface SCDiscoverFeedStoryIHImpressionInfo : NSObject <NSCopying>
{
    unsigned int _longImpressionCount;
    unsigned int _qualifiedLongImpressionCount;
    unsigned int _totalImpressionTimeOnLatestVersion;
    unsigned int _totalQualifiedImpressionTimeOnLatestVersion;
    SCDiscoverFeedStoryIHEventFloat *_shortImpressionScore;
    SCDiscoverFeedStoryIHEventFloat *_longImpressionScore;
    SCDiscoverFeedStoryIHEventFloat *_qualifiedLongImpressionScore;
    NSString *_longImpressionThumbnailId;
    SCDiscoverFeedStoryIHEventFloat *_decayedTotalImpressionTime;
    SCDiscoverFeedStoryIHEventFloat *_decayedTotalQualifiedImpressionTime;
}

@property(readonly, copy, nonatomic) SCDiscoverFeedStoryIHEventFloat *decayedTotalQualifiedImpressionTime; // @synthesize decayedTotalQualifiedImpressionTime=_decayedTotalQualifiedImpressionTime;
@property(readonly, copy, nonatomic) SCDiscoverFeedStoryIHEventFloat *decayedTotalImpressionTime; // @synthesize decayedTotalImpressionTime=_decayedTotalImpressionTime;
@property(readonly, copy, nonatomic) NSString *longImpressionThumbnailId; // @synthesize longImpressionThumbnailId=_longImpressionThumbnailId;
@property(readonly, nonatomic) unsigned int totalQualifiedImpressionTimeOnLatestVersion; // @synthesize totalQualifiedImpressionTimeOnLatestVersion=_totalQualifiedImpressionTimeOnLatestVersion;
@property(readonly, nonatomic) unsigned int totalImpressionTimeOnLatestVersion; // @synthesize totalImpressionTimeOnLatestVersion=_totalImpressionTimeOnLatestVersion;
@property(readonly, nonatomic) unsigned int qualifiedLongImpressionCount; // @synthesize qualifiedLongImpressionCount=_qualifiedLongImpressionCount;
@property(readonly, nonatomic) unsigned int longImpressionCount; // @synthesize longImpressionCount=_longImpressionCount;
@property(readonly, copy, nonatomic) SCDiscoverFeedStoryIHEventFloat *qualifiedLongImpressionScore; // @synthesize qualifiedLongImpressionScore=_qualifiedLongImpressionScore;
@property(readonly, copy, nonatomic) SCDiscoverFeedStoryIHEventFloat *longImpressionScore; // @synthesize longImpressionScore=_longImpressionScore;
@property(readonly, copy, nonatomic) SCDiscoverFeedStoryIHEventFloat *shortImpressionScore; // @synthesize shortImpressionScore=_shortImpressionScore;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithShortImpressionScore:(id)arg1 longImpressionScore:(id)arg2 qualifiedLongImpressionScore:(id)arg3 longImpressionCount:(unsigned int)arg4 qualifiedLongImpressionCount:(unsigned int)arg5 totalImpressionTimeOnLatestVersion:(unsigned int)arg6 totalQualifiedImpressionTimeOnLatestVersion:(unsigned int)arg7 longImpressionThumbnailId:(id)arg8 decayedTotalImpressionTime:(id)arg9 decayedTotalQualifiedImpressionTime:(id)arg10;

@end

