//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCServicesExposer, SCSnapTokenServices, SCUserSessionScope, SCUserStorageServices;

@interface SCDiscoverFeedDataLegacyEntryPoint : SCEntryPoint
{
    SCUserSessionScope *_userSessionScope;
    SCSnapTokenServices *_snapTokenServices;
    SCUserStorageServices *_scUserStorageServices;
    SCServicesExposer *_discoverFeedDataServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *discoverFeedDataServicesExposer; // @synthesize discoverFeedDataServicesExposer=_discoverFeedDataServicesExposer;
@property(nonatomic) __weak SCUserStorageServices *scUserStorageServices; // @synthesize scUserStorageServices=_scUserStorageServices;
@property(nonatomic) __weak SCSnapTokenServices *snapTokenServices; // @synthesize snapTokenServices=_snapTokenServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
- (void).cxx_destruct;
- (id)_createDiscoverFeedEventsController:(id)arg1 lazyDiscoverFeedTapHistoryManager:(id)arg2 lazyDiscoverFeedInteractionHistoryManager:(id)arg3 lazyDiscoverFeedRanker:(id)arg4;
- (id)_creatDiscoverFeedInteractionHistoryManager;
- (id)_creatDiscoverFeedTapHistoryManager;
- (id)_createDiscoverFeedRanker;
- (id)_createDiscoverFeedSectionsCoordinator;
- (id)_createDiscoverFeedDataStoreWithlazyDiscoverFeedRanker:(id)arg1 lazyDiscoverFeedInteractionHistoryManager:(id)arg2;
- (void)begin;

@end

