//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class NSOperationQueue, NSString, SCBehaviorSubject, SCDefaultDynamicLocaleProvider, SCDefaultLocaleBundleProvider, SCDynamicLocaleFileRefresher, SCDynamicLocaleLogger, SCGrapheneServices, SCServicesExposer, SCSystemContentDeliveryServices;

@interface SCDynamicLocaleProviderServicesEntryPoint : SCEntryPoint
{
    NSOperationQueue *_logQueue;
    NSString *_locale;
    SCDynamicLocaleLogger *_dynamicLocaleLogger;
    SCDefaultDynamicLocaleProvider *_localeProvider;
    SCDefaultLocaleBundleProvider *_bundleProvider;
    SCDynamicLocaleFileRefresher *_localeRefresher;
    SCBehaviorSubject *_dynamicLocaleEvents;
    SCSystemContentDeliveryServices *_contentDeliveryServices;
    SCGrapheneServices *_grapheneServices;
    SCServicesExposer *_localeProviderServicesExposer;
    SCServicesExposer *_dynamicLocaleEventServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *dynamicLocaleEventServicesExposer; // @synthesize dynamicLocaleEventServicesExposer=_dynamicLocaleEventServicesExposer;
@property(retain, nonatomic) SCServicesExposer *localeProviderServicesExposer; // @synthesize localeProviderServicesExposer=_localeProviderServicesExposer;
@property(nonatomic) __weak SCGrapheneServices *grapheneServices; // @synthesize grapheneServices=_grapheneServices;
@property(nonatomic) __weak SCSystemContentDeliveryServices *contentDeliveryServices; // @synthesize contentDeliveryServices=_contentDeliveryServices;
- (void).cxx_destruct;
- (id)_currentLocaleURL:(id)arg1;
- (id)_createLocaleFileRefresher;
- (id)_createLogger;
- (id)end;
- (void)begin;

@end

