//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, SCDiscoverFeedStory, SCDiscoverFeedStoryBuildingInfo, SCExperimentManager, SCSSMStoryCard;

@protocol SCDynamicLayoutUIBuilding <NSObject>
- (SCDiscoverFeedStory *)discoverFeedStoryFromSCSSMStoryCard:(SCSSMStoryCard *)arg1 storyBuildingInfo:(SCDiscoverFeedStoryBuildingInfo *)arg2 experimentManager:(SCExperimentManager *)arg3;
- (void)handleNoFillPromotedStoryCards:(NSArray *)arg1 querySource:(NSString *)arg2 experimentManager:(SCExperimentManager *)arg3;
- (NSArray *)discoverFeedStoriesFromSCSSMStoryCards:(NSArray *)arg1 storyBuildingInfo:(SCDiscoverFeedStoryBuildingInfo *)arg2 experimentManager:(SCExperimentManager *)arg3;
- (CDUnknownFunctionPointerType)storyViewModelBuilderFunc;
@end

