//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCEagleActionMenuViewDelegate-Protocol.h"
#import "SCLegacySendToWorkflowDelegate-Protocol.h"
#import "SCSendToDelegate-Protocol.h"
#import "SCSendToNavigationDelegate-Protocol.h"
#import "SCShakeToReportDelegate-Protocol.h"

@class NSString, SCEagleActionMenuView, SCEagleProduct, SCEagleSearchResult, SCEventListenerAnnouncer, SCLegacySendToUIContainer, SCSendToTransitionProvider, SCUserFeatureLauncher, SCUserSession;
@protocol SCSendToScreen;

@interface SCEagleActionMenuViewController : UIViewController <SCEagleActionMenuViewDelegate, SCSendToDelegate, SCSendToNavigationDelegate, SCShakeToReportDelegate, SCLegacySendToWorkflowDelegate>
{
    SCEagleActionMenuView *_actionMenuView;
    SCEagleProduct *_eagleProduct;
    SCEagleSearchResult *_eagleResult;
    SCUserSession *_userSession;
    SCSendToTransitionProvider *_sendToTransitionProvider;
    UIViewController<SCSendToScreen> *_sendViewController;
    SCEventListenerAnnouncer *_eventAnnouncer;
    SCUserFeatureLauncher *_legacySendToLauncher;
    SCLegacySendToUIContainer *_uiContainer;
}

+ (id)announcerIdentifier;
- (void).cxx_destruct;
- (void)_dismiss;
- (id)defaultSubProjectName;
- (id)defaultProjectNameV2;
- (id)jiraMetaInfo;
- (void)legacySendToScopeWillSend:(id)arg1 sendToSelection:(id)arg2;
- (void)legacySendToScopeDidDismiss:(id)arg1 selectedItems:(id)arg2;
- (void)_sendMessageToRecipients:(id)arg1 groups:(id)arg2 additionalText:(id)arg3;
- (void)dismissSendViewController:(id)arg1;
- (void)sendViewController:(id)arg1 sendToRecipients:(id)arg2 storiesPostingConfig:(id)arg3 businessIds:(id)arg4 groups:(id)arg5 appStories:(id)arg6 additionalText:(id)arg7;
- (void)eagleActionMenuViewHandleDismiss:(id)arg1;
- (void)eagleActionMenuViewHandleSend:(id)arg1;
- (void)eagleActionMenuViewHandleCopy:(id)arg1;
- (void)_dismissWithAnimation;
- (void)_didTap:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 eagleProduct:(id)arg2 eagleResult:(id)arg3;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

