//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEncryptedContentManagerDataProviding-Protocol.h"

@class NSData, NSObject, NSString, SCCloudFSFile, SCKeyServiceEncryption;
@protocol OS_dispatch_queue, SCCanceling, SCGallerySnap;

@protocol SCEncryptedContentManaging <SCEncryptedContentManagerDataProviding>
- (void)requestOverlayFormatForSnap:(id <SCGallerySnap>)arg1 encryptedOverlayBlob:(NSData *)arg2 queue:(NSObject<OS_dispatch_queue> *)arg3 resultHandler:(void (^)(SCOverlayFormat *, NSError *))arg4;
- (void)requestKeyIVForSnap:(id <SCGallerySnap>)arg1 queue:(NSObject<OS_dispatch_queue> *)arg2 resultHandler:(void (^)(NSData *, NSData *))arg3;
- (void)requestDecryptedDataForSnapId:(NSString *)arg1 cloudFile:(SCCloudFSFile *)arg2 synchronous:(_Bool)arg3 queue:(NSObject<OS_dispatch_queue> *)arg4 resultHandler:(void (^)(NSData *, NSError *))arg5;
- (id <SCCanceling>)requestBlurredMiniThumbnailForSnap:(id <SCGallerySnap>)arg1 orientation:(_Bool)arg2 resultHandler:(void (^)(UIImage *, NSError *, _Bool))arg3;
- (void)requestOverlayFormatForSnap:(id <SCGallerySnap>)arg1 cloudFile:(SCCloudFSFile *)arg2 synchronous:(_Bool)arg3 queue:(NSObject<OS_dispatch_queue> *)arg4 resultHandler:(void (^)(SCOverlayFormat *, NSError *))arg5;
- (void)requestImageForSnap:(id <SCGallerySnap>)arg1 cloudFile:(SCCloudFSFile *)arg2 synchronous:(_Bool)arg3 queue:(NSObject<OS_dispatch_queue> *)arg4 resultHandler:(void (^)(UIImage *, NSError *))arg5;
- (NSData *)secureEncryptData:(NSData *)arg1 key:(NSData *)arg2 IV:(NSData *)arg3 masterKey:(SCKeyServiceEncryption *)arg4;
@end

