//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLazy;

@interface SCExternalMediaPreparingServices : NSObject
{
    SCLazy *_externalMediaPreparer;
}

@property(readonly, nonatomic) SCLazy *externalMediaPreparer; // @synthesize externalMediaPreparer=_externalMediaPreparer;
- (void).cxx_destruct;
- (id)initWithExternalMediaPreparer:(id)arg1;

@end

