//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCExtensionsUserDataWorkflow, SCFriendmojiServices, SCSnapchatterServices, SCSystemScope, SCUserSessionScope;

@interface SCExtensionsUserDataEntryPoint : SCEntryPoint
{
    SCExtensionsUserDataWorkflow *_workflow;
    SCFriendmojiServices *_friendmojiServices;
    SCSnapchatterServices *_snapchatterServices;
    SCSystemScope *_systemScope;
    SCUserSessionScope *_userSessionScope;
}

@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;
@property(nonatomic) __weak SCFriendmojiServices *friendmojiServices; // @synthesize friendmojiServices=_friendmojiServices;
- (void).cxx_destruct;
- (id)end;
- (void)begin;

@end

