//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SOJUIdentityIdentityCheckResponse, SOJUUpdatesResponse;

@protocol SCFriendingConfigsDiscrepancyLogger <NSObject>
- (void)contactBookSyncVersionFromFeatureSetting:(long long)arg1;
- (void)addedFriendsTimestampFromFeatureSetting:(long long)arg1;
- (void)shouldShowQuickAddUnitFromFeatureSetting:(_Bool)arg1;
- (void)isContactSyncEnabledFromFeatureSetting:(_Bool)arg1;
- (void)searchableByPhoneNumberFromFeatureSetting:(_Bool)arg1;
- (void)compareUpdatesResponse:(SOJUUpdatesResponse *)arg1 withContactBookSyncVersion:(long long)arg2 featureSettingAvailable:(_Bool)arg3;
- (void)compareUpdatesResponse:(SOJUUpdatesResponse *)arg1 withAddedFriendsTimestamp:(long long)arg2 featureSettingAvailable:(_Bool)arg3;
- (void)compareIdentityCheckResponse:(SOJUIdentityIdentityCheckResponse *)arg1 withIsContactSyncEnabledInFeatureSetting:(_Bool)arg2 featureSettingAvailable:(_Bool)arg3;
- (void)compareIdentityCheckResponse:(SOJUIdentityIdentityCheckResponse *)arg1 withShouldShowQuickAddUnit:(_Bool)arg2 featureSettingAvailable:(_Bool)arg3;
- (void)compareUpdatesResponse:(SOJUUpdatesResponse *)arg1 withSearchableByPhoneNumberInFeatureSetting:(_Bool)arg2 featureSettingAvailable:(_Bool)arg3;
@end

