//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCStoryExporter.h"

#import "SCActivityItemCompositing-Protocol.h"

@class NSString;
@protocol SCActivityItemCompositingDelegate, SCActivityItemProviding;

@interface SCGalleryStoryExporter : SCStoryExporter <SCActivityItemCompositing>
{
    id <SCActivityItemCompositingDelegate> _compositingDelegate;
    id <SCActivityItemProviding> _activityItemProvider;
}

@property(retain, nonatomic) id <SCActivityItemProviding> activityItemProvider; // @synthesize activityItemProvider=_activityItemProvider;
@property(nonatomic) __weak id <SCActivityItemCompositingDelegate> compositingDelegate; // @synthesize compositingDelegate=_compositingDelegate;
- (void).cxx_destruct;
- (void)_cacheUrl:(id)arg1;
- (void)_transformItemsToUrls:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)didFinishExportingToURL:(id)arg1 withError:(id)arg2;
- (void)didProceedToProgress:(double)arg1;
- (void)createCompositeFromItems:(id)arg1;
- (id)initWithProviders:(id)arg1 spectaclesExportFormat:(long long)arg2;
- (id)initWithGallerySnaps:(id)arg1 cloudFiles:(id)arg2 mediaScenePath:(CDStruct_bac8f6e9)arg3 userSession:(id)arg4 spectaclesExportFormat:(long long)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

