//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCGalleryMomentClustererViewController.h"

#import "SCGallerySelectionControllerDataSource-Protocol.h"
#import "SCGallerySelectionControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, SCGallerySelectionController;
@protocol SCGallerySearchResultsViewControllerDelegate, SCStartChatDelegate;

@interface SCGallerySearchResultsViewController : SCGalleryMomentClustererViewController <UIGestureRecognizerDelegate, SCGallerySelectionControllerDataSource, SCGallerySelectionControllerDelegate>
{
    SCGallerySelectionController *_selectionController;
    id <SCStartChatDelegate> _startChatDelegate;
    id <SCGallerySearchResultsViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SCGallerySearchResultsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)memoriesCollectionViewSelectionHelperRequestSelectMode:(id)arg1;
- (_Bool)memoriesCollectionViewSelectionHelper:(id)arg1 overrideTapHandlingAtIndexPath:(id)arg2;
- (id)_snapForIndexPath:(id)arg1;
- (id)_entryForIndexPath:(id)arg1;
- (void)memoriesCollectionViewSelectionHelper:(id)arg1 didChangeSelected:(_Bool)arg2 forItems:(id)arg3 snapItems:(id)arg4;
- (void)memoriesCollectionViewSelectionHelper:(id)arg1 didChangeSelected:(_Bool)arg2 forSnapItem:(id)arg3;
- (void)memoriesCollectionViewSelectionHelper:(id)arg1 didChangeSelected:(_Bool)arg2 forItem:(id)arg3;
- (void)_didChangeSelectedItem:(_Bool)arg1;
- (_Bool)memoriesCollectionViewSelectionHelper:(id)arg1 shouldChangeSelectedAtIndexPath:(id)arg2;
- (void)selectionController:(id)arg1 shouldScrollToGalleryEntry:(id)arg2;
- (void)selectionControllerDidExitSelectionMode:(id)arg1;
- (void)selectionControllerDidEnterSelectionMode:(id)arg1;
- (id)selectedGallerySnaps;
- (id)selectedSnapItems;
- (id)selectedGalleryItems;
- (void)didSelectDismissalActionWithHeaderItem:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)_pan;
- (void)_enterSelectMode:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)pageViewName;
- (id)initWithWithUserSession:(id)arg1 startChatDelegate:(id)arg2 searchResult:(id)arg3 dataObjectContext:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

