//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCMemoriesStreamingManaging-Protocol.h"
#import "SCStreamingDelegate-Protocol.h"

@class NSMutableDictionary, NSNotificationCenter, NSString, SCQueuePerformer, SCScopedAccess, SCStreamingResourceLoader, SCUserSession;
@protocol SCGalleryStreamingSnapPackageFetching, SCStreamingMediaFetching, SCStreamingURLProviding, SCStreamingURLProviding><AVAssetResourceLoaderDelegate;

@interface SCGalleryStreamingManager : NSObject <SCStreamingDelegate, SCMemoriesStreamingManaging>
{
    SCUserSession *_userSession;
    SCQueuePerformer *_performer;
    id <SCStreamingURLProviding> _streamingURLProvider;
    id <SCStreamingURLProviding><AVAssetResourceLoaderDelegate> _streamingAVAssetProvider;
    id <SCStreamingMediaFetching> _streamingMediaFetcher;
    SCScopedAccess *_contentDelivery;
    SCStreamingResourceLoader *_streamingResourceLoader;
    NSMutableDictionary *_loadedVideoAssets;
    _Bool _shouldUseContentManager;
    _Bool _mediaServicesLost;
    NSNotificationCenter *_notificationCenter;
    NSMutableDictionary *_snapIdToSnapMap;
    NSMutableDictionary *_snapIdToStreamingPackageMap;
    id <SCGalleryStreamingSnapPackageFetching> _streamingPackageFetcher;
}

@property(readonly, nonatomic) id <SCGalleryStreamingSnapPackageFetching> streamingPackageFetcher; // @synthesize streamingPackageFetcher=_streamingPackageFetcher;
- (void).cxx_destruct;
- (void)_didDownloadFullMediaForSnapId:(id)arg1 contentResult:(id)arg2 encryptionInfo:(id)arg3;
- (void)_moveToCloudFSForSnapId:(id)arg1 resourceData:(id)arg2;
- (void)_loadAVAssetFromContentResult:(id)arg1 encryptionInfo:(id)arg2 snapId:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_retrieveContentForContentKey:(id)arg1 encryptionInfo:(id)arg2 pageInfo:(id)arg3 snapId:(id)arg4 contentStatus:(long long)arg5 completion:(CDUnknownBlockType)arg6;
- (void)didFullyCacheResourceData:(id)arg1 forStreamingRequestInfo:(id)arg2 request:(id)arg3;
- (id)transformResponseHeaders:(id)arg1 forStreamingRequestInfo:(id)arg2;
- (_Bool)shouldTransformResponseHeadersForStreamingRequestInfo:(id)arg1;
- (_Bool)_moveToCloudFSForSnap:(id)arg1 encryptedMediaBlob:(id)arg2 encryptedOverlayBlob:(id)arg3;
- (void)_prefetchMediaForStreamingPackge:(id)arg1 byteRangeValue:(id)arg2 encryptionInfo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_prefetchStreamingMediaForSnap:(id)arg1 streamingPackge:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_streamingVideoAssetWithStreamingPackge:(id)arg1 encryptionInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)didReceiveMediaServicesWereResetNotification;
- (void)didReceiveMediaServicesWereLostNotification;
- (void)dealloc;
- (void)removePendingStreamingSnap:(id)arg1;
- (void)addPendingStreamingSnap:(id)arg1 streamingPackge:(id)arg2;
- (void)preloadStreamingForSnap:(id)arg1 mediaScenePath:(CDStruct_bac8f6e9)arg2 completionQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)preloadStreamingForEntry:(id)arg1 mediaScenePath:(CDStruct_bac8f6e9)arg2 completionQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)contentManagerProxiedStreamingAVAssetForStreamingPackage:(id)arg1 encryptionInfo:(id)arg2 completionQueue:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)proxiedStreamingURLForStreamingPackge:(id)arg1 encryptionInfo:(id)arg2;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

