//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCGalleryActivityItemProviderFactory : NSObject
{
}

+ (id)combinedActivityItemProviderForProviders:(id)arg1;
+ (id)activityItemProviderPreviewImage:(id)arg1 userSession:(id)arg2 previewConfiguration:(id)arg3 commonLoggingParams:(id)arg4 exportFormat:(long long)arg5 uploadToYouTube:(_Bool)arg6;
+ (id)activityItemProviderPreviewVideoFilter:(id)arg1 userSession:(id)arg2 previewConfiguration:(id)arg3 commonLoggingParams:(id)arg4 exportFormat:(long long)arg5 uploadToYouTube:(_Bool)arg6;
+ (id)activityItemProvidersForSpectaclesItems:(id)arg1 gallerySnaps:(id)arg2 userContext:(id)arg3 userSession:(id)arg4 magicMomentCache:(id)arg5 exportFormat:(long long)arg6 shouldMergeIntoSingleSnap:(_Bool)arg7 uploadToYouTube:(_Bool)arg8;
+ (id)activityItemProvidersForItems:(id)arg1 gallerySnaps:(id)arg2 userContext:(id)arg3 userSession:(id)arg4;
+ (id)activityItemProviderForAsset:(id)arg1 userContext:(id)arg2 userSession:(id)arg3;
+ (id)_activityItemProvidersForSnaps:(id)arg1 userContext:(id)arg2 userSession:(id)arg3;
+ (id)_mixedActivityItemProvidersForSnaps:(id)arg1 userContext:(id)arg2 userSession:(id)arg3;
+ (id)activityItemProviderForSnap:(id)arg1 userContext:(id)arg2 userSession:(id)arg3;
+ (id)activityItemProviderForStorySnaps:(id)arg1 isMultisnap:(_Bool)arg2 userContext:(id)arg3 userSession:(id)arg4;

@end

