//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCGtqNetworkRequest;
@protocol SCPerforming;

@protocol SCGtqNetworkRequestManaging <NSObject>
- (void)submitServeNetworkRequest:(SCGtqNetworkRequest *)arg1 completionPerformer:(id <SCPerforming>)arg2 success:(void (^)(id, NSDictionary *))arg3 failure:(void (^)(NSError *, long long, NSDictionary *))arg4;
@end

