//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCIdentityExperimentContexts : NSObject
{
}

+ (id)getShowHidePasswordContext:(id)arg1;
+ (id)getBackgroundPermissionReportExperimentContext:(id)arg1;
+ (id)getFriendingProgressBarExperimentContext:(id)arg1;
+ (id)getStreaksExperimentContext:(id)arg1;
+ (id)getProfileCardRefreshExperimentContext:(id)arg1;
+ (id)getSendToShareSnapAppearanceExperimentContext:(id)arg1;
+ (id)getSendToShareSnapNewUserExperimentContext:(id)arg1;
+ (id)getSendToShareSnapExperimentContext:(id)arg1;
+ (id)getSkipCaptchaExperimentContext:(id)arg1;
+ (id)getSendToV11ExperimentContext:(id)arg1;
+ (id)getSendToListsV2ExperimentContext:(id)arg1;
+ (id)getSendToListsExperimentContext:(id)arg1;
+ (id)getSendToGroupInviteLinkCountryTestExperimentContext:(id)arg1;
+ (id)getSendToGroupInviteLinkGroupProfileExperimentContext:(id)arg1;
+ (id)getSendToGroupInviteLinkExperimentContext:(id)arg1;
+ (id)getSendToGroupsSectionEmptyStateExperimentContext:(id)arg1;
+ (id)getSendToRecentsRankingExperimentContext:(id)arg1;

@end

