//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCImageProcessPipelineInput-Protocol.h"

@class NSData, NSString, SCImageProcessContext;
@protocol SCImageProcessGLWrapper;

@interface SCImageProcessRGBImageDataInput : NSObject <SCImageProcessPipelineInput>
{
    SCImageProcessContext *_context;
    id <SCImageProcessGLWrapper> _glWrapper;
    NSData *_imageData;
    CDStruct_5e758c1a _pixelSize;
    NSString *_cachedTextureId;
}

- (void).cxx_destruct;
- (void)cleanupTextures;
- (_Bool)setupInputTextureWithError:(id *)arg1;
- (long long)colorSpace;
- (unsigned long long)bytesPerRow;
- (CDStruct_5e758c1a)pixelSize;
- (id)initWithContext:(id)arg1 glWrapper:(id)arg2 imageData:(id)arg3 pixelSize:(CDStruct_5e758c1a)arg4 cachedTextureId:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

