//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

#import "SCInAppRatingSubWorkflowDelegate-Protocol.h"

@class SCFeatureSettingsServices, SCInAppRatingTrigger, SCScopeExposer, SCSnapServices, SCSystemScope, SCUserFeatureConfigurationServices, SCUserSegmentServices, SCUserSessionScope, SCUserStorageServices;

@interface SCInAppRatingTriggerEntryPoint : SCEntryPoint <SCInAppRatingSubWorkflowDelegate>
{
    SCInAppRatingTrigger *_inAppRatingTrigger;
    SCUserSessionScope *_userSessionScope;
    SCUserFeatureConfigurationServices *_userFeatureConfigurationServices;
    SCSnapServices *_snapServices;
    SCUserStorageServices *_userStorageServices;
    SCSystemScope *_systemScope;
    SCUserSegmentServices *_userSegmentServices;
    SCFeatureSettingsServices *_featureSettingsServices;
    SCScopeExposer *_inAppRatingScopeExposer;
}

@property(retain, nonatomic) SCScopeExposer *inAppRatingScopeExposer; // @synthesize inAppRatingScopeExposer=_inAppRatingScopeExposer;
@property(nonatomic) __weak SCFeatureSettingsServices *featureSettingsServices; // @synthesize featureSettingsServices=_featureSettingsServices;
@property(nonatomic) __weak SCUserSegmentServices *userSegmentServices; // @synthesize userSegmentServices=_userSegmentServices;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
@property(nonatomic) __weak SCUserStorageServices *userStorageServices; // @synthesize userStorageServices=_userStorageServices;
@property(nonatomic) __weak SCSnapServices *snapServices; // @synthesize snapServices=_snapServices;
@property(nonatomic) __weak SCUserFeatureConfigurationServices *userFeatureConfigurationServices; // @synthesize userFeatureConfigurationServices=_userFeatureConfigurationServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
- (void).cxx_destruct;
- (void)endInAppRatingWorkflow;
- (void)beginInAppRatingWorkflowWithDelegate:(id)arg1;
- (void)begin;

@end

