//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCAppNotification;

@interface SCLegacyMapCommand : NSObject
{
    unsigned long long _subtype;
    NSString *_displayChatForUser_username;
    NSString *_displayChatForUser_userId;
    SCAppNotification *_displayChatForUser_notification;
    NSString *_displayChatForGroup_conversationId;
    SCAppNotification *_displayChatForGroup_notification;
    long long _displayChatForGroup_source;
    NSString *_displayChatForGroup_subpageName;
}

+ (id)presentLocationSettings;
+ (id)prepareViewForPresentation;
+ (id)prepareViewForDismissal;
+ (id)displayChatForUserWithUsername:(id)arg1 userId:(id)arg2 notification:(id)arg3;
+ (id)displayChatForGroupWithConversationId:(id)arg1 notification:(id)arg2 source:(long long)arg3 subpageName:(id)arg4;
- (void).cxx_destruct;
- (void)matchDisplayChatForUser:(CDUnknownBlockType)arg1 displayChatForGroup:(CDUnknownBlockType)arg2 presentLocationSettings:(CDUnknownBlockType)arg3 prepareViewForPresentation:(CDUnknownBlockType)arg4 prepareViewForDismissal:(CDUnknownBlockType)arg5;
- (id)internalInit;

@end

