//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCFeatureReference;
@protocol SCImageDownloading, SCLensCreatorBlacklistManaging, SCLensCreatorSubscriptionProviding, SCLensInfoCardDataProvidable, SCLensInfoCardLogging, SCUnlockedLensRemoving;

@interface SCLensInfoCardInteractorDependencies : NSObject
{
    id <SCLensInfoCardDataProvidable> _dataProvider;
    id <SCUnlockedLensRemoving> _lensRemover;
    id <SCLensCreatorBlacklistManaging> _lensCreatorBlacklistManager;
    id <SCLensCreatorSubscriptionProviding> _subscriptionProvider;
    id <SCImageDownloading> _imageDownloader;
    id <SCLensInfoCardLogging> _logger;
    SCFeatureReference *_lensCarouselFeature;
}

@property(readonly, nonatomic) SCFeatureReference *lensCarouselFeature; // @synthesize lensCarouselFeature=_lensCarouselFeature;
@property(readonly, nonatomic) id <SCLensInfoCardLogging> logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) id <SCImageDownloading> imageDownloader; // @synthesize imageDownloader=_imageDownloader;
@property(readonly, nonatomic) id <SCLensCreatorSubscriptionProviding> subscriptionProvider; // @synthesize subscriptionProvider=_subscriptionProvider;
@property(readonly, nonatomic) id <SCLensCreatorBlacklistManaging> lensCreatorBlacklistManager; // @synthesize lensCreatorBlacklistManager=_lensCreatorBlacklistManager;
@property(readonly, nonatomic) id <SCUnlockedLensRemoving> lensRemover; // @synthesize lensRemover=_lensRemover;
@property(readonly, nonatomic) id <SCLensInfoCardDataProvidable> dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;
- (id)initWithDataProvider:(id)arg1 lensRemover:(id)arg2 lensCreatorBlacklistManager:(id)arg3 subscriptionProvider:(id)arg4 imageDownloader:(id)arg5 logger:(id)arg6 lensCarouselFeature:(id)arg7;

@end

