//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSAttributedString, SCLensExplorerLensItem, UIColor, UIImage;

@interface SCLensExplorerLensCellViewModel : NSObject <NSCopying, NSCoding>
{
    _Bool _isDebugEnabled;
    _Bool _isLongPressActionSupported;
    SCLensExplorerLensItem *_lensItem;
    unsigned long long _cellType;
    UIColor *_color;
    NSAttributedString *_creatorUserName;
    NSAttributedString *_lensName;
    double _debugButtonCornerPadding;
    UIImage *_previewImage;
    UIImage *_iconImage;
    struct CGSize _debugButtonSize;
    struct CGSize _fullCellSize;
    struct CGSize _previewSize;
    struct CGRect _iconFrame;
}

+ (id)cellViewModelWithoutImagesWithViewModel:(id)arg1;
+ (id)cellViewModelWithViewModel:(id)arg1 iconImage:(id)arg2;
+ (id)cellViewModelWithViewModel:(id)arg1 previewImage:(id)arg2;
+ (id)cellViewModelWithLensExplorerItem:(id)arg1 configuration:(id)arg2 index:(unsigned long long)arg3 isTextRightToLeftDirection:(_Bool)arg4;
+ (id)loadingCellViewModelWithConfiguration:(id)arg1;
+ (id)colorForIndex:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool isLongPressActionSupported; // @synthesize isLongPressActionSupported=_isLongPressActionSupported;
@property(readonly, copy, nonatomic) UIImage *iconImage; // @synthesize iconImage=_iconImage;
@property(readonly, copy, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
@property(readonly, nonatomic) struct CGRect iconFrame; // @synthesize iconFrame=_iconFrame;
@property(readonly, nonatomic) struct CGSize previewSize; // @synthesize previewSize=_previewSize;
@property(readonly, nonatomic) struct CGSize fullCellSize; // @synthesize fullCellSize=_fullCellSize;
@property(readonly, nonatomic) _Bool isDebugEnabled; // @synthesize isDebugEnabled=_isDebugEnabled;
@property(readonly, nonatomic) double debugButtonCornerPadding; // @synthesize debugButtonCornerPadding=_debugButtonCornerPadding;
@property(readonly, nonatomic) struct CGSize debugButtonSize; // @synthesize debugButtonSize=_debugButtonSize;
@property(readonly, copy, nonatomic) NSAttributedString *lensName; // @synthesize lensName=_lensName;
@property(readonly, copy, nonatomic) NSAttributedString *creatorUserName; // @synthesize creatorUserName=_creatorUserName;
@property(readonly, copy, nonatomic) UIColor *color; // @synthesize color=_color;
@property(readonly, nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(readonly, copy, nonatomic) SCLensExplorerLensItem *lensItem; // @synthesize lensItem=_lensItem;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithLensItem:(id)arg1 cellType:(unsigned long long)arg2 color:(id)arg3 creatorUserName:(id)arg4 lensName:(id)arg5 debugButtonSize:(struct CGSize)arg6 debugButtonCornerPadding:(double)arg7 isDebugEnabled:(_Bool)arg8 fullCellSize:(struct CGSize)arg9 previewSize:(struct CGSize)arg10 iconFrame:(struct CGRect)arg11 previewImage:(id)arg12 iconImage:(id)arg13 isLongPressActionSupported:(_Bool)arg14;
- (id)initWithCoder:(id)arg1;

@end

