//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensExplorerBaseQueryCoordinatorDelegate-Protocol.h"
#import "SCLensExplorerQueryCoordinating-Protocol.h"

@class NSString, SCBehaviorSubject, SCDisposableObserver, SCFuture, SCLensExplorerBaseQueryCoordinator, SCSearchNavigationCoordinator, SCSearchQuery;
@protocol SCLensExplorerBaseQueryCoordinatorDelegate, SCLensExplorerDataStoreProtocol, SCLensExplorerQueryStatusChecking, SCPerforming;

@interface SCLensExplorerMockedQueryCoordinator : NSObject <SCLensExplorerBaseQueryCoordinatorDelegate, SCLensExplorerQueryCoordinating>
{
    SCLensExplorerBaseQueryCoordinator *_realQueryCoordinator;
    id <SCLensExplorerDataStoreProtocol> _dataStore;
    SCBehaviorSubject *_onItemsUpdatedObservable;
    id <SCPerforming> _performer;
    SCDisposableObserver *_disposeBag;
    id <SCLensExplorerQueryStatusChecking> _queryStatusChecker;
    _Bool _initialRequestCompleted;
    _Bool isLoading;
    SCSearchQuery *currentQuery;
    SCSearchNavigationCoordinator *navigationCoordinator;
    id <SCLensExplorerBaseQueryCoordinatorDelegate> _delegate;
}

+ (_Bool)isAvailable;
@property(nonatomic) __weak id <SCLensExplorerBaseQueryCoordinatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading;
@property(nonatomic) __weak SCSearchNavigationCoordinator *navigationCoordinator; // @synthesize navigationCoordinator;
@property(copy, nonatomic) SCSearchQuery *currentQuery; // @synthesize currentQuery;
- (void).cxx_destruct;
- (void)didFinishLoadingItemsWithQueryCoordinator:(id)arg1 isEmpty:(_Bool)arg2 pageViewType:(long long)arg3;
- (void)_updateDataStoreForLensExplorerV1WithQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (void)_realResultsForQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (void)_updateDataStoreWithRegularLenses;
- (void)_didUpdateItems;
- (void)reset;
@property(readonly, nonatomic) SCFuture *isEmpty;
- (id)onItemsUpdatedObservable;
- (_Bool)canPerformQuery:(id)arg1;
- (void)handleResponseData:(id)arg1 forQuery:(id)arg2;
- (void)resultsForQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (id)initWithRealQueryCoordinator:(id)arg1 queryStatusChecker:(id)arg2 dataStore:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

