//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensDataFetchRanking-Protocol.h"
#import "SCLensDataFetchRankingÐ¡ontextProviding-Protocol.h"

@class NSString, SCLensDataFetchRankerSettings, SCRequestManager;

@interface SCLensDataFetchRanker : NSObject <SCLensDataFetchRanking, SCLensDataFetchRankingÐ¡ontextProviding>
{
    SCRequestManager *_requestManager;
    SCLensDataFetchRankerSettings *_settings;
}

- (void).cxx_destruct;
- (id)_lensContextsWithParentContext:(unsigned long long)arg1;
- (id)_lensContextsWithParentContext:(unsigned long long)arg1 lensId:(id)arg2;
- (id)lensesContextForFetchingWithLensId:(id)arg1 parentContext:(unsigned long long)arg2;
- (void)setCameraLensesContextWithOrderedLenses:(id)arg1 parentContext:(unsigned long long)arg2;
- (void)removeLensesContext;
- (void)setLensesContextWithLens:(id)arg1 parentContext:(unsigned long long)arg2;
- (id)initWithRequestManager:(id)arg1 settings:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

