//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCLensExplorerBaseQueryCoordinator.h"

@class SCLensExplorerDataStore, SCLensExplorerSectionDebugInfoProvider;

@interface SCLensExplorerRankingLensesQueryCoordinator : SCLensExplorerBaseQueryCoordinator
{
    SCLensExplorerDataStore *_lensDataStore;
    SCLensExplorerSectionDebugInfoProvider *_debugInfoProvider;
    _Bool _initialRequestCompleted;
}

@property _Bool initialRequestCompleted; // @synthesize initialRequestCompleted=_initialRequestCompleted;
- (void).cxx_destruct;
- (void)reset;
- (_Bool)canPerformQuery:(id)arg1;
- (id)convertItemsFromResponseData:(id)arg1 query:(id)arg2;
- (void)handleError:(id)arg1 forQuery:(id)arg2;
- (void)handleResponseData:(id)arg1 forQuery:(id)arg2;
- (id)requestForQuery:(id)arg1;
- (id)initWithRequestManager:(id)arg1 lensDataStore:(id)arg2 queryStatusChecker:(id)arg3 requestProvider:(id)arg4 debugInfoProvider:(id)arg5;

@end

