//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCScanCapturerDelegate-Protocol.h"

@class SCDisposableObserverLifecycle, SCScanUtilityLensRequest, SCScopedAccess;
@protocol SCLocationProvider, SCPerforming, SCScanCapturer, SCScanFrameSelector, SCScanGTQProvider;

@interface SCLensSceneIntelligenceController : NSObject <SCScanCapturerDelegate>
{
    id <SCPerforming> _performer;
    id <SCScanGTQProvider> _gtqProvider;
    id <SCLocationProvider> _locationProvider;
    id <SCScanCapturer> _scanCapturer;
    id <SCScanFrameSelector> _frameSelector;
    SCScopedAccess *_scanDataOrchestrator;
    SCDisposableObserverLifecycle *_scanDataObserverLifecycle;
    _Bool _isAnalyzing;
    SCScanUtilityLensRequest *_utilityLensRequest;
    struct CGPoint _startingTouchPoint;
    long long _scanSource;
    _Bool _scanBarEnabled;
}

- (void).cxx_destruct;
- (void)_endAnalysis;
- (void)_beginAnalysisWithUtilityLensRequest:(id)arg1 touchPoint:(struct CGPoint)arg2 frameModifier:(id)arg3 scanSource:(long long)arg4 scanBarEnabled:(_Bool)arg5;
- (void)scanCapturer:(id)arg1 didCaptureFrame:(id)arg2 cameraPosition:(long long)arg3;
- (void)analyzeSingleFrameWithUtilityLensRequest:(id)arg1 touchPoint:(struct CGPoint)arg2 frameModifier:(id)arg3 scanSource:(long long)arg4 scanBarEnabled:(_Bool)arg5;
- (id)initWithCapturer:(id)arg1 scanDataOrchestrator:(id)arg2 gtqProvider:(id)arg3 locationProvider:(id)arg4;

@end

