//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCLensDataProviderListener-Protocol.h"
#import "SCLensLifecycleListener-Protocol.h"
#import "SCLensUIUpdateListener-Protocol.h"

@class NSArray, NSString, SCLens;

@protocol SCLensCarouselPresenterProtocol <SCLensUIUpdateListener, SCLensDataProviderListener, SCLensLifecycleListener>
@property(readonly, nonatomic) NSArray *lenses;
- (SCLens *)lensFromCurrentArrayByLensId:(NSString *)arg1;
- (void)reloadCellWithLens:(SCLens *)arg1;
- (SCLens *)selectedLens;
- (void)setLensIdToRestore:(NSString *)arg1;
- (void)updateScrollPositionToSelectedLens;
- (void)updateCurrentLensesSelection;
- (void)selectLastApplicableLens;
- (void)selectLensToTheLeftAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)selectLensToTheRightAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (_Bool)selectLensWithId:(NSString *)arg1 animated:(_Bool)arg2;
@end

