//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLazy;

@interface SCLegacyImageProcessServices : NSObject
{
    SCLazy *_defaultImageProcessCommandProvider;
    SCLazy *_imageProcessLensCommandFactory;
    SCLazy *_sharedComponentManagerPool;
}

@property(readonly, nonatomic) SCLazy *sharedComponentManagerPool; // @synthesize sharedComponentManagerPool=_sharedComponentManagerPool;
@property(readonly, nonatomic) SCLazy *imageProcessLensCommandFactory; // @synthesize imageProcessLensCommandFactory=_imageProcessLensCommandFactory;
@property(readonly, nonatomic) SCLazy *defaultImageProcessCommandProvider; // @synthesize defaultImageProcessCommandProvider=_defaultImageProcessCommandProvider;
- (void).cxx_destruct;
- (id)initWithDefaultImageProcessCommandProvider:(id)arg1 imageProcessLensCommandFactory:(id)arg2 sharedComponentManagerPool:(id)arg3;

@end

