//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNavigationState-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSArray, NSString, UIViewController;

@interface SCLegacyNavigationState : NSObject <SCTraceEnabled, SCNavigationState>
{
    UIViewController *_rootViewController;
}

- (void).cxx_destruct;
- (id)popToDestinationMatching:(CDUnknownBlockType)arg1 becauseOfEvent:(unsigned long long)arg2;
- (void)popToDestination:(id)arg1 becauseOfEvent:(unsigned long long)arg2;
@property(readonly, nonatomic) NSArray *navigationStack;
- (id)initWithRootViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

