//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol SCLocationShareUpsellService <NSObject>
- (void)reportLocationShareIgnoredForUserID:(NSString *)arg1;
- (void)reportLocationShareHappenedForUserID:(NSString *)arg1;
- (void)determineCurrentUpsellStatusForUserId:(NSString *)arg1 friendsWithBitmoji:(long long)arg2 currentlyInGhostMode:(_Bool)arg3 userHasBitmoji:(_Bool)arg4 totalMapFriendCount:(long long)arg5 desiredStyle:(long long)arg6 withCompletion:(void (^)(_Bool, long long))arg7;
@end

