//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCDataHandler.h"

#import "SCEventAnnouncing-Protocol.h"

@class NSString, SCEventListenerAnnouncer;
@protocol SCPerforming;

@interface SCMapTrayBaseDataLoader : SCDataHandler <SCEventAnnouncing>
{
    CDUnknownBlockType _pendingCompletion;
    SCEventListenerAnnouncer *_eventAnnouncer;
    id <SCPerforming> _performer;
}

+ (id)announcerIdentifier;
@property(retain, nonatomic) id <SCPerforming> performer; // @synthesize performer=_performer;
- (void).cxx_destruct;
@property(readonly, nonatomic) double initializationDelay;
- (id)_reloadDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)_maybeLoadDataWithCompletion:(CDUnknownBlockType)arg1 request:(id)arg2;
- (void)_setupLoader;
- (void)announceEvent:(id)arg1;
- (void)handleDataLoaded:(id)arg1 error:(id)arg2;
- (id)initializeLoad;
- (id)initWithPerformer:(id)arg1;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

