//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCLazy, SCMapBitmojiImageView, SIGButton, UIButton, UIImageView, UILabel;
@protocol SCMapLocationUpsellTrayViewDelegate;

@interface SCMapLocationUpsellTrayView : UIView
{
    id <SCMapLocationUpsellTrayViewDelegate> _delegate;
    SCLazy *_bitmojiImageFetcher;
    long long _style;
    SCMapBitmojiImageView *_friend1View;
    SCMapBitmojiImageView *_friend2View;
    SCMapBitmojiImageView *_friend3View;
    SCMapBitmojiImageView *_friend4View;
    SCMapBitmojiImageView *_selfView;
    UIImageView *_mapProp;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_shareWithLabel;
    SIGButton *_letsGoButton;
    SIGButton *_allMyFriendsButton;
    SIGButton *_selectFriendsButton;
    UIButton *_skipButton;
}

- (void).cxx_destruct;
- (void)_layoutButtonsBasedOnStyle:(long long)arg1;
- (void)_configureTextBasedOnStyle:(long long)arg1 friend1FirstName:(id)arg2 friend2FirstName:(id)arg3 friend3FirstName:(id)arg4 friend4FirstName:(id)arg5 totalNumberOfFriends:(long long)arg6;
- (void)layoutSubviews;
- (void)_configureConstraints;
- (void)_skipTapped;
- (void)_selectFriendsTapped;
- (void)_allMyFriendsTapped;
- (void)_letsGoButtonTapped;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2 bitmojiImageFetcher:(id)arg3 peopleFriendsProvider:(id)arg4 friend1:(id)arg5 friend2:(id)arg6 friend3:(id)arg7 friend4:(id)arg8 currentUser:(id)arg9 style:(long long)arg10 upsellFloorAsset:(id)arg11;

@end

