//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCMapTrayMetadataProvider-Protocol.h"

@protocol SCMapTrayUnseenItemTracking;

@interface SCMapTrayMetadataProviderImpl : NSObject <SCMapTrayMetadataProvider>
{
    id <SCMapTrayUnseenItemTracking> _unseenItemsTracker;
    long long _trayType;
}

@property(readonly, nonatomic) long long trayType; // @synthesize trayType=_trayType;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long trayUnseenItemCount;
- (id)initWithUnseenItemsTracker:(id)arg1 mapTrayType:(long long)arg2;

@end

