//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SIGActionSheetCell.h"

#import "SCGalleryEntryThumbnailGeneratorDelegate-Protocol.h"

@class NSString, UIImageView;
@protocol SCGalleryEntry, SCGalleryEntryThumbnailGenerating;

@interface SCMemoriesActionSheetCard : SIGActionSheetCell <SCGalleryEntryThumbnailGeneratorDelegate>
{
    id <SCGalleryEntry> _entry;
    UIImageView *_imageView;
    id <SCGalleryEntryThumbnailGenerating> _thumbnailGenerator;
}

- (void).cxx_destruct;
- (void)thumbnailGeneratorHasDelayedLoading:(id)arg1;
- (void)thumbnailGenerator:(id)arg1 didLoadMiniThumbnail:(id)arg2 snap:(id)arg3 duration:(double)arg4;
- (void)thumbnailGenerator:(id)arg1 didUpdateStoryThumbnailWithImage:(id)arg2 snap:(id)arg3 duration:(double)arg4;
- (void)thumbnailGenerator:(id)arg1 didUpdateSnapThumbnailWithImage:(id)arg2 snap:(id)arg3 duration:(double)arg4;
- (id)_titleString:(id)arg1;
- (void)setEntry:(id)arg1 userSession:(id)arg2 thumbnailProvider:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

