//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString, NSURL;

@interface SCMediaOrchestrationSessionInfoBuilder : NSObject
{
    unsigned long long _sessionStatus;
    NSString *_encryptionKey;
    NSString *_encryptionIv;
    NSURL *_contentURL;
    NSData *_serializedContentObject;
}

+ (id)mediaOrchestrationSessionInfoFromExistingMediaOrchestrationSessionInfo:(id)arg1;
+ (id)mediaOrchestrationSessionInfo;
- (void).cxx_destruct;
- (id)withSerializedContentObject:(id)arg1;
- (id)withContentURL:(id)arg1;
- (id)withEncryptionIv:(id)arg1;
- (id)withEncryptionKey:(id)arg1;
- (id)withSessionStatus:(unsigned long long)arg1;
- (id)build;

@end

