//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SCUserSession, UILongPressGestureRecognizer, UIView, UIViewController;
@protocol SCGalleryItem, SCGallerySnap, SCMemoriesActionMenuHelperDataSource, SCMemoriesActionMenuHelperDelegate;

@protocol SCMemoriesActionMenuHelping <NSObject>
@property(readonly, nonatomic) __weak id <SCMemoriesActionMenuHelperDataSource> dataSource;
@property(readonly, nonatomic) __weak id <SCMemoriesActionMenuHelperDelegate> delegate;
- (void)presentActionMenuForItem:(id <SCGalleryItem>)arg1 snap:(id <SCGallerySnap>)arg2 sourcePageName:(NSString *)arg3 sourceView:(UIView *)arg4 viewController:(UIViewController *)arg5;
- (void)handleLongPress:(UILongPressGestureRecognizer *)arg1 item:(id <SCGalleryItem>)arg2 snap:(id <SCGallerySnap>)arg3 sourcePageName:(NSString *)arg4 sourceView:(UIView *)arg5 viewController:(UIViewController *)arg6;
- (id)initWithActionMenuType:(long long)arg1 dataSource:(id <SCMemoriesActionMenuHelperDataSource>)arg2 delegate:(id <SCMemoriesActionMenuHelperDelegate>)arg3 userSession:(SCUserSession *)arg4;
@end

