//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SIGCollectionViewCell.h"

#import "SCGalleryEntryThumbnailGeneratorDelegate-Protocol.h"
#import "SCMemoriesCellSelecting-Protocol.h"
#import "SCMemoriesCellTransitioning-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIImageView, UILabel, UITextField, UIView;
@protocol SCGalleryEntryThumbnailGenerating, SCMemoriesStoryEditorHeaderCellDelegate;

@interface SCMemoriesStoryEditorHeaderCell : SIGCollectionViewCell <SCGalleryEntryThumbnailGeneratorDelegate, UITextFieldDelegate, SCMemoriesCellSelecting, SCMemoriesCellTransitioning>
{
    UIImageView *_thumbnailImageView;
    UILabel *_subtitleLabel;
    UITextField *_textField;
    UIView *_trailingContainerView;
    NSLayoutConstraint *_trailingContainerViewWidth;
    id <SCGalleryEntryThumbnailGenerating> _thumbnailGenerator;
    id <SCMemoriesStoryEditorHeaderCellDelegate> _delegate;
}

@property(nonatomic) __weak id <SCMemoriesStoryEditorHeaderCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)setTransitioningInitialImage:(id)arg1;
- (id)transitioningExpandingView;
- (id)transitioningImage;
- (id)transitioningPosterFrame;
- (unsigned long long)interactionMode;
- (void)animateLongTapForTouchLocation:(struct CGPoint)arg1 reverse:(_Bool)arg2;
- (void)setSelectMode:(_Bool)arg1;
- (void)setSelected:(_Bool)arg1 selectOverlayImage:(id)arg2 snapIds:(id)arg3;
- (void)setHighlighted:(_Bool)arg1;
- (void)thumbnailGeneratorHasDelayedLoading:(id)arg1;
- (void)thumbnailGenerator:(id)arg1 didLoadMiniThumbnail:(id)arg2 snap:(id)arg3 duration:(double)arg4;
- (void)thumbnailGenerator:(id)arg1 didUpdateStoryThumbnailWithImage:(id)arg2 snap:(id)arg3 duration:(double)arg4;
- (void)thumbnailGenerator:(id)arg1 didUpdateSnapThumbnailWithImage:(id)arg2 snap:(id)arg3 duration:(double)arg4;
- (void)_saveButtonTapped;
- (void)_updateTrailingView:(id)arg1;
- (void)setViewModel:(id)arg1 thumbnailGenerator:(id)arg2;
- (id)_loadingView;
- (id)_saveButton;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

