//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, NSURL;

@interface SCMusicTrack : NSObject <NSCopying>
{
    int _trackId;
    int _durationInSeconds;
    NSString *_title;
    NSString *_artistName;
    NSURL *_audioFileURL;
    NSURL *_imageURL;
}

@property(readonly, nonatomic) int durationInSeconds; // @synthesize durationInSeconds=_durationInSeconds;
@property(readonly, copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(readonly, copy, nonatomic) NSURL *audioFileURL; // @synthesize audioFileURL=_audioFileURL;
@property(readonly, copy, nonatomic) NSString *artistName; // @synthesize artistName=_artistName;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) int trackId; // @synthesize trackId=_trackId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTrackId:(int)arg1 title:(id)arg2 artistName:(id)arg3 audioFileURL:(id)arg4 imageURL:(id)arg5 durationInSeconds:(int)arg6;

@end

