//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, SCFuture, SCNMessagingMultiRecipientFeedEntryIdentifier;
@protocol SCArroyoFeedDataUpdateAnnouncer;

@protocol SCNativeMessagingFeedManaging
@property(readonly, nonatomic) SCFuture *initialLocalFeedEntries;
- (void)leaveLegacyConversation:(NSString *)arg1;
- (void)retryMultiRecipientFeedEntry:(SCNMessagingMultiRecipientFeedEntryIdentifier *)arg1;
- (void)clearOneOnOneConversationByUserId:(NSString *)arg1;
- (void)clearGroupConversationById:(NSString *)arg1;
- (void)enterFeed;
- (void)exitFeed;
- (void)enterLegacyConversation;
- (_Bool)hasMoreFeedEntries;
- (id <SCArroyoFeedDataUpdateAnnouncer>)feedDataUpdateAnnouncer;
@end

