//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCNContentResolutionGoogleXTController : NSObject
{
    struct Handle<std::__1::shared_ptr<snap::content_resolution::GoogleXTController>, std::__1::shared_ptr<snap::content_resolution::GoogleXTController>> _cppRefHandle;
}

+ (id)getInstance:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateCachedHostFromRedirectedUrl:(id)arg1 finalRedirectedUrl:(id)arg2;
- (id)getReplacedXTHost:(id)arg1;
- (id)initWithCpp:(const shared_ptr_f47af111 *)arg1;

@end

