//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCNContentManagerCacheController : NSObject
{
    struct Handle<std::__1::shared_ptr<snap::content_manager::CacheController>, std::__1::shared_ptr<snap::content_manager::CacheController>> _cppRefHandle;
}

+ (void)load:(id)arg1 dataProviderFactory:(id)arg2 metrics:(id)arg3;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithCpp:(const shared_ptr_b1a20913 *)arg1;

@end

