//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCNMessagingTweaks, SCNMessagingUUID;

@interface SCNMessagingSessionParameters : NSObject
{
    _Bool _debug;
    NSString *_databaseLocation;
    SCNMessagingUUID *_userId;
    NSString *_userAgentPrefix;
    SCNMessagingTweaks *_tweaks;
}

+ (id)SessionParametersWithDatabaseLocation:(id)arg1 userId:(id)arg2 userAgentPrefix:(id)arg3 debug:(_Bool)arg4 tweaks:(id)arg5;
@property(readonly, nonatomic) SCNMessagingTweaks *tweaks; // @synthesize tweaks=_tweaks;
@property(readonly, nonatomic) _Bool debug; // @synthesize debug=_debug;
@property(readonly, nonatomic) NSString *userAgentPrefix; // @synthesize userAgentPrefix=_userAgentPrefix;
@property(readonly, nonatomic) SCNMessagingUUID *userId; // @synthesize userId=_userId;
@property(readonly, nonatomic) NSString *databaseLocation; // @synthesize databaseLocation=_databaseLocation;
- (void).cxx_destruct;
- (id)description;
- (id)initWithDatabaseLocation:(id)arg1 userId:(id)arg2 userAgentPrefix:(id)arg3 debug:(_Bool)arg4 tweaks:(id)arg5;

@end

