//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SCOnDemandResource, SCOnDemandZippedResource;

@protocol SCOnDemandResourceDownloader <NSObject>
- (void)downloadImage:(id <SCOnDemandResource>)arg1 comletion:(void (^)(UIImage *))arg2;
- (void)downloadAndUnzipAsImages:(id <SCOnDemandZippedResource>)arg1 completion:(void (^)(NSArray *))arg2;
- (void)downloadAndUnzip:(id <SCOnDemandZippedResource>)arg1 completion:(void (^)(NSArray *))arg2;
- (void)download:(id <SCOnDemandResource>)arg1 completion:(void (^)(NSData *))arg2;
- (void)prefetch:(id <SCOnDemandResource>)arg1;
@end

