//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCOperaLayer-Protocol.h"

@class NSDictionary, NSString, SCOperaAdStoreViewModel, SCOperaPage;

@interface SCOperaStoreV2Layer : NSObject <SCOperaLayer>
{
    _Bool _presentStoreOnVisibleDismissStoreOnCancel;
    _Bool _enableViewLifecycleEvent;
    _Bool _enableStoreProductVCInitializationUponSwipeUp;
    SCOperaPage *_page;
    NSDictionary *_storeParams;
    NSString *_appAuthorText;
    SCOperaAdStoreViewModel *_adStoreViewModel;
}

+ (id)layerWithProperties:(id)arg1 page:(id)arg2;
@property(readonly, nonatomic) _Bool enableStoreProductVCInitializationUponSwipeUp; // @synthesize enableStoreProductVCInitializationUponSwipeUp=_enableStoreProductVCInitializationUponSwipeUp;
@property(readonly, nonatomic) _Bool enableViewLifecycleEvent; // @synthesize enableViewLifecycleEvent=_enableViewLifecycleEvent;
@property(readonly, copy, nonatomic) SCOperaAdStoreViewModel *adStoreViewModel; // @synthesize adStoreViewModel=_adStoreViewModel;
@property(readonly, copy, nonatomic) NSString *appAuthorText; // @synthesize appAuthorText=_appAuthorText;
@property(nonatomic) _Bool presentStoreOnVisibleDismissStoreOnCancel; // @synthesize presentStoreOnVisibleDismissStoreOnCancel=_presentStoreOnVisibleDismissStoreOnCancel;
@property(readonly, copy, nonatomic) NSDictionary *storeParams; // @synthesize storeParams=_storeParams;
@property(nonatomic) __weak SCOperaPage *page; // @synthesize page=_page;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)type;
- (id)initWithProperties:(id)arg1 page:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

