//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNavigationLogging-Protocol.h"

@class NSOperationQueue, NSString, SCDisposableObserverLifecycle, SCLazy;

@interface SCPagePageViewReporter : NSObject <SCNavigationLogging>
{
    NSOperationQueue *_pagePageViewReportQueue;
    SCLazy *_blizzardLogger;
    SCDisposableObserverLifecycle *_disposableObserverLifecycle;
    double _lastPageTransitionStartTimestamp;
    long long _pageSequenceId;
    long long _lastExitEvent;
    _Bool _isFFBadgeOn;
    _Bool _isDFBadgeOn;
    _Bool _isAddFriendsBadgeOn;
    _Bool _isMemoriesBadgeOn;
}

- (void).cxx_destruct;
- (void)_didEndPageTransition:(double)arg1;
- (void)_didEndPageViewWithNextPageName:(id)arg1 finishedPageName:(id)arg2 prevPageName:(id)arg3 startTimestamp:(double)arg4 endTimestamp:(double)arg5;
- (void)_didChangeCurrentPageEvent:(id)arg1;
- (void)setMemoriesBadgeOn:(_Bool)arg1;
- (void)setAddFriendsBadgeOn:(_Bool)arg1;
- (void)setDiscoverFeedBadgeOn:(_Bool)arg1;
- (void)setFriendsFeedBadgeOn:(_Bool)arg1;
- (void)setExitEvent:(long long)arg1;
- (void)subscribeOnCurrentPageEvent:(id)arg1;
- (id)initWithReportQueue:(id)arg1 blizzardLogger:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

