//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GTPColor, NSMutableArray, NSString;

@interface SCPCNScanCardData : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *actionButtonsArray; // @dynamic actionButtonsArray;
@property(readonly, nonatomic) unsigned long long actionButtonsArray_Count; // @dynamic actionButtonsArray_Count;
@property(copy, nonatomic) NSString *brandImageURL; // @dynamic brandImageURL;
@property(copy, nonatomic) NSString *brandName; // @dynamic brandName;
@property(retain, nonatomic) GTPColor *brandNameColor; // @dynamic brandNameColor;
@property(copy, nonatomic) NSString *category; // @dynamic category;
@property(nonatomic) _Bool hasBrandNameColor; // @dynamic hasBrandNameColor;
@property(copy, nonatomic) NSString *html; // @dynamic html;
@property(copy, nonatomic) NSString *itemDescription; // @dynamic itemDescription;
@property(copy, nonatomic) NSString *itemImageURL; // @dynamic itemImageURL;
@property(copy, nonatomic) NSString *itemName; // @dynamic itemName;

@end

