//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCPlugInScopeExposer.h"

#import "SCScopeContainerDelegate-Protocol.h"
#import "SCScopeLifecycleContainer-Protocol.h"

@class NSString, SCPlugInSetRegistry, SCScopeContainer;
@protocol SCPlugInScopeContainerDelegate;

@interface SCPlugInScopeContainer : SCPlugInScopeExposer <SCScopeContainerDelegate, SCScopeLifecycleContainer>
{
    SCScopeContainer *_scopeContainer;
    SCPlugInSetRegistry *_plugInRegistry;
    CDUnknownBlockType _plugInLoader;
    id <SCPlugInScopeContainerDelegate> _delegate;
}

@property(nonatomic) __weak id <SCPlugInScopeContainerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scopeContainer:(id)arg1 removingScope:(id)arg2;
- (void)scopeContainer:(id)arg1 exposingScope:(id)arg2;
- (void)beginLifecycle;
- (void)removeScope;
- (id)scope;
- (void)exposePlugInScope:(CDUnknownBlockType)arg1 onPlugInsRegistered:(CDUnknownBlockType)arg2;
- (id)initWithScopeContainer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

