//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSString;

@interface SCPMDRDeliverableModelHandle : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSData *contentObject; // @dynamic contentObject;
@property(readonly, nonatomic) int handleOneOfCase; // @dynamic handleOneOfCase;
@property(copy, nonatomic) NSString *modelId; // @dynamic modelId;

@end

