//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCExtensionSharedDirectory, SCExtensionSharedFile;

@interface SCProcessedNotificationPersister : NSObject
{
    NSString *_userId;
    NSString *_yesterdayFileName;
    NSString *_todayFileName;
    SCExtensionSharedFile *_notifProcessedTodayFile;
    SCExtensionSharedFile *_notifProcessedYesterdayFile;
    SCExtensionSharedDirectory *_sharedExtensionFolder;
}

- (void).cxx_destruct;
- (void)cleanUpProcessedNotificationsFiles;
- (void)saveProcessedNotificationId:(id)arg1;
- (_Bool)notificationProcessed:(id)arg1;
- (id)initWithUserId:(id)arg1 sharedExtensionFolder:(id)arg2 todayFileName:(id)arg3 yesterdayFileName:(id)arg4 notifProcessedTodayFile:(id)arg5 notifProcessedYesterdayFile:(id)arg6;
- (id)initWithUserId:(id)arg1;

@end

