//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCPreviewFilterDataProvider-Protocol.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSMutableSet, NSString, SCAltitude, SCArSegmentationImageGenerator, SCCarouselGroupConfigParser, SCFuture, SCImageProcessCommandConfiguration, SCPreviewFilterDataProviderContextData, SCSnapCommonLoggingParameters, SCSpeed, SCTimestampMetadata, SCUnlockablesContextBasedSelector, SCUserSession, SCVenueFilterSelector, SCVenueInfoSticker, SCWeather, UIImage;
@protocol SCPreviewFeatureContextImageClassifier, SCPreviewFilterDataProviderDelegate, SCUnifiedCameraObjectDataFetching;

@interface SCPreviewStaticFilterDataProvider : NSObject <SCPreviewFilterDataProvider>
{
    _Bool _updating;
    NSMutableDictionary *_geoFilterImages;
    NSMutableDictionary *_geoFilterAppearanceSettings;
    SCArSegmentationImageGenerator *_arSegmentationImageGenerator;
    UIImage *_fullScreenImage;
    SCFuture *_fullScreenImageFuture;
    UIImage *_contextFilteredImage;
    NSMutableSet *_requestedGeoFilterIds;
    _Bool _isGeoFilterLoaded;
    SCUserSession *_userSession;
    NSMutableDictionary *_activeGeofiltersMap;
    id <SCUnifiedCameraObjectDataFetching> _ucoDataFetcher;
    _Bool _isReverseMotionFilterSelected;
    _Bool _hasUserUnlockedFilter;
    _Bool _isVenueFilterSelected;
    _Bool _isStreakFilterSelected;
    id <SCPreviewFilterDataProviderDelegate> _delegate;
    NSArray *_visualFilterNames;
    NSArray *_speedMotionFilterConfigs;
    NSDictionary *_reverseMotionFilterConfig;
    SCVenueFilterSelector *_venueFilterSelector;
    NSArray *_geoFilters;
    SCSpeed *_speed;
    SCTimestampMetadata *_timestamp;
    SCWeather *_weather;
    SCVenueInfoSticker *_venueInfo;
    unsigned long long _batteryStatus;
    SCAltitude *_altitude;
    SCImageProcessCommandConfiguration *_selectedCommandConfiguration;
    NSString *_selectedSmartFilterName;
    NSString *_selectedContextFilterId;
    NSString *_selectedSpeedMotionFilterName;
    NSString *_selectedGeoFilterId;
    NSArray *_selectedGeoFilterIds;
    NSString *_userUnlockedFilterId;
    long long _streakCount;
    SCUnlockablesContextBasedSelector *_geofilterContextBasedSelector;
    SCSnapCommonLoggingParameters *_commonLoggingParameters;
    SCPreviewFilterDataProviderContextData *_filterContextData;
    SCCarouselGroupConfigParser *_carouselGroupConfigParser;
    id <SCPreviewFeatureContextImageClassifier> _contextImageClassifier;
}

@property(retain, nonatomic) id <SCPreviewFeatureContextImageClassifier> contextImageClassifier; // @synthesize contextImageClassifier=_contextImageClassifier;
@property(readonly, nonatomic) SCCarouselGroupConfigParser *carouselGroupConfigParser; // @synthesize carouselGroupConfigParser=_carouselGroupConfigParser;
@property(retain, nonatomic) SCPreviewFilterDataProviderContextData *filterContextData; // @synthesize filterContextData=_filterContextData;
@property(retain, nonatomic) SCSnapCommonLoggingParameters *commonLoggingParameters; // @synthesize commonLoggingParameters=_commonLoggingParameters;
@property(retain, nonatomic) SCUnlockablesContextBasedSelector *geofilterContextBasedSelector; // @synthesize geofilterContextBasedSelector=_geofilterContextBasedSelector;
@property(readonly, nonatomic) _Bool isStreakFilterSelected; // @synthesize isStreakFilterSelected=_isStreakFilterSelected;
@property(readonly, nonatomic) long long streakCount; // @synthesize streakCount=_streakCount;
@property(readonly, nonatomic) _Bool isVenueFilterSelected; // @synthesize isVenueFilterSelected=_isVenueFilterSelected;
@property(readonly, nonatomic) _Bool hasUserUnlockedFilter; // @synthesize hasUserUnlockedFilter=_hasUserUnlockedFilter;
@property(readonly, copy, nonatomic) NSString *userUnlockedFilterId; // @synthesize userUnlockedFilterId=_userUnlockedFilterId;
@property(readonly, nonatomic) _Bool isReverseMotionFilterSelected; // @synthesize isReverseMotionFilterSelected=_isReverseMotionFilterSelected;
@property(readonly, copy, nonatomic) NSArray *selectedGeoFilterIds; // @synthesize selectedGeoFilterIds=_selectedGeoFilterIds;
@property(readonly, copy, nonatomic) NSString *selectedGeoFilterId; // @synthesize selectedGeoFilterId=_selectedGeoFilterId;
@property(readonly, copy, nonatomic) NSString *selectedSpeedMotionFilterName; // @synthesize selectedSpeedMotionFilterName=_selectedSpeedMotionFilterName;
@property(readonly, copy, nonatomic) NSString *selectedContextFilterId; // @synthesize selectedContextFilterId=_selectedContextFilterId;
@property(readonly, copy, nonatomic) NSString *selectedSmartFilterName; // @synthesize selectedSmartFilterName=_selectedSmartFilterName;
@property(readonly, copy, nonatomic) SCImageProcessCommandConfiguration *selectedCommandConfiguration; // @synthesize selectedCommandConfiguration=_selectedCommandConfiguration;
@property(readonly, nonatomic) SCAltitude *altitude; // @synthesize altitude=_altitude;
@property(readonly, nonatomic) unsigned long long batteryStatus; // @synthesize batteryStatus=_batteryStatus;
@property(readonly, nonatomic) SCVenueInfoSticker *venueInfo; // @synthesize venueInfo=_venueInfo;
@property(readonly, nonatomic) SCWeather *weather; // @synthesize weather=_weather;
@property(readonly, nonatomic) SCTimestampMetadata *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) SCSpeed *speed; // @synthesize speed=_speed;
@property(readonly, copy, nonatomic) NSArray *geoFilters; // @synthesize geoFilters=_geoFilters;
@property(readonly, nonatomic) SCVenueFilterSelector *venueFilterSelector; // @synthesize venueFilterSelector=_venueFilterSelector;
@property(readonly, copy, nonatomic) NSArray *visualFilterNames; // @synthesize visualFilterNames=_visualFilterNames;
@property(nonatomic) __weak id <SCPreviewFilterDataProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long selectedGeoFilterMediaSubType;
@property(readonly, copy, nonatomic) NSArray *unlockFilters;
- (void)updateWeatherViewType:(id)arg1;
- (void)updateAltitudeType:(id)arg1;
- (void)_stopUpdatingFilterDataStore;
- (void)_startUpdatingFilterDataStore;
- (void)_fetchGeoFilterImages;
- (void)_fillActiveGeofiltersMap;
- (id)geofilterByFilterId:(id)arg1;
- (void)startUpdatingVenueStickerData;
- (_Bool)shouldFilterDataProviderRequestToUseLocation;
- (void)stopUpdatingFilterData;
- (void)startUpdatingFilterData;
- (void)startUpdatingInfoStickerData;
- (void)userDidInteractWithHostView;
- (void)startPreviewContextImageClassification;
- (void)updateGeoFilter:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *geoFilterAppearanceSettingsDictionary;
@property(readonly, copy, nonatomic) NSArray *venues;
@property(readonly, copy, nonatomic) NSArray *geoFilterImages;
@property(readonly, copy, nonatomic) NSDictionary *reverseMotionFilterConfig; // @synthesize reverseMotionFilterConfig=_reverseMotionFilterConfig;
@property(readonly, copy, nonatomic) NSArray *speedMotionFilterConfigs; // @synthesize speedMotionFilterConfigs=_speedMotionFilterConfigs;
@property(readonly, nonatomic) unsigned long long updateMode;
- (void)clear;
- (id)initWithFullScreenImage:(id)arg1 fullScreenImageFuture:(id)arg2 mediaOrientation:(long long)arg3 userSession:(id)arg4 visualFilterNames:(id)arg5 contextFilteredImage:(id)arg6 geoFilters:(id)arg7 venueFilterSelector:(id)arg8 speed:(id)arg9 weather:(id)arg10 altitude:(id)arg11 timestamp:(id)arg12 batteryStatus:(unsigned long long)arg13 streakCount:(long long)arg14 selectedCommandConfiguration:(id)arg15 selectedContextFilterId:(id)arg16 selectedSmartFilterName:(id)arg17 selectedSpeedMotionFilterName:(id)arg18 speedMotionFilterConfigs:(id)arg19 selectedGeoFilterId:(id)arg20 selectedGeoFilterIds:(id)arg21 isReverseMotionFilterSelected:(_Bool)arg22 isVenueFilterSelected:(_Bool)arg23 isStreakCountSelected:(_Bool)arg24 hideAnimatedGeofilters:(_Bool)arg25 hideGeofilters:(_Bool)arg26;
- (id)initWithVisualFilterNames:(id)arg1 geoFilters:(id)arg2 speed:(id)arg3 weather:(id)arg4 altitude:(id)arg5 timestamp:(id)arg6 batteryStatus:(unsigned long long)arg7 streakCount:(long long)arg8 selectedCommandConfiguration:(id)arg9 selectedContextFilterId:(id)arg10 selectedSmartFilterName:(id)arg11 selectedSpeedMotionFilterName:(id)arg12 speedMotionFilterConfigs:(id)arg13 selectedGeoFilterId:(id)arg14 selectedGeoFilterIds:(id)arg15 isReverseMotionFilterSelected:(_Bool)arg16 isVenueFilterSelected:(_Bool)arg17 isStreakCountSelected:(_Bool)arg18 userSession:(id)arg19;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

