//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCExtensionSharedDirectory, SCExtensionSharedFile, SCQueuePerformer;

@interface SCReceivedSnapPersister : NSObject
{
    NSString *_userId;
    NSString *_yesterdayFileName;
    NSString *_todayFileName;
    SCExtensionSharedFile *_receivedSnapTodayFile;
    SCExtensionSharedFile *_receivedSnapYesterdayFile;
    SCExtensionSharedDirectory *_receivedSnapFolderFolder;
    SCQueuePerformer *_performer;
}

- (void).cxx_destruct;
- (void)cleanUpReceivedSnapFiles;
- (void)addReceivedSnapIds:(id)arg1;
- (id)initWithUserId:(id)arg1 receivedSnapOnExtensionFolder:(id)arg2 todayFileName:(id)arg3 yesterdayFileName:(id)arg4 receivedSnapTodayFile:(id)arg5 receivedSnapYesterdayFile:(id)arg6 queuePerformer:(id)arg7;
- (id)initWithUserId:(id)arg1;

@end

