//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

#import "SCCameraUserStatusImplDelegate-Protocol.h"

@class NSString, SCActiveUserSessionScope, SCServicesExposer, SCUserStorageServices;

@interface SCRequestManagerPermissionEntryPoint : SCEntryPoint <SCCameraUserStatusImplDelegate>
{
    SCActiveUserSessionScope *_userSessionScope;
    SCUserStorageServices *_userStorageServices;
    SCServicesExposer *_requestManagerPermissionServicesExposer;
    SCServicesExposer *_userStatusServicesExposer;
}

@property(retain, nonatomic) SCServicesExposer *userStatusServicesExposer; // @synthesize userStatusServicesExposer=_userStatusServicesExposer;
@property(retain, nonatomic) SCServicesExposer *requestManagerPermissionServicesExposer; // @synthesize requestManagerPermissionServicesExposer=_requestManagerPermissionServicesExposer;
@property(nonatomic) __weak SCUserStorageServices *userStorageServices; // @synthesize userStorageServices=_userStorageServices;
@property(nonatomic) __weak SCActiveUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
- (void).cxx_destruct;
- (_Bool)isLoggedIn;
- (void)_migrateToUserStatus:(id)arg1;
- (void)begin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

