//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface SCS2BitmojiThumbnail : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *fallbackThumbnailURL; // @dynamic fallbackThumbnailURL;
@property(copy, nonatomic) NSString *tileTemplateId; // @dynamic tileTemplateId;

@end

