//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCS2Publisher, SCS2PublisherEdition_Thumbnail, StoryDoc_ID;

@interface SCS2PublisherEdition : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *deeplinkURL; // @dynamic deeplinkURL;
@property(nonatomic) _Bool hasPublisher; // @dynamic hasPublisher;
@property(nonatomic) _Bool hasStoryDocId; // @dynamic hasStoryDocId;
@property(nonatomic) _Bool hasThumbnail; // @dynamic hasThumbnail;
@property(nonatomic) long long id_p; // @dynamic id_p;
@property(nonatomic) long long publishEpoch; // @dynamic publishEpoch;
@property(retain, nonatomic) SCS2Publisher *publisher; // @dynamic publisher;
@property(retain, nonatomic) StoryDoc_ID *storyDocId; // @dynamic storyDocId;
@property(retain, nonatomic) SCS2PublisherEdition_Thumbnail *thumbnail; // @dynamic thumbnail;
@property(copy, nonatomic) NSString *thumbnailURL; // @dynamic thumbnailURL;
@property(copy, nonatomic) NSString *title; // @dynamic title;

@end

