//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCSagaFlashbackTypeCustom, SCSagaFlashbackTypeMonthEnd, SCSagaFlashbackTypeSameDate, SCSagaFlashbackTypeYearEnd;

@interface SCSagaFlashbackType : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCSagaFlashbackTypeSameDate *_flashbackTypeSameDate_flashbackTypeSameDate;
    SCSagaFlashbackTypeMonthEnd *_flashbackTypeMonthEnd_flashbackTypeMonthEnd;
    SCSagaFlashbackTypeYearEnd *_flashbackTypeYearEnd_flashbackTypeYearEnd;
    SCSagaFlashbackTypeCustom *_flashbackTypeCustom_flashbackTypeCustom;
}

+ (id)flashbackTypeYearEndWithFlashbackTypeYearEnd:(id)arg1;
+ (id)flashbackTypeSameDateWithFlashbackTypeSameDate:(id)arg1;
+ (id)flashbackTypeMonthEndWithFlashbackTypeMonthEnd:(id)arg1;
+ (id)flashbackTypeCustomWithFlashbackTypeCustom:(id)arg1;
- (void).cxx_destruct;
- (void)matchFlashbackTypeSameDate:(CDUnknownBlockType)arg1 flashbackTypeMonthEnd:(CDUnknownBlockType)arg2 flashbackTypeYearEnd:(CDUnknownBlockType)arg3 flashbackTypeCustom:(CDUnknownBlockType)arg4;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)asFlashbackTypeCustom;
- (id)asFlashbackTypeYearEnd;
- (id)asFlashbackTypeMonthEnd;
- (id)asFlashbackTypeSameDate;
- (unsigned long long)subtype;
- (_Bool)isSameSubtype:(id)arg1;

@end

