//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCDocObject.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSString, SCSagaFlashbackType;

@interface SCSagaFriendshipFlashback : SCDocObject <NSCopying>
{
    _Bool _viewed;
    NSString *_conversationId;
    NSString *_flashbackId;
    SCSagaFlashbackType *_type;
    NSArray *_messages;
    unsigned long long _startEpochSecInclusive;
    unsigned long long _endEpochSecExclusive;
    long long _displayOrder;
}

+ (struct SCDocObjectClassFunctionPointer)objectClassFunctionPointer;
+ (id)immutableObjectParse:(const void *)arg1 bufferSize:(unsigned long long)arg2;
+ (const char *)table;
@property(readonly, nonatomic) long long displayOrder; // @synthesize displayOrder=_displayOrder;
@property(readonly, nonatomic) _Bool viewed; // @synthesize viewed=_viewed;
@property(readonly, nonatomic) unsigned long long endEpochSecExclusive; // @synthesize endEpochSecExclusive=_endEpochSecExclusive;
@property(readonly, nonatomic) unsigned long long startEpochSecInclusive; // @synthesize startEpochSecInclusive=_startEpochSecInclusive;
@property(readonly, copy, nonatomic) NSArray *messages; // @synthesize messages=_messages;
@property(readonly, copy, nonatomic) SCSagaFlashbackType *type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *flashbackId; // @synthesize flashbackId=_flashbackId;
@property(readonly, copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithConversationId:(id)arg1 flashbackId:(id)arg2 type:(id)arg3 messages:(id)arg4 startEpochSecInclusive:(unsigned long long)arg5 endEpochSecExclusive:(unsigned long long)arg6 viewed:(_Bool)arg7 displayOrder:(long long)arg8;

@end

