//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSMutableArray, SCSagaPbUUID;

@interface SCSagaPbSagaSyncResponse : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *deletedFlashbacksArray; // @dynamic deletedFlashbacksArray;
@property(readonly, nonatomic) unsigned long long deletedFlashbacksArray_Count; // @dynamic deletedFlashbacksArray_Count;
@property(retain, nonatomic) NSMutableArray *flashbacksArray; // @dynamic flashbacksArray;
@property(readonly, nonatomic) unsigned long long flashbacksArray_Count; // @dynamic flashbacksArray_Count;
@property(nonatomic) _Bool fullSync; // @dynamic fullSync;
@property(nonatomic) _Bool hasRequestId; // @dynamic hasRequestId;
@property(nonatomic) unsigned long long nextSyncEpochSec; // @dynamic nextSyncEpochSec;
@property(copy, nonatomic) NSData *nextSyncToken; // @dynamic nextSyncToken;
@property(retain, nonatomic) SCSagaPbUUID *requestId; // @dynamic requestId;

@end

