//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCAuthenticatedNetworkServices, SCBitmojiFetchServices, SCFriendmojiServices, SCFriendsFeedServices, SCGroupServices, SCNavigationServices, SCNetworkImageServices, SCScopeExposer, SCSnapTokenServices, SCSnapchatterServices, SCStoriesServices, SCUserFeatureConfigurationServices, SCUserInfoServices, SCUserSessionScope, SCUserStorageServices;
@protocol SCFeatureLensFeed;

@interface SCSearchV2ViewControllerFactory : NSObject
{
    SCAuthenticatedNetworkServices *_authenticatedNetworkServices;
    SCBitmojiFetchServices *_bitmojiFetchServices;
    SCFriendmojiServices *_friendmojiServices;
    SCFriendsFeedServices *_friendsFeedServices;
    SCGroupServices *_groupServices;
    SCNavigationServices *_navigationServices;
    SCNetworkImageServices *_networkImageServices;
    SCSnapchatterServices *_snapchatterServices;
    SCSnapTokenServices *_snapTokenServices;
    SCStoriesServices *_storiesServices;
    SCUserFeatureConfigurationServices *_userFeatureConfigurationServices;
    SCUserInfoServices *_userInfoServices;
    SCUserSessionScope *_userSessionScope;
    SCUserStorageServices *_userStorageServices;
    SCScopeExposer *_mapScopeExposer;
    id <SCFeatureLensFeed> _lensFeedFeature;
}

- (void).cxx_destruct;
- (id)viewControllerWithMetricsContext:(long long)arg1 displayConfiguration:(id)arg2;
- (id)viewControllerWithMetricsContext:(long long)arg1;
- (id)initWithAuthenticatedNetworkServices:(id)arg1 bitmojiFetchServices:(id)arg2 friendmojiServices:(id)arg3 friendsFeedServices:(id)arg4 groupServices:(id)arg5 navigationServices:(id)arg6 networkImageServices:(id)arg7 snapchatterServices:(id)arg8 snapTokenServices:(id)arg9 storiesServices:(id)arg10 userFeatureConfigurationServices:(id)arg11 userInfoServices:(id)arg12 userSessionScope:(id)arg13 userStorageServices:(id)arg14 mapScopeExposer:(id)arg15 lensFeedFeature:(id)arg16;

@end

