//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSelectionNewGroupDelegate-Protocol.h"

@class NSString, SCLazy;
@protocol SCSelectionNewGroupErrorHandler;

@interface SCSelectionNewGroupCreator : NSObject <SCSelectionNewGroupDelegate>
{
    NSString *_userId;
    SCLazy *_groupDataCreator;
    SCLazy *_groupDataFetcher;
    SCLazy *_groupsDataMutator;
    SCLazy *_snapchattersDataFetcher;
    id <SCSelectionNewGroupErrorHandler> _errorHandler;
}

- (void).cxx_destruct;
- (void)_checkAndUpdateExistingGroup:(id)arg1 groupName:(id)arg2 completion:(CDUnknownBlockType)arg3 completionQueue:(id)arg4;
- (void)_createGroupWithParticipants:(id)arg1 groupName:(id)arg2 completion:(CDUnknownBlockType)arg3 completionQueue:(id)arg4;
- (_Bool)_createGroupPrestepWithSelectedItems:(id)arg1 uiContainer:(id)arg2 snapchatters:(id)arg3;
- (id)_userIdToParticipantsOfSelectionItems:(id)arg1;
- (_Bool)createGroupWithSelectedItems:(id)arg1 groupName:(id)arg2 uiContainer:(id)arg3 completion:(CDUnknownBlockType)arg4 completionQueue:(id)arg5;
- (id)initWithUserId:(id)arg1 groupDataCreator:(id)arg2 groupDataFetcher:(id)arg3 groupDataMutator:(id)arg4 snapchattersDataFetcher:(id)arg5 errorHandler:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

