//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;
@protocol SCUIContainer;

@protocol SCSelectionNewGroupErrorHandler <NSObject>
- (void)cannotEditGroupNameMessage;
- (void)newGroupAlreadyExistingMessage;
- (void)newGroupAlertWithNonMutualFriends:(NSArray *)arg1 uiContainer:(id <SCUIContainer>)arg2;
@end

