//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SIGHeaderButtonItem;
@protocol SCSearchHeaderButtonDelegate;

@interface SCSearchHeaderButtonScope : NSObject
{
    SIGHeaderButtonItem *_buttonItem;
    id <SCSearchHeaderButtonDelegate> _delegate;
}

@property(readonly, nonatomic) __weak id <SCSearchHeaderButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SIGHeaderButtonItem *buttonItem; // @synthesize buttonItem=_buttonItem;
- (void).cxx_destruct;
- (id)initWithButtonItem:(id)arg1 delegate:(id)arg2;

@end

