//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, SCSendToPreviewConfiguration, SCSendToRecipientConfiguration, SCSendToStoryConfiguration;
@protocol SCSendToWorkflowDelegate, SCUIContainer;

@interface SCSendToScope : NSObject
{
    id <SCUIContainer> _uiContainer;
    NSArray *_preSelectedItems;
    SCSendToPreviewConfiguration *_previewConfiguration;
    SCSendToRecipientConfiguration *_recipientConfiguration;
    SCSendToStoryConfiguration *_storyConfiguration;
    id <SCSendToWorkflowDelegate> _delegate;
}

@property(readonly, nonatomic) __weak id <SCSendToWorkflowDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) SCSendToStoryConfiguration *storyConfiguration; // @synthesize storyConfiguration=_storyConfiguration;
@property(readonly, nonatomic) SCSendToRecipientConfiguration *recipientConfiguration; // @synthesize recipientConfiguration=_recipientConfiguration;
@property(readonly, nonatomic) SCSendToPreviewConfiguration *previewConfiguration; // @synthesize previewConfiguration=_previewConfiguration;
@property(readonly, copy, nonatomic) NSArray *preSelectedItems; // @synthesize preSelectedItems=_preSelectedItems;
@property(readonly, nonatomic) id <SCUIContainer> uiContainer; // @synthesize uiContainer=_uiContainer;
- (void).cxx_destruct;
- (id)initWithUIContainer:(id)arg1 preSelectedItems:(id)arg2 previewConfiguration:(id)arg3 recipientConfiguration:(id)arg4 storyConfiguration:(id)arg5 delegate:(id)arg6;

@end

