//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLazy;

@interface SCSendToDataServices : NSObject
{
    SCLazy *_lastSnapDataCoordinator;
    SCLazy *_replySnapchatterObservableRepository;
    SCLazy *_dataPrefetcher;
    SCLazy *_firstSnapRecipientsObservable;
}

@property(readonly, nonatomic) SCLazy *firstSnapRecipientsObservable; // @synthesize firstSnapRecipientsObservable=_firstSnapRecipientsObservable;
@property(readonly, nonatomic) SCLazy *dataPrefetcher; // @synthesize dataPrefetcher=_dataPrefetcher;
@property(readonly, nonatomic) SCLazy *replySnapchatterObservableRepository; // @synthesize replySnapchatterObservableRepository=_replySnapchatterObservableRepository;
@property(readonly, nonatomic) SCLazy *lastSnapDataCoordinator; // @synthesize lastSnapDataCoordinator=_lastSnapDataCoordinator;
- (void).cxx_destruct;
- (id)initWithLastSnapDataCoordinator:(id)arg1 replySnapchatterObservableRepository:(id)arg2 dataPrefetcher:(id)arg3 firstSnapRecipientsObservable:(id)arg4;

@end

