//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCSelectionItem;

@interface SCSelectionItemUpdate : NSObject <NSCopying>
{
    _Bool _isSelected;
    SCSelectionItem *_selectionItem;
    NSString *_source;
}

@property(readonly, copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(readonly, nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(readonly, copy, nonatomic) SCSelectionItem *selectionItem; // @synthesize selectionItem=_selectionItem;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithSelectionItem:(id)arg1 isSelected:(_Bool)arg2 source:(id)arg3;

@end

