//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEventAnnouncing-Protocol.h"
#import "SCObserver-Protocol.h"

@class NSArray, NSString, NSURL, SCSearchQuery, SCSnapKitAppState, SCSnapKitProtoConnectResponse;

@protocol SCSnapKitAppStateController <SCObserver, SCEventAnnouncing>
- (void)endScopeGraph;
- (void)beginScopeGraph;
- (void)updateAppState:(SCSnapKitAppState *)arg1 withIsTurnedOn:(_Bool)arg2;
- (NSURL *)authURLForAppId:(NSString *)arg1;
- (NSArray *)connectedAppStoryIds;
- (NSArray *)appStatesAppStoriesWithQuery:(SCSearchQuery *)arg1;
- (SCSnapKitAppState *)appStateForApplicationId:(NSString *)arg1;
- (void)didDisconnectAppWithAppId:(NSString *)arg1;
- (void)updateWithProtoConnectResponseFromRemote:(SCSnapKitProtoConnectResponse *)arg1;
@end

