//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSError, SCSnapchattersDataRequest;

@interface SCSnapchattersLoggingData : NSObject <NSCopying>
{
    SCSnapchattersDataRequest *_DataRequest;
    unsigned long long _state;
    NSError *_error;
}

@property(readonly, copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) unsigned long long state; // @synthesize state=_state;
@property(readonly, copy, nonatomic) SCSnapchattersDataRequest *DataRequest; // @synthesize DataRequest=_DataRequest;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDataRequest:(id)arg1 state:(unsigned long long)arg2 error:(id)arg3;

@end

