//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, SCSnapKitPhoneVerificationDataModel;

@protocol SCSnapKitPhoneVerificationVerifyPageDelegate <NSObject>
- (void)verificationCompleted;
- (void)cancelPhoneVerification;
- (void)errorSendingCode:(NSString *)arg1;
- (void)codeSentTo:(NSString *)arg1 using:(unsigned long long)arg2;
- (void)beginPasswordReauthentication:(SCSnapKitPhoneVerificationDataModel *)arg1;
- (void)beginPhoneVerification:(SCSnapKitPhoneVerificationDataModel *)arg1;
@end

