//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSpectaclesEventListener-Protocol.h"
#import "SCSpectaclesHomeWifiManaging-Protocol.h"
#import "SCSpectaclesSsidEventListener-Protocol.h"

@class NSMutableArray, NSString, SCFeatureSettingsService, SCQueuePerformer, SCSpectaclesAuthorizationManager, SCSpectaclesDevice, SCSpectaclesHomeWifiManagerEventListenerAnnouncer, SCUserSession, SCWeakTimer;
@protocol SCSpectaclesAppLogger, SCSpectaclesManaging;

@interface SCSpectaclesHomeWifiManager : NSObject <SCSpectaclesEventListener, SCSpectaclesSsidEventListener, SCSpectaclesHomeWifiManaging>
{
    SCSpectaclesAuthorizationManager *_authorizationManager;
    SCFeatureSettingsService *_featureSettingsService;
    _Bool _specsRefreshTokenInvalid;
    SCUserSession *_userSession;
    id <SCSpectaclesManaging> _spectaclesManager;
    id <SCSpectaclesAppLogger> _analyticsLogger;
    SCSpectaclesHomeWifiManagerEventListenerAnnouncer *_announcer;
    SCQueuePerformer *_performer;
    unsigned long long _state;
    SCSpectaclesDevice *_device;
    NSString *_currentWifiSsid;
    NSMutableArray *_wifiAPList;
    SCWeakTimer *_pendingSnapsNotificationTimer;
}

+ (id)homeWifiStateToString:(unsigned long long)arg1;
@property(retain, nonatomic) SCWeakTimer *pendingSnapsNotificationTimer; // @synthesize pendingSnapsNotificationTimer=_pendingSnapsNotificationTimer;
@property(nonatomic) _Bool specsRefreshTokenInvalid; // @synthesize specsRefreshTokenInvalid=_specsRefreshTokenInvalid;
@property(retain, nonatomic) NSMutableArray *wifiAPList; // @synthesize wifiAPList=_wifiAPList;
@property(copy, nonatomic) NSString *currentWifiSsid; // @synthesize currentWifiSsid=_currentWifiSsid;
@property(retain, nonatomic) SCSpectaclesDevice *device; // @synthesize device=_device;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
@property(retain, nonatomic) SCSpectaclesHomeWifiManagerEventListenerAnnouncer *announcer; // @synthesize announcer=_announcer;
@property(nonatomic) __weak id <SCSpectaclesAppLogger> analyticsLogger; // @synthesize analyticsLogger=_analyticsLogger;
@property(nonatomic) __weak id <SCSpectaclesManaging> spectaclesManager; // @synthesize spectaclesManager=_spectaclesManager;
@property(nonatomic) __weak SCUserSession *userSession; // @synthesize userSession=_userSession;
- (void).cxx_destruct;
- (id)_connectedDevice;
- (void)_pendingSnapsNotificationTimeout:(id)arg1;
- (void)_requestLastCloudUploadTime:(id)arg1;
- (id)_wifiApFromListWithSsid:(id)arg1;
- (void)_transitionToState:(unsigned long long)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)wifiScannerDidUpdateWifiSsid:(id)arg1;
- (void)spectaclesDevice:(id)arg1 didReceiveWifiAPList:(id)arg2;
- (void)spectaclesDevice:(id)arg1 didReceiveShareWifiCredentialsResponseStatus:(unsigned long long)arg2;
- (void)spectaclesDevice:(id)arg1 didReceiveClientId:(id)arg2 requestAuthzCode:(_Bool)arg3;
- (void)spectaclesDevice:(id)arg1 didReceiveCloudUploadEvent:(unsigned long long)arg2;
- (void)spectaclesDeviceDidUpdateState:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (_Bool)currentFlowIsResharingCredentials;
- (_Bool)wifiAPNeedsCredentialsUpdate:(id)arg1;
- (_Bool)hasWifiNetworkRequiringCredentialsUpdate;
- (void)removeWifiNetwork:(id)arg1;
- (void)startShareWifiCredentialsWithSSID:(id)arg1 password:(id)arg2;
- (void)cancelShareWifiCredentials;
- (void)startShareWifiCredentials;
- (id)initWithUserSession:(id)arg1 featureSettingsService:(id)arg2 spectaclesManager:(id)arg3 authorizationManager:(id)arg4 analyticsLogger:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

