//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSpectaclesSearchResultViewController.h"

#import "SCGalleryPreviewControllerDelegate-Protocol.h"
#import "SCLensDataProviderListener-Protocol.h"
#import "SCProgressOverlayViewDelegate-Protocol.h"
#import "UIViewControllerTransitioningDelegate-Protocol.h"

@class NSString, SCGalleryPrepareMediaForSnapsOperation, SCGalleryPreviewController, SCLens, SCProgressOverlayView, SCSpectaclesPrepareDepthForSnapOperation;
@protocol SCLensCameraScreenDataProviderProtocol;

@interface SCSpectaclesLensScanSearchResultViewController : SCSpectaclesSearchResultViewController <SCLensDataProviderListener, UIViewControllerTransitioningDelegate, SCGalleryPreviewControllerDelegate, SCProgressOverlayViewDelegate>
{
    SCLens *_lens;
    NSString *_lensId;
    id <SCLensCameraScreenDataProviderProtocol> _lensDataProvider;
    NSString *_lensDataProviderToken;
    SCProgressOverlayView *_progressOverlayView;
    SCGalleryPrepareMediaForSnapsOperation *_prepareMediaOperation;
    SCSpectaclesPrepareDepthForSnapOperation *_prepareDepthOperation;
    SCGalleryPreviewController *_controller;
}

- (void).cxx_destruct;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)galleryPreviewControllerDidSendOrPostContent;
- (void)galleryPreviewControllerDidSaveAsEdit:(id)arg1;
- (void)galleryPreviewControllerDidSaveAsCopy:(id)arg1;
- (void)galleryPreviewController:(id)arg1 didFailToLoadContent:(id)arg2;
- (void)galleryPreviewControllerDidCancel:(id)arg1;
- (void)galleryPreviewControllerDidDismiss:(id)arg1;
- (void)galleryPreviewControllerWillDismiss:(id)arg1;
- (void)progressOverlayViewDidCancel:(id)arg1;
- (void)_complete;
- (void)_launchPreviewForSnap:(id)arg1 entry:(id)arg2 cloudFile:(id)arg3;
- (void)_downloadDepthForSnap:(id)arg1 entry:(id)arg2 cloudFile:(id)arg3;
- (void)_showProgressView;
- (void)memoriesCollectionViewSelectionHelper:(id)arg1 didTapItemAtIndexPath:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (void)lensDataProvider:(id)arg1 didUpdateLens:(id)arg2 contentUpdateType:(long long)arg3;
- (void)lensDataProvider:(id)arg1 didUpdateAllLenses:(id)arg2 requiresAnimation:(_Bool)arg3;
- (id)_createLensDataProvider;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)headerString;
- (id)titleString;
- (id)initWithLensId:(id)arg1 userSession:(id)arg2 delegate:(id)arg3;
- (id)initWithLens:(id)arg1 userSession:(id)arg2 delegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

