//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSpectaclesTweaksConfigProvider-Protocol.h"

@class NSString;

@interface SCSpectaclesTweaksConfigProvider : NSObject <SCSpectaclesTweaksConfigProvider>
{
}

- (_Bool)enableAutomaticContentWiFiTransfer;
- (long long)automaticContentTransferBatteryThreshold;
- (_Bool)enableAutomaticContentTransferWithBatteryThreshold;
- (_Bool)enableBackgroundContentHdVideoBTCTransfer;
- (_Bool)enableBackgroundContentPictureBTCTransfer;
- (_Bool)skipWiFiSSIDCheckWhenImporting;
- (unsigned long long)mockTemperatureStatus;
- (unsigned long long)mockStorageLevelStatus;
- (unsigned long long)mockBatteryLevelStatus;
- (_Bool)restrictRSSIWhenScanning;
- (_Bool)alwaysShowOnboardingAfterPairing;
- (long long)mockGuppyBatteryLevel;
- (long long)mockCoulombCounterTemperature;
- (long long)mockDeviceBatteryLevel;
- (id)hermosaWhitelistedDeviceName;
- (_Bool)hermosaEnabled;
- (_Bool)gateLowEndDevices;
- (_Bool)disableContentDeletion;
- (id)newportBurstFrame;
- (_Bool)newportEnableBurst;
- (_Bool)enableMultiSnapForNewport;
- (_Bool)enableMultiSnap;
- (_Bool)keepAliveInBackground;
- (_Bool)disableProdAuthentication;
- (_Bool)disableEncryption;
- (_Bool)disableBluetooth;
- (_Bool)setupBleNotifications;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

