//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, SCSpectaclesLookupTable;

@interface SCSpectaclesRectificationConfiguration : NSObject <NSCopying>
{
    unsigned long long _subtype;
    unsigned long long _rectified_camera;
    SCSpectaclesLookupTable *_newportFisheye_lookupTable;
    NSArray *_newportFisheye_stabilization;
}

+ (id)rectifiedWithCamera:(unsigned long long)arg1;
+ (id)newportFisheyeWithLookupTable:(id)arg1 stabilization:(id)arg2;
- (void).cxx_destruct;
- (void)matchRectified:(CDUnknownBlockType)arg1 newportFisheye:(CDUnknownBlockType)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

