//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCSpectaclesDataFlowsRequest-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSString;
@protocol SCSpectaclesDevice;

@interface SCSpectaclesContentTransferRequest : NSObject <SCTraceEnabled, SCSpectaclesDataFlowsRequest>
{
    id <SCSpectaclesDevice> _device;
    long long _transferChannel;
    unsigned long long _startSource;
}

- (void).cxx_destruct;
- (_Bool)_shouldCreateHdVideoTaskFrom:(id)arg1;
- (_Bool)_shouldCreatePictureTaskFrom:(id)arg1;
- (_Bool)_shouldCreateImuDataTaskFrom:(id)arg1;
- (_Bool)_shouldCreateThumbnailTaskFrom:(id)arg1;
- (id)contentIds;
- (_Bool)isAutomaticTransfer;
- (unsigned long long)startSource;
- (id)device;
- (long long)transferChannel;
- (id)createTasksFrom:(id)arg1;
- (id)initWithDevice:(id)arg1 transferChannel:(long long)arg2 startSource:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

