//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SCLensLoggerConsumptionTrackingProviding, SCPerforming, SCPostCaptureLensComponentManagerPool;

@interface SCSpectaclesImageProcessLensCommandFactory : NSObject
{
    id <SCPerforming> _performer;
    id <SCPostCaptureLensComponentManagerPool> _componentManagerPool;
    id <SCLensLoggerConsumptionTrackingProviding> _consumptionLensLogger;
}

- (void).cxx_destruct;
- (id)_videoLensProcessingCommandWithLens:(id)arg1 metadata:(id)arg2 innerProcessAction:(id)arg3;
- (id)stereoVideoLensProcessingCommandWithLens:(id)arg1 serializedDataString:(id)arg2 metadata:(id)arg3;
- (id)imageLensProcessingCommandWithLens:(id)arg1 metadata:(id)arg2;
- (id)videoLensProcessingCommandWithLens:(id)arg1 metadata:(id)arg2;
- (id)initWithComponentManagerPool:(id)arg1 lensLogger:(id)arg2;

@end

