//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSDictionary, NSUUID;
@protocol SCSpectaclesContent, SCSpectaclesDevice;

@interface SCSpectaclesTransferSession : NSObject
{
    float _progress;
    id <SCSpectaclesDevice> _device;
    NSUUID *_batchID;
    NSDate *_sessionStartTime;
    long long _numberOfContentBeingTransferred;
    long long _numberOfContentTransferred;
    long long _channel;
    unsigned long long _transferType;
    NSArray *_transferredContent;
    NSArray *_untransferredContent;
    NSDictionary *_untransferredCountByComponent;
    id <SCSpectaclesContent> _currentlyTransferringContent;
    unsigned long long _component;
}

@property(readonly, nonatomic) float progress; // @synthesize progress=_progress;
@property(readonly, nonatomic) unsigned long long component; // @synthesize component=_component;
@property(readonly, nonatomic) id <SCSpectaclesContent> currentlyTransferringContent; // @synthesize currentlyTransferringContent=_currentlyTransferringContent;
@property(readonly, nonatomic) NSDictionary *untransferredCountByComponent; // @synthesize untransferredCountByComponent=_untransferredCountByComponent;
@property(readonly, nonatomic) NSArray *untransferredContent; // @synthesize untransferredContent=_untransferredContent;
@property(readonly, nonatomic) NSArray *transferredContent; // @synthesize transferredContent=_transferredContent;
@property(readonly, nonatomic) unsigned long long transferType; // @synthesize transferType=_transferType;
@property(readonly, nonatomic) long long channel; // @synthesize channel=_channel;
@property(readonly, nonatomic) long long numberOfContentTransferred; // @synthesize numberOfContentTransferred=_numberOfContentTransferred;
@property(readonly, nonatomic) long long numberOfContentBeingTransferred; // @synthesize numberOfContentBeingTransferred=_numberOfContentBeingTransferred;
@property(readonly, nonatomic) NSDate *sessionStartTime; // @synthesize sessionStartTime=_sessionStartTime;
@property(readonly, nonatomic) NSUUID *batchID; // @synthesize batchID=_batchID;
@property(readonly, nonatomic) id <SCSpectaclesDevice> device; // @synthesize device=_device;
- (void).cxx_destruct;
- (id)copy;
- (id)initWithTransferSession:(id)arg1;

@end

