//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

#import "SCSpectaclesOnboardingViewControllerDelegate-Protocol.h"

@class NSString, SCSpectaclesDependenciesService, SCSpectaclesOnboardingScope, SCSpectaclesServices;

@interface SCSpectaclesOnboardingEntryPoint : SCEntryPoint <SCSpectaclesOnboardingViewControllerDelegate>
{
    SCSpectaclesDependenciesService *_dependenciesService;
    SCSpectaclesServices *_spectaclesServices;
    SCSpectaclesOnboardingScope *_onboardingScope;
}

@property(nonatomic) __weak SCSpectaclesOnboardingScope *onboardingScope; // @synthesize onboardingScope=_onboardingScope;
@property(nonatomic) __weak SCSpectaclesServices *spectaclesServices; // @synthesize spectaclesServices=_spectaclesServices;
@property(nonatomic) __weak SCSpectaclesDependenciesService *dependenciesService; // @synthesize dependenciesService=_dependenciesService;
- (void).cxx_destruct;
- (void)spectaclesOnboardingViewControllerWillDismiss:(id)arg1;
- (id)end;
- (void)begin;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

