//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSError, SCSpectaclesGenericDataChannel;

@protocol SCSpectaclesGenericDataChannelDelegate <NSObject>
- (void)channelDidClose:(SCSpectaclesGenericDataChannel *)arg1;
- (void)channel:(SCSpectaclesGenericDataChannel *)arg1 didError:(NSError *)arg2;
- (void)channelDidWriteData:(SCSpectaclesGenericDataChannel *)arg1;
- (void)channel:(SCSpectaclesGenericDataChannel *)arg1 didReadData:(NSData *)arg2;
- (void)channelDidOpen:(SCSpectaclesGenericDataChannel *)arg1;
@end

