//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, SCSpectaclesHDTransferSessionInfo;
@protocol SCSpectaclesDevice, SCUserTooltipStatusProviding;

@protocol SCSpectaclesAppWifiTransferInitiating <NSObject>
- (void)initiateTransferForHDContentIds:(NSArray *)arg1 tooltipsStatusProvider:(id <SCUserTooltipStatusProviding>)arg2 device:(id <SCSpectaclesDevice>)arg3 startSource:(unsigned long long)arg4 useAutomaticTransferMode:(_Bool)arg5;
- (void)initiateTransferForAllUntransferredHDContentWithTooltipsStatusProvider:(id <SCUserTooltipStatusProviding>)arg1 device:(id <SCSpectaclesDevice>)arg2 startSource:(unsigned long long)arg3 useAutomaticTransferMode:(_Bool)arg4;
- (SCSpectaclesHDTransferSessionInfo *)getCurrentHdSessionAnalyticsInfo;
@end

