//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CBPeripheralDelegate-Protocol.h"
#import "SCSpectaclesCommunicationChannel-Protocol.h"

@class CBPeripheral, CBUUID, NSMutableData, NSNumber, NSString;
@protocol SCSpectaclesCommunicationChannelDelegate;

@interface SCSpectaclesBLEChannel : NSObject <CBPeripheralDelegate, SCSpectaclesCommunicationChannel>
{
    CBPeripheral *_peripheral;
    CBUUID *_serviceUUID;
    CBUUID *_txCharacteristicUUID;
    CBUUID *_rxCharacteristicUUID;
    NSMutableData *_writeBuffer;
    _Bool _hasSpaceAvailable;
    _Bool _isOpen;
    id <SCSpectaclesCommunicationChannelDelegate> _delegate;
    unsigned long long _options;
    unsigned long long _reachabilityStatus;
}

@property(readonly, nonatomic) unsigned long long reachabilityStatus; // @synthesize reachabilityStatus=_reachabilityStatus;
@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(readonly, nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(nonatomic) __weak id <SCSpectaclesCommunicationChannelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)peripheral:(id)arg1 didReadRSSI:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)_sendGenericError;
- (void)_writeNextPacket;
@property(readonly, copy) NSString *description;
- (void)stopMonitorReachability;
- (void)close;
- (void)writeData:(id)arg1;
- (void)open;
- (void)monitorReachability;
@property(readonly, nonatomic) _Bool isMonitoringReachability;
- (id)initWithPeripheral:(id)arg1 serviceUUID:(id)arg2 txCharacteristicUUID:(id)arg3 rxCharacteristicUUID:(id)arg4 delegate:(id)arg5;

// Remaining properties
@property(readonly, nonatomic) NSNumber *RSSI;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

