//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SCSpectaclesDeviceConnectionState <NSObject>
- (_Bool)isActive;
- (_Bool)isUnpaired;
- (_Bool)tryingToConnectWiFi;
- (_Bool)tryingToConnectBTForContentTransfer;
- (_Bool)tryingToConnectBTDeviceRecording;
- (_Bool)tryingToConnectBT;
- (_Bool)connectedOverWiFi;
- (_Bool)connectedOverBT;
- (_Bool)connectedOverBLE;
- (_Bool)connectedOverBTOrWiFi;
- (_Bool)connectedOverBLEOrWiFi;
@end

