//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString, SCSCOREHNNewsCategory, SCSSMHNNewsWeatherMetadata;

@interface SCSSMPublisherHNNewsMetadata : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCSCOREHNNewsCategory *category; // @dynamic category;
@property(nonatomic) _Bool hasCategory; // @dynamic hasCategory;
@property(nonatomic) _Bool hasHnNewsWeatherMetadata; // @dynamic hasHnNewsWeatherMetadata;
@property(retain, nonatomic) SCSSMHNNewsWeatherMetadata *hnNewsWeatherMetadata; // @dynamic hnNewsWeatherMetadata;
@property(nonatomic) _Bool isBitmojiWeather; // @dynamic isBitmojiWeather;
@property(nonatomic) _Bool isBreakingNews; // @dynamic isBreakingNews;
@property(copy, nonatomic) NSString *ringColor; // @dynamic ringColor;

@end

