//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCCORECompositeStoryId, SCSSMStoryLookupRequestItem_DeltaFetchInfo, SCSSMStoryLookupRequestItem_EnvironmentInfo;

@interface SCSSMStoryLookupRequestItem : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCCORECompositeStoryId *compositeStoryId; // @dynamic compositeStoryId;
@property(retain, nonatomic) SCSSMStoryLookupRequestItem_DeltaFetchInfo *deltaFetchInfo; // @dynamic deltaFetchInfo;
@property(retain, nonatomic) SCSSMStoryLookupRequestItem_EnvironmentInfo *environmentInfo; // @dynamic environmentInfo;
@property(nonatomic) _Bool hasCompositeStoryId; // @dynamic hasCompositeStoryId;
@property(nonatomic) _Bool hasDeltaFetchInfo; // @dynamic hasDeltaFetchInfo;
@property(nonatomic) _Bool hasEnvironmentInfo; // @dynamic hasEnvironmentInfo;

@end

