//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCStickerChatHometabLayoutExperimentContext : SCExperimentContext
{
    _Bool _isChatHomeTabEnabled;
    _Bool _isStickerCategoryHeaderCellSeeAllButtonEnabled;
    _Bool _isStickerCategoryEndOfSectionSeeAllButtonEnabled;
    _Bool _isChatHomeTabHorizontalScrolling;
    _Bool _shouldChatHomeTabOpenMaximized;
    long long _chatHomeTabBackfillMax;
    long long _chatHomeTabRecentsBackfillMax;
}

@property(readonly, nonatomic) _Bool shouldChatHomeTabOpenMaximized; // @synthesize shouldChatHomeTabOpenMaximized=_shouldChatHomeTabOpenMaximized;
@property(readonly, nonatomic) _Bool isChatHomeTabHorizontalScrolling; // @synthesize isChatHomeTabHorizontalScrolling=_isChatHomeTabHorizontalScrolling;
@property(readonly, nonatomic) _Bool isStickerCategoryEndOfSectionSeeAllButtonEnabled; // @synthesize isStickerCategoryEndOfSectionSeeAllButtonEnabled=_isStickerCategoryEndOfSectionSeeAllButtonEnabled;
@property(readonly, nonatomic) _Bool isStickerCategoryHeaderCellSeeAllButtonEnabled; // @synthesize isStickerCategoryHeaderCellSeeAllButtonEnabled=_isStickerCategoryHeaderCellSeeAllButtonEnabled;
@property(readonly, nonatomic) long long chatHomeTabRecentsBackfillMax; // @synthesize chatHomeTabRecentsBackfillMax=_chatHomeTabRecentsBackfillMax;
@property(readonly, nonatomic) long long chatHomeTabBackfillMax; // @synthesize chatHomeTabBackfillMax=_chatHomeTabBackfillMax;
@property(readonly, nonatomic) _Bool isChatHomeTabEnabled; // @synthesize isChatHomeTabEnabled=_isChatHomeTabEnabled;
- (void)setupParameters;
- (id)experimentName;

@end

