//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "SCTCKAudioServices-Protocol.h"

@class AVAudioSessionRouteDescription, NSMutableSet, NSString, SCAppNotification, SCAudioRoute;

@protocol SCTAudioServices <NSObject, SCTCKAudioServices>
- (void)stopRingingInConvoId:(NSString *)arg1;
- (void)startRingingInConvoId:(NSString *)arg1 incoming:(_Bool)arg2;
- (void)unlockRingingWithToken:(id)arg1;
- (id)lockRingingWithLabel:(NSString *)arg1;
- (_Bool)shouldIgnoreVolumeChanges;
- (void)playSound:(unsigned long long)arg1;
- (void)processConvoId:(NSString *)arg1 visibilityChanged:(_Bool)arg2;
- (void)processIncomingCallNotificationRemoved:(SCAppNotification *)arg1;
- (void)processIncomingCallNotificationShown:(SCAppNotification *)arg1;
- (AVAudioSessionRouteDescription *)currentAudioRoute;
- (NSMutableSet *)availableRoutes;
- (_Bool)applyAudioRoute:(SCAudioRoute *)arg1;
- (void)updateProximityMonitoring:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)updateAudioSessionConfiguration:(unsigned long long)arg1 isForCallKit:(_Bool)arg2 completion:(void (^)(void))arg3;
- (void)updateAudioSessionConfiguration:(unsigned long long)arg1 proximitySensor:(_Bool)arg2 completion:(void (^)(void))arg3;
@end

