//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCLazy;
@protocol SCLensByIdRetrievable, SCLensDataFetcherFactory, SCLensIconRepository, SCLoggerAmplitudeProtocol, SCUcoCarouselConfigProviding, SCUcoDataStore, SCUcoFiltersAvailability, SCUcoLogger, SCUcoPerformanceLogger, SCUcoStudySettingsProvider, SCUcoUnlockablesController, SCUcoViewModelGenerator, SCUnifiedCameraObjectDataFetching;

@protocol SCUcoDependencyFactory <NSObject>
- (_Bool)ucoFeatureEnabled;
- (id <SCUcoPerformanceLogger>)performanceLoggerWithGraphene:(SCLazy *)arg1 ucoDataStore:(id <SCUcoDataStore>)arg2 ucoFiltersAvailability:(id <SCUcoFiltersAvailability>)arg3;
- (id <SCUcoStudySettingsProvider>)studySettingsProvider;
- (id <SCUcoDataStore>)ucoDataStoreWithUnlockablesController:(id <SCUcoUnlockablesController>)arg1;
- (id <SCUcoLogger>)ucoLoggerWithBlizzardLogger:(id <SCLoggerAmplitudeProtocol>)arg1;
- (id <SCUcoViewModelGenerator>)createUcoViewModelGeneratorWithLensByIdRetrievable:(id <SCLensByIdRetrievable>)arg1 lensIconRepository:(id <SCLensIconRepository>)arg2 ucoCarouselConfigProvider:(id <SCUcoCarouselConfigProviding>)arg3;
- (id <SCUnifiedCameraObjectDataFetching>)createUcoDataFetcherWithLazyStoreTuple:(SCLazy *)arg1 lensDataFetcherFactory:(id <SCLensDataFetcherFactory>)arg2 fromGallery:(_Bool)arg3;
@end

