//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCUcoDependencyFactory-Protocol.h"

@class NSString, SCLazy;
@protocol SCUcoStudySettingsProvider;

@interface SCUcoDependencyFactory : NSObject <SCUcoDependencyFactory>
{
    SCLazy *_experimentManager;
    id <SCUcoStudySettingsProvider> _studySettingsProvider;
}

+ (id)defaultFactory;
- (void).cxx_destruct;
- (_Bool)ucoFeatureEnabled;
- (id)performanceLoggerWithGraphene:(id)arg1 ucoDataStore:(id)arg2 ucoFiltersAvailability:(id)arg3;
- (id)ucoDataStoreWithUnlockablesController:(id)arg1;
- (id)ucoLoggerWithBlizzardLogger:(id)arg1;
- (id)createUcoViewModelGeneratorWithLensByIdRetrievable:(id)arg1 lensIconRepository:(id)arg2 ucoCarouselConfigProvider:(id)arg3;
- (id)createUcoDataFetcherWithLazyStoreTuple:(id)arg1 lensDataFetcherFactory:(id)arg2 fromGallery:(_Bool)arg3;
- (id)initWithExperimentManager:(id)arg1;
@property(retain, nonatomic) id <SCUcoStudySettingsProvider> studySettingsProvider;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

