//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOverlayFilterView.h"

@class SCSingleLensCommandUcoStateProvider, UIView;
@protocol SCUcoInfoView;

@interface SCUnifiedCameraObjectFilterView : SCOverlayFilterView
{
    UIView<SCUcoInfoView> *_ucoInfoView;
    SCSingleLensCommandUcoStateProvider *_singleLensCommandUcoStateProvider;
}

- (void).cxx_destruct;
- (_Bool)hasImage;
- (void)_startLoadingLensCommand:(id)arg1;
- (void)updateImageProcessCommands:(id)arg1;
- (void)startViewing;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2 filterCarouselGroupName:(id)arg3 ucoViewModelGenerator:(id)arg4;

@end

