//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCObservable;

@interface SCUserInfoProvider : NSObject
{
    id _currentValue;
    SCObservable *_updates;
}

@property(readonly, nonatomic) SCObservable *updates; // @synthesize updates=_updates;
@property(readonly, nonatomic) id currentValue; // @synthesize currentValue=_currentValue;
- (void).cxx_destruct;

@end

