//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEntryPoint.h"

@class SCConversationServices, SCConversationVersionTracker, SCEntryPointCleanup, SCFeatureSettingsServices, SCFriendsFeedServices, SCNotificationBadgeCountObservableRepository, SCNotificationBadgeUpdater, SCNotificationBestFriendsSoundRepository, SCNotificationConsumableConversationIdsRepository, SCNotificationUnviewedIncomingFriendsRepository, SCReceivedSnapPersister, SCSnapchatterServices, SCUserSessionScope;

@interface SCUserNotificationsEntryPoint : SCEntryPoint
{
    SCNotificationBadgeUpdater *_badgeUpdater;
    SCNotificationBadgeCountObservableRepository *_badgeCountObservableRepository;
    SCConversationVersionTracker *_tracker;
    SCNotificationConsumableConversationIdsRepository *_consumableIdsRepository;
    SCNotificationBestFriendsSoundRepository *_bestFriendsSoundRepository;
    SCNotificationUnviewedIncomingFriendsRepository *_unviewedIncomingFriendsRepository;
    SCEntryPointCleanup *_cleanup;
    SCReceivedSnapPersister *_receivedSnapReceiver;
    SCUserSessionScope *_userSessionScope;
    SCFriendsFeedServices *_friendsFeedServices;
    SCSnapchatterServices *_snapchatterServices;
    SCConversationServices *_conversationServices;
    SCFeatureSettingsServices *_featureSettingsServices;
}

@property(nonatomic) __weak SCFeatureSettingsServices *featureSettingsServices; // @synthesize featureSettingsServices=_featureSettingsServices;
@property(nonatomic) __weak SCConversationServices *conversationServices; // @synthesize conversationServices=_conversationServices;
@property(nonatomic) __weak SCSnapchatterServices *snapchatterServices; // @synthesize snapchatterServices=_snapchatterServices;
@property(nonatomic) __weak SCFriendsFeedServices *friendsFeedServices; // @synthesize friendsFeedServices=_friendsFeedServices;
@property(nonatomic) __weak SCUserSessionScope *userSessionScope; // @synthesize userSessionScope=_userSessionScope;
- (void).cxx_destruct;
- (void)_persistSettingsForExtensions;
- (id)end;
- (void)_initializeObjectsAndData;
- (void)begin;

@end

