//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLogoutInterceptor-Protocol.h"
#import "SCSettingsDelegate-Protocol.h"

@class NSString, SCExperimentManager, SCFeatureSettingsService, SCLazy, SCLogoutVerificationLogger;
@protocol SCLogoutInterceptorCoolDownService, SCUIContainer;

@interface SCVerificationLogoutInterceptor : NSObject <SCLogoutInterceptor, SCSettingsDelegate>
{
    id <SCUIContainer> _navigationContainer;
    SCLazy *_verificationUI;
    SCFeatureSettingsService *_featureSettingsService;
    long long _previousViewCount;
    SCLogoutVerificationLogger *_logger;
    CDUnknownBlockType _alert;
    CDUnknownBlockType _completion;
    _Bool _enabled;
    NSString *_sessionUUID;
    SCExperimentManager *_experimentManager;
    id <SCLogoutInterceptorCoolDownService> _coolDownService;
}

- (void).cxx_destruct;
- (void)_verificationAlertDeclinedWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)settingFinished;
- (void)_initCoolDownService;
- (void)_promptWithCompletionBlock:(CDUnknownBlockType)arg1 uiContainer:(id)arg2;
- (void)_verificationAlertConfirmedWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_showAlertInContainer:(id)arg1 confirmCallback:(CDUnknownBlockType)arg2 declineCallback:(CDUnknownBlockType)arg3;
- (void)interceptLogoutWithCompletionBlock:(CDUnknownBlockType)arg1 uiContainer:(id)arg2;
- (void)setPreviousViewCount:(long long)arg1;
- (id)initWithNavigationContainer:(id)arg1 verificationUI:(id)arg2 featureSettingsService:(id)arg3 enabled:(_Bool)arg4 logger:(id)arg5 alert:(CDUnknownBlockType)arg6 preferences:(id)arg7 experimentManager:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

