//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GRPCProtoCall, GRXWriter, SCVSClientUpdateRequest, SCVSGetFriendClustersRequest, SCVSGetPreferencesRequest, SCVSSetPreferencesRequest;

@protocol SCVSValis <NSObject>
- (GRPCProtoCall *)RPCToGetFriendClustersWithRequest:(SCVSGetFriendClustersRequest *)arg1 handler:(void (^)(SCVSGetFriendClustersResponse *, NSError *))arg2;
- (void)getFriendClustersWithRequest:(SCVSGetFriendClustersRequest *)arg1 handler:(void (^)(SCVSGetFriendClustersResponse *, NSError *))arg2;
- (GRPCProtoCall *)RPCToSendClientUpdateWithRequest:(SCVSClientUpdateRequest *)arg1 handler:(void (^)(SCVSClientUpdateResponse *, NSError *))arg2;
- (void)sendClientUpdateWithRequest:(SCVSClientUpdateRequest *)arg1 handler:(void (^)(SCVSClientUpdateResponse *, NSError *))arg2;
- (GRPCProtoCall *)RPCToCommunicateWithRequestsWriter:(GRXWriter *)arg1 eventHandler:(void (^)(_Bool, SCVSServerUpdate *, NSError *))arg2;
- (void)communicateWithRequestsWriter:(GRXWriter *)arg1 eventHandler:(void (^)(_Bool, SCVSServerUpdate *, NSError *))arg2;
- (GRPCProtoCall *)RPCToSetPreferencesWithRequest:(SCVSSetPreferencesRequest *)arg1 handler:(void (^)(SCVSSetPreferencesResponse *, NSError *))arg2;
- (void)setPreferencesWithRequest:(SCVSSetPreferencesRequest *)arg1 handler:(void (^)(SCVSSetPreferencesResponse *, NSError *))arg2;
- (GRPCProtoCall *)RPCToGetPreferencesWithRequest:(SCVSGetPreferencesRequest *)arg1 handler:(void (^)(SCVSGetPreferencesResponse *, NSError *))arg2;
- (void)getPreferencesWithRequest:(SCVSGetPreferencesRequest *)arg1 handler:(void (^)(SCVSGetPreferencesResponse *, NSError *))arg2;
@end

