//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCWebProxyRequest;
@protocol SCCanceling, SCWebProxyURLProviding;

@protocol SCWebProxyRequestHandling <NSObject>
- (id <SCCanceling>)handleStreamingProxyRequest:(SCWebProxyRequest *)arg1 urlProvider:(id <SCWebProxyURLProviding>)arg2 updateBlock:(void (^)(NSError *, NSDictionary *, long long, NSData *))arg3;
- (id <SCCanceling>)handleProxyRequest:(SCWebProxyRequest *)arg1 urlProvider:(id <SCWebProxyURLProviding>)arg2 completion:(void (^)(NSError *, SCWebProxyResponse *))arg3;
@end

