//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSData, NSMutableDictionary, NSString;

@interface SDMAppInstall_AppInfo : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(copy, nonatomic) NSString *appIcon; // @dynamic appIcon;
@property(copy, nonatomic) NSString *appId; // @dynamic appId;
@property(copy, nonatomic) NSData *contentObject; // @dynamic contentObject;
@property(retain, nonatomic) NSMutableDictionary *storeParams; // @dynamic storeParams;
@property(readonly, nonatomic) unsigned long long storeParams_Count; // @dynamic storeParams_Count;

@end

