//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SIGDampedHarmonicSpring : NSObject
{
    double _mass;
    double _stiffness;
    double _dampingCoefficient;
}

- (double)relativeVelocityForVelocity:(double)arg1 from:(inout double)arg2 to:(double)arg3 epsilon:(double)arg4;
- (id)timingFunctionWithInitialVelocity:(struct CGVector)arg1 from:(inout struct CGPoint)arg2 to:(struct CGPoint)arg3 context:(id)arg4;
- (id)timingFunctionWithInitialFloatVelocity:(double)arg1 from:(inout double)arg2 to:(double)arg3 context:(id)arg4;
- (id)timingFunctionWithInitialVelocity:(double)arg1 from:(inout double)arg2 to:(double)arg3;
- (id)timingFunctionWithRelativeInitialFloatVelocity:(double)arg1;
- (id)timingFunctionWithRelativeInitialVelocity:(struct CGVector)arg1;
- (double)maximumDisplacementFromEquilibrium:(double)arg1;
- (double)positionAtTime:(double)arg1 initialPosition:(double)arg2 initialVelocity:(double)arg3;
- (double)dampedNaturalFrequency;
- (double)undampedNaturalFrequency;
- (double)frequencyResponse;
- (double)dampingRatio;
- (id)initWithDampingRatio:(double)arg1 frequencyResponse:(double)arg2;
- (id)initWithMass:(double)arg1 stiffness:(double)arg2 dampingCoefficient:(double)arg3;

@end

