//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, SIGHeaderItemTextInputTraits, UIScrollView, UIView, UIViewController;
@protocol SIGHeaderItemDelegate, SIGTextFieldPillDelegate, UITextFieldDelegate;

@interface SIGHeaderItem : NSObject
{
    _Bool _titleEditable;
    _Bool _titleCollapsesWhenScrolled;
    _Bool _titleAlwaysCollapsed;
    _Bool _searchFieldVisible;
    _Bool _showsSectionTitle;
    unsigned long long _style;
    id <SIGHeaderItemDelegate> _delegate;
    unsigned long long _dismissalAction;
    UIView *_customLeadingAccessoryView;
    UIView *_trailingAccessoryView;
    NSString *_title;
    NSString *_editableTitlePlaceholderText;
    long long _titleTextAlignment;
    UIScrollView *_scrollView;
    NSString *_subtitle;
    id <UITextFieldDelegate> _searchFieldDelegate;
    SIGHeaderItemTextInputTraits *_searchFieldTextInputTraits;
    id <SIGTextFieldPillDelegate> _pillsDelegate;
    UIView *_searchFieldLeadingView;
    UIView *_searchFieldTrailingView;
    NSArray *_tabBarItems;
    UIViewController *_viewController;
}

@property(nonatomic) __weak UIViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) _Bool showsSectionTitle; // @synthesize showsSectionTitle=_showsSectionTitle;
@property(copy, nonatomic) NSArray *tabBarItems; // @synthesize tabBarItems=_tabBarItems;
@property(retain, nonatomic) UIView *searchFieldTrailingView; // @synthesize searchFieldTrailingView=_searchFieldTrailingView;
@property(retain, nonatomic) UIView *searchFieldLeadingView; // @synthesize searchFieldLeadingView=_searchFieldLeadingView;
@property(nonatomic) __weak id <SIGTextFieldPillDelegate> pillsDelegate; // @synthesize pillsDelegate=_pillsDelegate;
@property(readonly, nonatomic) SIGHeaderItemTextInputTraits *searchFieldTextInputTraits; // @synthesize searchFieldTextInputTraits=_searchFieldTextInputTraits;
@property(nonatomic) __weak id <UITextFieldDelegate> searchFieldDelegate; // @synthesize searchFieldDelegate=_searchFieldDelegate;
@property(nonatomic, getter=isSearchFieldVisible) _Bool searchFieldVisible; // @synthesize searchFieldVisible=_searchFieldVisible;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic, getter=isTitleAlwaysCollapsed) _Bool titleAlwaysCollapsed; // @synthesize titleAlwaysCollapsed=_titleAlwaysCollapsed;
@property(nonatomic, getter=doesTitleCollapseWhenScrolled) _Bool titleCollapsesWhenScrolled; // @synthesize titleCollapsesWhenScrolled=_titleCollapsesWhenScrolled;
@property(nonatomic) long long titleTextAlignment; // @synthesize titleTextAlignment=_titleTextAlignment;
@property(retain, nonatomic) NSString *editableTitlePlaceholderText; // @synthesize editableTitlePlaceholderText=_editableTitlePlaceholderText;
@property(nonatomic, getter=isTitleEditable) _Bool titleEditable; // @synthesize titleEditable=_titleEditable;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *trailingAccessoryView; // @synthesize trailingAccessoryView=_trailingAccessoryView;
@property(retain, nonatomic) UIView *customLeadingAccessoryView; // @synthesize customLeadingAccessoryView=_customLeadingAccessoryView;
@property(nonatomic) unsigned long long dismissalAction; // @synthesize dismissalAction=_dismissalAction;
@property(nonatomic) __weak id <SIGHeaderItemDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (id)init;

@end

