//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface SIGNavigationBarButtonItem : NSObject
{
    _Bool _showBadgeCount;
    NSString *_title;
    UIImage *_image;
    UIImage *_highlightImage;
    unsigned long long _highlightTintColor;
    unsigned long long _highlightLabelColor;
    long long _badgeCount;
    NSString *_accessibilityIdentifier;
    id _target;
    SEL _selector;
}

+ (id)navigationBarButtonItemWithImage:(id)arg1 highlightImage:(id)arg2 highlightTintColor:(unsigned long long)arg3 highlightLabelColor:(unsigned long long)arg4 title:(id)arg5 target:(id)arg6 selector:(SEL)arg7;
@property(readonly, nonatomic) SEL selector; // @synthesize selector=_selector;
@property(readonly, nonatomic) __weak id target; // @synthesize target=_target;
@property(copy, nonatomic) NSString *accessibilityIdentifier; // @synthesize accessibilityIdentifier=_accessibilityIdentifier;
@property(nonatomic) _Bool showBadgeCount; // @synthesize showBadgeCount=_showBadgeCount;
@property(nonatomic) long long badgeCount; // @synthesize badgeCount=_badgeCount;
@property(readonly, nonatomic) unsigned long long highlightLabelColor; // @synthesize highlightLabelColor=_highlightLabelColor;
@property(readonly, nonatomic) unsigned long long highlightTintColor; // @synthesize highlightTintColor=_highlightTintColor;
@property(readonly, nonatomic) UIImage *highlightImage; // @synthesize highlightImage=_highlightImage;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithImage:(id)arg1 highlightImage:(id)arg2 highlightTintColor:(unsigned long long)arg3 highlightLabelColor:(unsigned long long)arg4 title:(id)arg5 target:(id)arg6 selector:(SEL)arg7;

@end

