//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"
#import "SIGPresentationContext-Protocol.h"
#import "SIGPresentationContextInternal-Protocol.h"

@class NSMutableArray, NSString, UIView;

@interface SIGPresentationContextImplementation : NSObject <SIGPresentationContext, SIGPresentationContextInternal, SCTraceEnabled>
{
    UIView *_containerView;
    UIView *_newView;
    UIView *_oldView;
    struct CGRect _targetRect;
    long long _footerAnimationStyle;
    long long _headerAnimationStyle;
    NSMutableArray *_setupBlocks;
    NSMutableArray *_animationBlocks;
    NSMutableArray *_completionBlocks;
}

- (void).cxx_destruct;
- (void)triggerCompletionBlocks:(id)arg1 complete:(_Bool)arg2;
- (void)triggerAnimationBlocks:(id)arg1;
- (void)triggerSetupBlocks:(id)arg1;
- (void)addCompletion:(CDUnknownBlockType)arg1;
- (void)addAnimation:(CDUnknownBlockType)arg1;
- (void)addSetup:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) long long headerAnimationStyle;
@property(readonly, nonatomic) long long footerAnimationStyle;
@property(readonly, nonatomic) struct CGRect targetRect;
@property(readonly, nonatomic) __weak UIView *oldView;
@property(readonly, nonatomic) __weak UIView *newView;
@property(readonly, nonatomic) __weak UIView *containerView;
- (id)initWithContainerView:(id)arg1 newView:(id)arg2 oldView:(id)arg3 targetRect:(struct CGRect)arg4 style:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

