//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOrderedSet, SCDisposableObserverLifecycle, SCScriptIndexer;
@protocol OS_dispatch_queue;

@interface SIGSectionFastIndexer : NSObject
{
    NSOrderedSet *_alphabeticalIndexes;
    NSOrderedSet *_precedingSections;
    NSOrderedSet *_subsequentSections;
    CDUnknownBlockType _indexKeyToSectionMapper;
    NSObject<OS_dispatch_queue> *_lock;
    SCScriptIndexer *_scriptIndexer;
    SCDisposableObserverLifecycle *_subscription;
}

- (void).cxx_destruct;
- (void)_onNextSortedEntities:(id)arg1;
- (id)rowBasedIndexPathForKey:(id)arg1;
- (id)sectionBasedIndexPathForKey:(id)arg1;
- (id)initWithIndexEntityObservableRepository:(id)arg1 alphabeticalIndexes:(id)arg2 precedingSections:(id)arg3 subsequentSections:(id)arg4 indexKeyToSectionMapper:(CDUnknownBlockType)arg5;

@end

