//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SIGScrollViewKeyValueObserverDelegate-Protocol.h"

@class NSLayoutConstraint, SIGHeader, SIGScrollViewKeyValueObserver, SIGSubscreenViewControllerContentFade, UIScrollView;

@interface SIGSubscreenView : UIView <SIGScrollViewKeyValueObserverDelegate>
{
    SIGHeader *_header;
    UIScrollView *_scrollView;
    SIGScrollViewKeyValueObserver *_observer;
    UIView *_backgroundView;
    UIView *_contentView;
    SIGSubscreenViewControllerContentFade *_fade;
    NSLayoutConstraint *_fadeTopAnchor;
    _Bool _updatingInsets;
    struct UIEdgeInsets _additionalContentInsets;
    NSLayoutConstraint *_contentViewTopAnchor;
    _Bool _scrollBehaviorSuppressed;
    unsigned long long _style;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(readonly, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) SIGHeader *header; // @synthesize header=_header;
@property(nonatomic, getter=isScrollBehaviorSupressed) _Bool scrollBehaviorSuppressed; // @synthesize scrollBehaviorSuppressed=_scrollBehaviorSuppressed;
@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)updateScrollViewInsets;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)_scrollViewBeingPanned;
- (void)_stylize;
- (id)scrollViewBottomAnchor;
- (id)scrollViewTopAnchor;
- (void)safeAreaInsetsDidChange;
- (id)initWithScrollView:(id)arg1;
- (void)updateContentViewConstraintsRelativeToSectionHeader:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

