//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIControl;
@protocol SIGTextFieldRightViewDelegate;

@interface SIGTextFieldRightView : UIView
{
    NSString *_textFieldText;
    long long _clearButtonMode;
    UIControl *_clearButton;
    UIView *_accessoryView;
    id <SIGTextFieldRightViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SIGTextFieldRightViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(readonly, nonatomic) UIControl *clearButton; // @synthesize clearButton=_clearButton;
@property(nonatomic) long long clearButtonMode; // @synthesize clearButtonMode=_clearButtonMode;
- (void).cxx_destruct;
- (void)updateStateWithText:(id)arg1;
- (void)_assertValidOptions;
- (long long)_impliedRightViewMode;
- (id)initWithFrame:(struct CGRect)arg1;

@end

