//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSNumber, NSString;

@protocol SOJUIdentityMischiefParticipant <SCSojuMessage>
@property(readonly, nonatomic) NSString *colorHex;
@property(readonly, nonatomic) NSString *bitmojiSnapcodeSelfieId;
@property(readonly, nonatomic) NSString *bitmojiSelfieId;
@property(readonly, nonatomic) NSString *bitmojiAvatarId;
@property(readonly, nonatomic) NSNumber *mischiefVersion;
@property(readonly, nonatomic) NSNumber *videoChatUserId;
@property(readonly, nonatomic) NSNumber *joinTimestamp;
@property(readonly, nonatomic) NSString *color;
@property(readonly, nonatomic) NSString *display;
@property(readonly, nonatomic) NSString *username;
@property(readonly, nonatomic) NSString *userId;
@end

