//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSNumber, NSString;

@protocol SOJUVenue <SCSojuMessage>
@property(readonly, nonatomic) NSString *superCategory;
@property(readonly, nonatomic) NSString *iconUrl;
@property(readonly, nonatomic) NSArray *categories;
@property(readonly, nonatomic) NSString *venueName;
@property(readonly, nonatomic) NSNumber *isExtra;
@property(readonly, nonatomic) NSString *matchingGeofilterId;
@property(readonly, nonatomic) NSNumber *splitByServer;
@property(readonly, nonatomic) NSString *subtitle;
@property(readonly, nonatomic) NSString *filterId;
@property(readonly, nonatomic) NSString *locality;
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) NSString *venueId;
@end

