//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSNumber, NSString, SOJUBroadcastMobsModelMobStoryTypeExtraData;

@protocol SOJUBroadcastMobsModelMobStory <SCSojuMessage>
@property(readonly, nonatomic) NSArray *usersWithAbilities;
@property(readonly, nonatomic) NSString *typeVal;
@property(readonly, nonatomic) NSString *creatorDisplayName;
@property(readonly, nonatomic) NSString *creatorUsername;
@property(readonly, nonatomic) NSNumber *createTimestamp;
@property(readonly, nonatomic) NSString *subText;
@property(readonly, nonatomic) NSString *displayName;
@property(readonly, nonatomic) SOJUBroadcastMobsModelMobStoryTypeExtraData *typeExtraData;
@property(readonly, nonatomic) NSString *creatorId;
@property(readonly, nonatomic) NSString *idValue;
@end

