//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSNumber, NSString;

@protocol SOJUSecurityFideliusDeviceRecipientInfo <SCSojuMessage>
@property(readonly, nonatomic) NSNumber *recipientVersion;
@property(readonly, nonatomic) NSString *recipientUserId;
@property(readonly, nonatomic) NSString *senderUserId;
@property(readonly, nonatomic) NSString *recipientOutDeltaCheck;
@property(readonly, nonatomic) NSString *recipientOutDelta;
@property(readonly, nonatomic) NSString *tag;
@property(readonly, nonatomic) NSString *phi;
@property(readonly, nonatomic) NSString *na;
@property(readonly, nonatomic) NSNumber *counter;
@property(readonly, nonatomic) NSString *senderOutDeltaCheck;
@property(readonly, nonatomic) NSString *senderOutDelta;
@end

