//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUCommerceStorePolicy-Protocol.h"

@class NSString;

@interface SOJUCommerceStorePolicy : SCSojuMessage <SOJUCommerceStorePolicy>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithReturnPolicyUrl:(id)arg1 returnPolicyUrlLabel:(id)arg2 termsOfServicePolicyUrl:(id)arg3 termsOfServicePolicyLabel:(id)arg4 privacyPolicyUrl:(id)arg5 privacyPolicyLabel:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *privacyPolicyLabel; // @dynamic privacyPolicyLabel;
@property(readonly, nonatomic) NSString *privacyPolicyUrl; // @dynamic privacyPolicyUrl;
@property(readonly, nonatomic) NSString *returnPolicyUrl; // @dynamic returnPolicyUrl;
@property(readonly, nonatomic) NSString *returnPolicyUrlLabel; // @dynamic returnPolicyUrlLabel;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *termsOfServicePolicyLabel; // @dynamic termsOfServicePolicyLabel;
@property(readonly, nonatomic) NSString *termsOfServicePolicyUrl; // @dynamic termsOfServicePolicyUrl;

@end

