//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SOJUAuthPayload-Protocol.h"

@class NSNumber, NSString;

@protocol SOJUChatConversationActionRequest <SOJUAuthPayload>
@property(readonly, nonatomic) NSNumber *muteCognacNotification;
@property(readonly, nonatomic) NSNumber *messageRetentionInMinutes;
@property(readonly, nonatomic) NSNumber *enabled;
@property(readonly, nonatomic) NSString *action;
@property(readonly, nonatomic) NSString *conversationId;
@end

