//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSNumber, NSString, SOJUGalleryServletSnapAssetsGallerySnapAssetMetadata;

@protocol SOJUGalleryServletSnapAssetsGallerySnapAsset <SCSojuMessage>
@property(readonly, nonatomic) SOJUGalleryServletSnapAssetsGallerySnapAssetMetadata *assetMetadata;
@property(readonly, nonatomic) NSString *downloadUrl;
@property(readonly, nonatomic) NSNumber *assetDescriptor;
@property(readonly, nonatomic) NSString *idValue;
@end

