//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUUnlockablesOndemandHomeFilterWireModel-Protocol.h"

@class NSArray, NSNumber, NSString, SOJUUnlockablesOndemandHomeFilterAddress, SOJUUnlockablesOndemandHomeFilterTargeting;

@interface SOJUUnlockablesOndemandHomeFilterWireModel : SCSojuMessage <SOJUUnlockablesOndemandHomeFilterWireModel>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithIsEnabled:(id)arg1 address:(id)arg2 targeting:(id)arg3 homeFilterAssets:(id)arg4;

// Remaining properties
@property(readonly, nonatomic) SOJUUnlockablesOndemandHomeFilterAddress *address; // @dynamic address;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSArray *homeFilterAssets; // @dynamic homeFilterAssets;
@property(readonly, nonatomic) NSNumber *isEnabled; // @dynamic isEnabled;
@property(readonly) Class superclass;
@property(readonly, nonatomic) SOJUUnlockablesOndemandHomeFilterTargeting *targeting; // @dynamic targeting;

@end

