//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSNumber;

@protocol SOJUFeatureSettings <SCSojuMessage>
@property(readonly, nonatomic) NSNumber *galleryIsBlocked;
@property(readonly, nonatomic) NSNumber *showTravelModeAtTopInSettings;
@property(readonly, nonatomic) NSNumber *isSnapAdsPortalContributor;
@property(readonly, nonatomic) NSNumber *isAdvertiser;
@property(readonly, nonatomic) NSNumber *galleryInvited;
@property(readonly, nonatomic) NSNumber *galleryEnabled;
@property(readonly, nonatomic) NSNumber *isBirthdayPartyEnabled;
@property(readonly, nonatomic) NSNumber *isLensesTooltipEnabled;
@property(readonly, nonatomic) NSNumber *isPrefetchForStoreLensesEnabled;
@property(readonly, nonatomic) NSNumber *lookseryFaceTrackingv2InitializationEnabled;
@property(readonly, nonatomic) NSNumber *lookseryFaceTrackingv2Enabled;
@property(readonly, nonatomic) NSNumber *qrcodeEnabled;
@property(readonly, nonatomic) NSNumber *barcodeEnabled;
@property(readonly, nonatomic) NSNumber *lensStoreAvailable;
@property(readonly, nonatomic) NSNumber *payReplaySnaps;
@property(readonly, nonatomic) NSNumber *travelMode;
@property(readonly, nonatomic) NSNumber *replaySnaps;
@property(readonly, nonatomic) NSNumber *frontFacingFlash;
@property(readonly, nonatomic) NSNumber *visualFilters;
@property(readonly, nonatomic) NSNumber *smartFilters;
@end

