//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUGalleryStoryInviteStickerStyle-Protocol.h"

@class NSString;

@interface SOJUGalleryStoryInviteStickerStyle : SCSojuMessage <SOJUGalleryStoryInviteStickerStyle>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithStoryName:(id)arg1 storyId:(id)arg2 inviteId:(id)arg3 username:(id)arg4 bitmojiAvatarId:(id)arg5;

// Remaining properties
@property(readonly, nonatomic) NSString *bitmojiAvatarId; // @dynamic bitmojiAvatarId;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *inviteId; // @dynamic inviteId;
@property(readonly, nonatomic) NSString *storyId; // @dynamic storyId;
@property(readonly, nonatomic) NSString *storyName; // @dynamic storyName;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *username; // @dynamic username;

@end

