//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUCommerceStoreInfo-Protocol.h"

@class NSNumber, NSString, SOJUCommerceSnapCodeInfo, SOJUCommerceSnapCommercePolicy, SOJUCommerceStoreCategoryInfo, SOJUCommerceStorePixelInfo, SOJUCommerceStorePolicy;

@interface SOJUCommerceStoreInfo : SCSojuMessage <SOJUCommerceStoreInfo>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithIdValue:(id)arg1 name:(id)arg2 owner:(id)arg3 email:(id)arg4 phone:(id)arg5 iconUrl:(id)arg6 categoryInfo:(id)arg7 snapchatAccount:(id)arg8 storePolicy:(id)arg9 supportUrl:(id)arg10 isStoreVisible:(id)arg11 checkoutDisclaimerPolicyHtml:(id)arg12 doesShipToUserLocation:(id)arg13 shouldUseWebview:(id)arg14 snapcodeUrl:(id)arg15 soldBy:(id)arg16 snapCommercePolicy:(id)arg17 isThirdPartyStore:(id)arg18 descriptionValue:(id)arg19 deeplinkSnapCodeInfo:(id)arg20 storePixelInfo:(id)arg21;
- (_Bool)isSpectaclesStore;
- (_Bool)isValidModel;

// Remaining properties
@property(readonly, nonatomic) SOJUCommerceStoreCategoryInfo *categoryInfo; // @dynamic categoryInfo;
@property(readonly, nonatomic) NSString *checkoutDisclaimerPolicyHtml; // @dynamic checkoutDisclaimerPolicyHtml;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) SOJUCommerceSnapCodeInfo *deeplinkSnapCodeInfo; // @dynamic deeplinkSnapCodeInfo;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *descriptionValue; // @dynamic descriptionValue;
@property(readonly, nonatomic) NSNumber *doesShipToUserLocation; // @dynamic doesShipToUserLocation;
@property(readonly, nonatomic) NSString *email; // @dynamic email;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *iconUrl; // @dynamic iconUrl;
@property(readonly, nonatomic) NSString *idValue; // @dynamic idValue;
@property(readonly, nonatomic) NSNumber *isStoreVisible; // @dynamic isStoreVisible;
@property(readonly, nonatomic) NSNumber *isThirdPartyStore; // @dynamic isThirdPartyStore;
@property(readonly, nonatomic) NSString *name; // @dynamic name;
@property(readonly, nonatomic) NSString *owner; // @dynamic owner;
@property(readonly, nonatomic) NSString *phone; // @dynamic phone;
@property(readonly, nonatomic) NSNumber *shouldUseWebview; // @dynamic shouldUseWebview;
@property(readonly, nonatomic) SOJUCommerceSnapCommercePolicy *snapCommercePolicy; // @dynamic snapCommercePolicy;
@property(readonly, nonatomic) NSString *snapchatAccount; // @dynamic snapchatAccount;
@property(readonly, nonatomic) NSString *snapcodeUrl; // @dynamic snapcodeUrl;
@property(readonly, nonatomic) NSString *soldBy; // @dynamic soldBy;
@property(readonly, nonatomic) SOJUCommerceStorePixelInfo *storePixelInfo; // @dynamic storePixelInfo;
@property(readonly, nonatomic) SOJUCommerceStorePolicy *storePolicy; // @dynamic storePolicy;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *supportUrl; // @dynamic supportUrl;

@end

