//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUCdnCdnClientConfig-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface SOJUCdnCdnClientConfig : SCSojuMessage <SOJUCdnCdnClientConfig>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithVersion:(id)arg1 cachableUrls:(id)arg2 cdnRoutingRules:(id)arg3 cdnInfos:(id)arg4 routingDefinitions:(id)arg5;

// Remaining properties
@property(readonly, nonatomic) NSArray *cachableUrls; // @dynamic cachableUrls;
@property(readonly, nonatomic) NSArray *cdnInfos; // @dynamic cdnInfos;
@property(readonly, nonatomic) NSArray *cdnRoutingRules; // @dynamic cdnRoutingRules;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSArray *routingDefinitions; // @dynamic routingDefinitions;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSNumber *version; // @dynamic version;

@end

