//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSNumber, NSString, SOJUAdIdentityResponse, SOJUAdOpportunityRequestIds, SOJUCarouselConfig, SOJUUnlockablesPrecacheInfoForLocData, SOJUWeatherResponse;

@protocol SOJULocationResponse <SCSojuMessage>
@property(readonly, nonatomic) SOJUAdOpportunityRequestIds *opportunityRequestIds;
@property(readonly, nonatomic) NSArray *purposes;
@property(readonly, nonatomic) NSArray *stickers;
@property(readonly, nonatomic) SOJUUnlockablesPrecacheInfoForLocData *precacheServingInfo;
@property(readonly, nonatomic) SOJUAdIdentityResponse *adIdentity;
@property(readonly, nonatomic) NSArray *venueFilters;
@property(readonly, nonatomic) NSArray *mobStoryAuths;
@property(readonly, nonatomic) SOJUCarouselConfig *carousel;
@property(readonly, nonatomic) NSString *encGeocell;
@property(readonly, nonatomic) NSArray *preCacheGeolenses;
@property(readonly, nonatomic) NSArray *geoStickerPacks;
@property(readonly, nonatomic) NSArray *lensFilters;
@property(readonly, nonatomic) NSArray *ourStoryAuths;
@property(readonly, nonatomic) NSNumber *clearCacheOurStoryAuths;
@property(readonly, nonatomic) NSArray *preCacheGeofilters;
@property(readonly, nonatomic) NSArray *bitmojiFilters;
@property(readonly, nonatomic) NSArray *invalidFilterIds;
@property(readonly, nonatomic) NSArray *filters;
@property(readonly, nonatomic) SOJUWeatherResponse *weather;
@end

