//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SOJUConversationMessage-Protocol.h"

@class NSNumber, NSString;

@protocol SOJUSnapStateMessage <SOJUConversationMessage>
@property(readonly, nonatomic) NSNumber *screenCaptureRecordingCount;
@property(readonly, nonatomic) NSNumber *screenCaptureShotCount;
@property(readonly, nonatomic) NSString *fiSenderOutBeta;
@property(readonly, nonatomic) NSString *fiRecipientOutDeltaCheck;
@property(readonly, nonatomic) NSString *fiRecipientOutDelta;
@property(readonly, nonatomic) NSNumber *fiSendTimestamp;
@property(readonly, nonatomic) NSString *fiRecipientOutAlpha;
@property(readonly, nonatomic) NSString *fiSenderOutAlpha;
@property(readonly, nonatomic) NSNumber *fiVersion;
@property(readonly, nonatomic) NSNumber *fiNeedsRetry;
@property(readonly, nonatomic) NSNumber *screenshotCount;
@property(readonly, nonatomic) NSNumber *replayed;
@property(readonly, nonatomic) NSNumber *viewed;
@property(readonly, nonatomic) NSString *snapId;
@end

