//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SCEmojiTextConvertible-Protocol.h"
#import "SOJUSticker-Protocol.h"

@class NSArray, NSData, NSNumber, NSString;

@interface SOJUSticker : SCSojuMessage <SCEmojiTextConvertible, SOJUSticker>
{
}

+ (void)registerMessageFields:(id)arg1;
+ (id)stickerIdFullFromStickerWithoutGeoStickerId:(id)arg1;
+ (id)privacySafeStickerIdFromSticker:(id)arg1;
+ (id)stickerFromBitmoji:(id)arg1 packId:(id)arg2 avatarId:(id)arg3 friendAvatarId:(id)arg4 unlockableId:(id)arg5;
- (id)initWithPackId:(id)arg1 stickerId:(id)arg2 stickerType:(id)arg3 capabilities:(id)arg4 creationTime:(id)arg5 encKey:(id)arg6 encIv:(id)arg7 lastUsedTime:(id)arg8 facecutOriginSnapId:(id)arg9 customStickerType:(id)arg10 isAnimated:(id)arg11 externalSrcUrl:(id)arg12 stickerImageData:(id)arg13 uniqueId:(id)arg14 unlockableId:(id)arg15 order:(id)arg16;
- (id)convertToEmojiText;
- (_Bool)isBitmoji;
- (_Bool)isFriends;
- (_Bool)isGeo;

// Remaining properties
@property(readonly, nonatomic) NSArray *capabilities; // @dynamic capabilities;
@property(readonly, nonatomic) NSNumber *creationTime; // @dynamic creationTime;
@property(readonly, nonatomic) NSString *customStickerType; // @dynamic customStickerType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *encIv; // @dynamic encIv;
@property(readonly, nonatomic) NSString *encKey; // @dynamic encKey;
@property(readonly, nonatomic) NSString *externalSrcUrl; // @dynamic externalSrcUrl;
@property(readonly, nonatomic) NSString *facecutOriginSnapId; // @dynamic facecutOriginSnapId;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *isAnimated; // @dynamic isAnimated;
@property(readonly, nonatomic) NSNumber *lastUsedTime; // @dynamic lastUsedTime;
@property(readonly, nonatomic) NSNumber *order; // @dynamic order;
@property(readonly, nonatomic) NSString *packId; // @dynamic packId;
@property(readonly, nonatomic) NSString *stickerId; // @dynamic stickerId;
@property(readonly, nonatomic) NSData *stickerImageData; // @dynamic stickerImageData;
@property(readonly, nonatomic) NSString *stickerType; // @dynamic stickerType;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSNumber *uniqueId; // @dynamic uniqueId;
@property(readonly, nonatomic) NSNumber *unlockableId; // @dynamic unlockableId;

@end

