//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUStrRect-Protocol.h"

@class NSString;

@interface SOJUStrRect : SCSojuMessage <SOJUStrRect>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithX:(id)arg1 y:(id)arg2 width:(id)arg3 height:(id)arg4;
- (id)initWithProtoBuf:(id)arg1;
- (id)initWithProtoBinary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *height; // @dynamic height;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *width; // @dynamic width;
@property(readonly, nonatomic) NSString *x; // @dynamic x;
@property(readonly, nonatomic) NSString *y; // @dynamic y;

@end

