//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUContextFilterSkyItem-Protocol.h"

@class NSNumber, NSString;

@interface SOJUContextFilterSkyItem : SCSojuMessage <SOJUContextFilterSkyItem>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithUuid:(id)arg1 url:(id)arg2 skyType:(id)arg3 styleType:(id)arg4 colorBrightness:(id)arg5 replacementSkyUrl:(id)arg6 blimpUrl:(id)arg7;
- (id)initWithProtoBuf:(id)arg1;
- (id)initWithProtoBinary:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSString *blimpUrl; // @dynamic blimpUrl;
@property(readonly, nonatomic) NSNumber *colorBrightness; // @dynamic colorBrightness;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *replacementSkyUrl; // @dynamic replacementSkyUrl;
@property(readonly, nonatomic) NSString *skyType; // @dynamic skyType;
@property(readonly, nonatomic) NSString *styleType; // @dynamic styleType;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *url; // @dynamic url;
@property(readonly, nonatomic) NSString *uuid; // @dynamic uuid;

@end

