//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSNumber, NSString;

@protocol SOJUGalleryVenueFilter <SCSojuMessage>
@property(readonly, nonatomic) NSString *selectedVenueId;
@property(readonly, nonatomic) NSArray *venues;
@property(readonly, nonatomic) NSNumber *yOffset;
@end

