//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSString, SOJUIdentityMischiefMetadata, SOJULastMischiefChatAction, SOJULastMischiefContent, SOJUVideoChatParams;

@protocol SOJUIdentityMischief <SCSojuMessage>
@property(readonly, nonatomic) NSString *migrationState;
@property(readonly, nonatomic) NSNumber *isCognacNotificationMuted;
@property(readonly, nonatomic) NSNumber *mentionNotificationStatus;
@property(readonly, nonatomic) NSArray *messageEraseMessages;
@property(readonly, nonatomic) NSDictionary *seenChatSequenceNumbers;
@property(readonly, nonatomic) NSString *mischiefCreationSource;
@property(readonly, nonatomic) NSString *creatorId;
@property(readonly, nonatomic) NSNumber *isStoryMuted;
@property(readonly, nonatomic) NSString *mischiefMobId;
@property(readonly, nonatomic) NSDictionary *participantLastContent;
@property(readonly, nonatomic) NSDictionary *pageLatestSequenceNumbers;
@property(readonly, nonatomic) NSDictionary *blockedParticipantExceptions;
@property(readonly, nonatomic) SOJULastMischiefContent *lastMischiefContent;
@property(readonly, nonatomic) NSNumber *laterContentExists;
@property(readonly, nonatomic) NSArray *snapStateMessages;
@property(readonly, nonatomic) NSArray *messageStateMessages;
@property(readonly, nonatomic) NSDictionary *earliestSequenceNumbers;
@property(readonly, nonatomic) NSNumber *earlierContentExists;
@property(readonly, nonatomic) SOJUVideoChatParams *videoChatParams;
@property(readonly, nonatomic) NSNumber *notificationStatus;
@property(readonly, nonatomic) NSArray *updateMessages;
@property(readonly, nonatomic) NSArray *releaseMessages;
@property(readonly, nonatomic) NSArray *chatMessages;
@property(readonly, nonatomic) NSArray *contentOrder;
@property(readonly, nonatomic) NSArray *content;
@property(readonly, nonatomic) NSString *contentType;
@property(readonly, nonatomic) NSString *iterToken;
@property(readonly, nonatomic) NSArray *stickerFavorites;
@property(readonly, nonatomic) SOJULastMischiefChatAction *lastMischiefChatAction;
@property(readonly, nonatomic) NSDictionary *latestSequenceNumbers;
@property(readonly, nonatomic) NSNumber *lastClearedTimestamp;
@property(readonly, nonatomic) NSNumber *lastInteractionTimestamp;
@property(readonly, nonatomic) NSNumber *createMischiefTimestamp;
@property(readonly, nonatomic) NSArray *exParticipants;
@property(readonly, nonatomic) NSArray *participants;
@property(readonly, nonatomic) NSString *mischiefName;
@property(readonly, nonatomic) SOJUIdentityMischiefMetadata *mischiefMetadata;
@property(readonly, nonatomic) NSString *mischiefId;
@end

