//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUGalleryServletMediaResult-Protocol.h"

@class NSDictionary, NSNumber, NSString;

@interface SOJUGalleryServletMediaResult : SCSojuMessage <SOJUGalleryServletMediaResult>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithMediaId:(id)arg1 uploadUrl:(id)arg2 statusCode:(id)arg3 debugInfo:(id)arg4 uploadHeaders:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) NSString *debugInfo; // @dynamic debugInfo;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *mediaId; // @dynamic mediaId;
@property(readonly, nonatomic) NSNumber *statusCode; // @dynamic statusCode;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSDictionary *uploadHeaders; // @dynamic uploadHeaders;
@property(readonly, nonatomic) NSString *uploadUrl; // @dynamic uploadUrl;

@end

