//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUUnlockablesOndemandUser-Protocol.h"

@class NSArray, NSString;

@interface SOJUUnlockablesOndemandUser : SCSojuMessage <SOJUUnlockablesOndemandUser>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithUsername:(id)arg1 userEmail:(id)arg2 userId:(id)arg3 organizations:(id)arg4 countryFromIp:(id)arg5;

// Remaining properties
@property(readonly, nonatomic) NSString *countryFromIp; // @dynamic countryFromIp;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSArray *organizations; // @dynamic organizations;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *userEmail; // @dynamic userEmail;
@property(readonly, nonatomic) NSString *userId; // @dynamic userId;
@property(readonly, nonatomic) NSString *username; // @dynamic username;

@end

