//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUGalleryServletMediaParams-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface SOJUGalleryServletMediaParams : SCSojuMessage <SOJUGalleryServletMediaParams>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithMediaType:(id)arg1 mediaId:(id)arg2 mediaMd5hash:(id)arg3 size:(id)arg4 createTime:(id)arg5 mediaFormat:(id)arg6 facesList:(id)arg7;

// Remaining properties
@property(readonly, nonatomic) NSNumber *createTime; // @dynamic createTime;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSArray *facesList; // @dynamic facesList;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *mediaFormat; // @dynamic mediaFormat;
@property(readonly, nonatomic) NSString *mediaId; // @dynamic mediaId;
@property(readonly, nonatomic) NSString *mediaMd5hash; // @dynamic mediaMd5hash;
@property(readonly, nonatomic) NSNumber *mediaType; // @dynamic mediaType;
@property(readonly, nonatomic) NSNumber *size; // @dynamic size;
@property(readonly) Class superclass;

@end

