//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUBroadcastArticleMetadata-Protocol.h"

@class NSNumber, NSString, SOJUDiscoverModerationAudience, SOJUDiscoverModerationBrandSafety;

@interface SOJUBroadcastArticleMetadata : SCSojuMessage <SOJUBroadcastArticleMetadata>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithTileId:(id)arg1 headline:(id)arg2 imageUrl:(id)arg3 collapsedTileCropPctOffset:(id)arg4 horizontalTileCropPctOffset:(id)arg5 trackingId:(id)arg6 textJustification:(id)arg7 logoUrl:(id)arg8 verticalV2TileCropPctOffset:(id)arg9 horizontalV2TileCropPctOffset:(id)arg10 collapsedV2TileCropPctOffset:(id)arg11 narrowV2TileCropPctOffset:(id)arg12 mediumV2TileCropPctOffset:(id)arg13 logoReadStateOverlayColor:(id)arg14 logoText:(id)arg15 videoUrl:(id)arg16 logoPosition:(id)arg17 logoDropShadowEnabled:(id)arg18 logoDropShadowColor:(id)arg19 videoThumbnailUrl:(id)arg20 bitmojiTileTemplateId:(id)arg21 audience:(id)arg22 brandSafety:(id)arg23;

// Remaining properties
@property(readonly, nonatomic) SOJUDiscoverModerationAudience *audience; // @dynamic audience;
@property(readonly, nonatomic) NSString *bitmojiTileTemplateId; // @dynamic bitmojiTileTemplateId;
@property(readonly, nonatomic) SOJUDiscoverModerationBrandSafety *brandSafety; // @dynamic brandSafety;
@property(readonly, nonatomic) NSNumber *collapsedTileCropPctOffset; // @dynamic collapsedTileCropPctOffset;
@property(readonly, nonatomic) NSNumber *collapsedV2TileCropPctOffset; // @dynamic collapsedV2TileCropPctOffset;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *headline; // @dynamic headline;
@property(readonly, nonatomic) NSNumber *horizontalTileCropPctOffset; // @dynamic horizontalTileCropPctOffset;
@property(readonly, nonatomic) NSNumber *horizontalV2TileCropPctOffset; // @dynamic horizontalV2TileCropPctOffset;
@property(readonly, nonatomic) NSString *imageUrl; // @dynamic imageUrl;
@property(readonly, nonatomic) NSString *logoDropShadowColor; // @dynamic logoDropShadowColor;
@property(readonly, nonatomic) NSNumber *logoDropShadowEnabled; // @dynamic logoDropShadowEnabled;
@property(readonly, nonatomic) NSString *logoPosition; // @dynamic logoPosition;
@property(readonly, nonatomic) NSString *logoReadStateOverlayColor; // @dynamic logoReadStateOverlayColor;
@property(readonly, nonatomic) NSString *logoText; // @dynamic logoText;
@property(readonly, nonatomic) NSString *logoUrl; // @dynamic logoUrl;
@property(readonly, nonatomic) NSNumber *mediumV2TileCropPctOffset; // @dynamic mediumV2TileCropPctOffset;
@property(readonly, nonatomic) NSNumber *narrowV2TileCropPctOffset; // @dynamic narrowV2TileCropPctOffset;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *textJustification; // @dynamic textJustification;
@property(readonly, nonatomic) NSString *tileId; // @dynamic tileId;
@property(readonly, nonatomic) NSString *trackingId; // @dynamic trackingId;
@property(readonly, nonatomic) NSNumber *verticalV2TileCropPctOffset; // @dynamic verticalV2TileCropPctOffset;
@property(readonly, nonatomic) NSString *videoThumbnailUrl; // @dynamic videoThumbnailUrl;
@property(readonly, nonatomic) NSString *videoUrl; // @dynamic videoUrl;

@end

