//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUCdnCdnInfo-Protocol.h"

@class NSString;

@interface SOJUCdnCdnInfo : SCSojuMessage <SOJUCdnCdnInfo>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithCdnId:(id)arg1 host:(id)arg2;

// Remaining properties
@property(readonly, nonatomic) NSString *cdnId; // @dynamic cdnId;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *host; // @dynamic host;
@property(readonly) Class superclass;

@end

