//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUScannableActionUnlockableSticker-Protocol.h"

@class NSNumber, NSString;

@interface SOJUScannableActionUnlockableSticker : SCSojuMessage <SOJUScannableActionUnlockableSticker>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithThumbnailImageLink:(id)arg1 stickerTitle:(id)arg2 stickerPackId:(id)arg3 unlockDurationInMins:(id)arg4 unlocked:(id)arg5 unlockableId:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *stickerPackId; // @dynamic stickerPackId;
@property(readonly, nonatomic) NSString *stickerTitle; // @dynamic stickerTitle;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *thumbnailImageLink; // @dynamic thumbnailImageLink;
@property(readonly, nonatomic) NSNumber *unlockDurationInMins; // @dynamic unlockDurationInMins;
@property(readonly, nonatomic) NSString *unlockableId; // @dynamic unlockableId;
@property(readonly, nonatomic) NSNumber *unlocked; // @dynamic unlocked;

@end

