//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUIdentitySuggestionPlacementReasonPairDeprecated-Protocol.h"

@class NSString;

@interface SOJUIdentitySuggestionPlacementReasonPairDeprecated : SCSojuMessage <SOJUIdentitySuggestionPlacementReasonPairDeprecated>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithPlacement:(id)arg1 reason:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *placement; // @dynamic placement;
@property(readonly, nonatomic) NSString *reason; // @dynamic reason;
@property(readonly) Class superclass;

@end

