//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUStoryLogbook-Protocol.h"

@class NSArray, NSNumber, NSString, SOJUStory, SOJUStoryExtra;

@interface SOJUStoryLogbook : SCSojuMessage <SOJUStoryLogbook>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithStory:(id)arg1 storyExtras:(id)arg2 friendStoryExtras:(id)arg3 otherStoryExtras:(id)arg4 engagementPercentage:(id)arg5 intendedPostTime:(id)arg6 storyNotes:(id)arg7 friendStoryNotes:(id)arg8 otherStoryNotes:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSNumber *engagementPercentage; // @dynamic engagementPercentage;
@property(readonly, nonatomic) SOJUStoryExtra *friendStoryExtras; // @dynamic friendStoryExtras;
@property(readonly, nonatomic) NSArray *friendStoryNotes; // @dynamic friendStoryNotes;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *intendedPostTime; // @dynamic intendedPostTime;
@property(readonly, nonatomic) SOJUStoryExtra *otherStoryExtras; // @dynamic otherStoryExtras;
@property(readonly, nonatomic) NSArray *otherStoryNotes; // @dynamic otherStoryNotes;
@property(readonly, nonatomic) SOJUStory *story; // @dynamic story;
@property(readonly, nonatomic) SOJUStoryExtra *storyExtras; // @dynamic storyExtras;
@property(readonly, nonatomic) NSArray *storyNotes; // @dynamic storyNotes;
@property(readonly) Class superclass;

@end

