//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUSecurityGetAssertionResponse-Protocol.h"

@class NSString;

@interface SOJUSecurityGetAssertionResponse : SCSojuMessage <SOJUSecurityGetAssertionResponse>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithAssertion:(id)arg1 tag1:(id)arg2 tag2:(id)arg3 nonce:(id)arg4;

// Remaining properties
@property(readonly, nonatomic) NSString *assertion; // @dynamic assertion;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *nonce; // @dynamic nonce;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *tag1; // @dynamic tag1;
@property(readonly, nonatomic) NSString *tag2; // @dynamic tag2;

@end

