//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUSnapUpdate-Protocol.h"

@class NSNumber, NSString;

@interface SOJUSnapUpdate : SCSojuMessage <SOJUSnapUpdate>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithT:(id)arg1 c:(id)arg2 replayed:(id)arg3 sv:(id)arg4 stackId:(id)arg5 replayPurchaseReceipt:(id)arg6 esId:(id)arg7 fiNeedsRetry:(id)arg8 fiVersion:(id)arg9 fiRecipientOutAlpha:(id)arg10 fiRecipientOutDelta:(id)arg11 fiRecipientOutDeltaCheck:(id)arg12 fiRecipientOutBeta:(id)arg13 screenCaptureShotCount:(id)arg14 screenCaptureRecordingCount:(id)arg15;

// Remaining properties
@property(readonly, nonatomic) NSNumber *c; // @dynamic c;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSString *esId; // @dynamic esId;
@property(readonly, nonatomic) NSNumber *fiNeedsRetry; // @dynamic fiNeedsRetry;
@property(readonly, nonatomic) NSString *fiRecipientOutAlpha; // @dynamic fiRecipientOutAlpha;
@property(readonly, nonatomic) NSString *fiRecipientOutBeta; // @dynamic fiRecipientOutBeta;
@property(readonly, nonatomic) NSString *fiRecipientOutDelta; // @dynamic fiRecipientOutDelta;
@property(readonly, nonatomic) NSString *fiRecipientOutDeltaCheck; // @dynamic fiRecipientOutDeltaCheck;
@property(readonly, nonatomic) NSNumber *fiVersion; // @dynamic fiVersion;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *replayPurchaseReceipt; // @dynamic replayPurchaseReceipt;
@property(readonly, nonatomic) NSNumber *replayed; // @dynamic replayed;
@property(readonly, nonatomic) NSNumber *screenCaptureRecordingCount; // @dynamic screenCaptureRecordingCount;
@property(readonly, nonatomic) NSNumber *screenCaptureShotCount; // @dynamic screenCaptureShotCount;
@property(readonly, nonatomic) NSString *stackId; // @dynamic stackId;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSNumber *sv; // @dynamic sv;
@property(readonly, nonatomic) NSNumber *t; // @dynamic t;

@end

