//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage.h"

#import "SOJUGalleryServletSensorBlob-Protocol.h"

@class NSNumber, NSString;

@interface SOJUGalleryServletSensorBlob : SCSojuMessage <SOJUGalleryServletSensorBlob>
{
}

+ (void)registerMessageFields:(id)arg1;
- (id)initWithData:(id)arg1 sensorMajorVersion:(id)arg2 sensorMinorVersion:(id)arg3;
- (id)initWithProtoBuf:(id)arg1;
- (id)initWithProtoBinary:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSString *data; // @dynamic data;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSNumber *sensorMajorVersion; // @dynamic sensorMajorVersion;
@property(readonly, nonatomic) NSNumber *sensorMinorVersion; // @dynamic sensorMinorVersion;
@property(readonly) Class superclass;

@end

