//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSNumber, NSString, SOJUCoordinate, SOJUGalleryMultiSnapSegment, SOJUGalleryServletSensorBlob, SOJUGallerySnapSource, SOJUStoryFrame;

@protocol SOJUGalleryServletGallerySnap <SCSojuMessage>
@property(readonly, nonatomic) NSArray *snapAssets;
@property(readonly, nonatomic) NSString *spectaclesSecondaryMetadataRedirectUri;
@property(readonly, nonatomic) NSNumber *hasSpectaclesSecondaryMetadata;
@property(readonly, nonatomic) NSString *spectaclesSecondaryMetadataUrl;
@property(readonly, nonatomic) NSArray *mediaAttributes;
@property(readonly, nonatomic) NSNumber *hasDepthEffectDeprecated;
@property(readonly, nonatomic) NSString *spectaclesMetadataRedirectUri;
@property(readonly, nonatomic) NSNumber *hasSpectaclesMetadata;
@property(readonly, nonatomic) NSString *spectaclesMetadataUrl;
@property(readonly, nonatomic) NSArray *toolVersions;
@property(readonly, nonatomic) SOJUGalleryServletSensorBlob *sensorBlob;
@property(readonly, nonatomic) NSString *multiSnapGroupId;
@property(readonly, nonatomic) SOJUGalleryMultiSnapSegment *multiSnapSegment;
@property(readonly, nonatomic) NSString *mediaFormat;
@property(readonly, nonatomic) NSNumber *captureTime;
@property(readonly, nonatomic) NSNumber *hdMediaSize;
@property(readonly, nonatomic) NSNumber *overlayImageSize;
@property(readonly, nonatomic) NSNumber *thumbnailSize;
@property(readonly, nonatomic) NSNumber *gzippedOverlay;
@property(readonly, nonatomic) NSString *hdMediaRedirectUri;
@property(readonly, nonatomic) NSString *mediaRedirectUri;
@property(readonly, nonatomic) NSString *overlayRedirectUri;
@property(readonly, nonatomic) NSString *thumbnailRedirectUri;
@property(readonly, nonatomic) NSNumber *infiniteDuration;
@property(readonly, nonatomic) NSString *thumbnailRedirectUrlDeprecated;
@property(readonly, nonatomic) NSString *miniThumbnailBytes;
@property(readonly, nonatomic) NSNumber *isInfiniteDurationDeprecated;
@property(readonly, nonatomic) NSString *deviceId;
@property(readonly, nonatomic) NSNumber *contentScore;
@property(readonly, nonatomic) NSNumber *statusCode;
@property(readonly, nonatomic) SOJUStoryFrame *framing;
@property(readonly, nonatomic) SOJUGallerySnapSource *source;
@property(readonly, nonatomic) NSNumber *cameraFrontFacing;
@property(readonly, nonatomic) NSNumber *cameraHardwareMountingDegrees;
@property(readonly, nonatomic) NSNumber *tagsVersion;
@property(readonly, nonatomic) NSString *tags;
@property(readonly, nonatomic) NSNumber *hasThumbnail;
@property(readonly, nonatomic) NSString *thumbnailDownloadUrl;
@property(readonly, nonatomic) NSNumber *hasOverlayImage;
@property(readonly, nonatomic) NSString *overlayDownloadUrl;
@property(readonly, nonatomic) NSNumber *hdMediaStatus;
@property(readonly, nonatomic) NSString *hdMediaDownloadUrl;
@property(readonly, nonatomic) NSString *mediaDownloadUrl;
@property(readonly, nonatomic) NSNumber *size;
@property(readonly, nonatomic) NSNumber *duration;
@property(readonly, nonatomic) NSNumber *height;
@property(readonly, nonatomic) NSNumber *width;
@property(readonly, nonatomic) NSNumber *battery;
@property(readonly, nonatomic) NSNumber *speed;
@property(readonly, nonatomic) NSNumber *temperature;
@property(readonly, nonatomic) NSString *timeZone;
@property(readonly, nonatomic) SOJUCoordinate *location;
@property(readonly, nonatomic) NSNumber *overlayOrientation;
@property(readonly, nonatomic) NSNumber *orientation;
@property(readonly, nonatomic) NSNumber *createTime;
@property(readonly, nonatomic) NSString *overlay;
@property(readonly, nonatomic) NSNumber *mediaType;
@property(readonly, nonatomic) NSString *encryption;
@property(readonly, nonatomic) NSString *mediaId;
@property(readonly, nonatomic) NSNumber *defunct;
@property(readonly, nonatomic) NSString *snapId;
@end

