//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSojuMessage-Protocol.h"

@class NSArray, NSDictionary, NSNumber;

@protocol SOJUIdentityTrophyCase <SCSojuMessage>
@property(readonly, nonatomic) NSDictionary *metricCounters;
@property(readonly, nonatomic) NSNumber *receivedSnaps;
@property(readonly, nonatomic) NSNumber *sentSnaps;
@property(readonly, nonatomic) NSNumber *score;
@property(readonly, nonatomic) NSArray *response;
@end

