//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPBaseViperViewController.h"

#import "SPCameraViewDelegate-Protocol.h"
#import "SPCameraViewInput-Protocol.h"

@class NSString, SPCameraView, UIColor;
@protocol SPCameraViewOutput;

@interface SPCameraViewController : SPBaseViperViewController <SPCameraViewDelegate, SPCameraViewInput>
{
    double _maskScaleWidthFactor;
    double _maskHeightToWidthAspect;
    double _maskCenterYInset;
    UIColor *_faceFoundMaskColor;
    UIColor *_faceNotFoundMaskColor;
    id <SPCameraViewOutput> _output;
}

+ (id)controller;
@property(retain, nonatomic) id <SPCameraViewOutput> output; // @synthesize output=_output;
@property(retain, nonatomic) UIColor *faceNotFoundMaskColor; // @synthesize faceNotFoundMaskColor=_faceNotFoundMaskColor;
@property(retain, nonatomic) UIColor *faceFoundMaskColor; // @synthesize faceFoundMaskColor=_faceFoundMaskColor;
@property(nonatomic) double maskCenterYInset; // @synthesize maskCenterYInset=_maskCenterYInset;
@property(nonatomic) double maskHeightToWidthAspect; // @synthesize maskHeightToWidthAspect=_maskHeightToWidthAspect;
@property(nonatomic) double maskScaleWidthFactor; // @synthesize maskScaleWidthFactor=_maskScaleWidthFactor;
- (void).cxx_destruct;
- (void)cameraView:(id)arg1 didChangeAllowTakePhoto:(_Bool)arg2;
- (void)cameraView:(id)arg1 didProcessCurrentImage:(id)arg2 fromBackCamera:(_Bool)arg3;
@property(nonatomic) long long flashMode;
@property(readonly, nonatomic) _Bool hasFlash;
- (void)switchCamera;
- (void)takePhoto;
- (void)setupInitialState;
- (void)setCameraViewModel:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
@property(retain, nonatomic) UIColor *disabledCameraBackgroundColor;
@property(retain, nonatomic) UIColor *overlayColor;
- (_Bool)prefersStatusBarHidden;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SPCameraView *view; // @dynamic view;

@end

