//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPBaseViewInput-Protocol.h"

@class SPCameraViewModel, UIColor;

@protocol SPCameraViewInput <SPBaseViewInput>
@property(retain, nonatomic) UIColor *faceNotFoundMaskColor;
@property(retain, nonatomic) UIColor *faceFoundMaskColor;
@property(retain, nonatomic) UIColor *disabledCameraBackgroundColor;
@property(retain, nonatomic) UIColor *overlayColor;
@property(nonatomic) double maskCenterYInset;
@property(nonatomic) double maskHeightToWidthAspect;
@property(nonatomic) double maskScaleWidthFactor;
@property(nonatomic) long long flashMode;
@property(readonly, nonatomic) _Bool hasFlash;
- (void)switchCamera;
- (void)takePhoto;
- (void)setCameraViewModel:(SPCameraViewModel *)arg1;
@end

