//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSOperationQueue, SPScenarioAllResourcesOperationFactory;
@protocol OS_dispatch_queue, SPScenariosDownloaderDataSource;

@interface SPScenariosDownloader : NSObject
{
    NSObject<OS_dispatch_queue> *_lockQueue;
    NSOperationQueue *_highPriorityOperationsQueue;
    NSOperationQueue *_normalPriorityOperationsQueue;
    id <SPScenariosDownloaderDataSource> _prefetchDataSource;
    SPScenarioAllResourcesOperationFactory *_resourcesOperationFactory;
}

@property(readonly, nonatomic) SPScenarioAllResourcesOperationFactory *resourcesOperationFactory; // @synthesize resourcesOperationFactory=_resourcesOperationFactory;
- (void).cxx_destruct;
- (id)_createOperationForScenario:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)forceLoadResourcesForScenarioViewModel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)loadResourcesForScenario:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) id <SPScenariosDownloaderDataSource> prefetchDataSource; // @synthesize prefetchDataSource=_prefetchDataSource;
- (id)initWithResourcesOperationsFactory:(id)arg1;

@end

