//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSNumber, NSString;

@interface SPScenarioResourcesModel : NSObject <NSCoding>
{
    NSString *_path;
    NSNumber *_prRatio;
    NSNumber *_prRequiredFramesAfterReset;
    NSNumber *_prRequiredFirstFrames;
}

@property(readonly, nonatomic) NSNumber *prRequiredFirstFrames; // @synthesize prRequiredFirstFrames=_prRequiredFirstFrames;
@property(readonly, nonatomic) NSNumber *prRequiredFramesAfterReset; // @synthesize prRequiredFramesAfterReset=_prRequiredFramesAfterReset;
@property(readonly, nonatomic) NSNumber *prRatio; // @synthesize prRatio=_prRatio;
@property(readonly, copy, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (id)initWithPath:(id)arg1 prRatio:(id)arg2 prRequiredFirstFrames:(id)arg3 prRequiredFramesAfterReset:(id)arg4;

@end

