//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject, SPHairStyleModel, SPPersonsSource, SPScenario, SPScenariosTopic;
@protocol OS_dispatch_queue, SPCancellationToken, SPPersonProcessor;

@protocol SPSearchIconService <NSObject>
- (id <SPCancellationToken>)searchIconForPersonsSource:(SPPersonsSource *)arg1 scenario:(SPScenario *)arg2 callbackQueue:(NSObject<OS_dispatch_queue> *)arg3 completion:(void (^)(UIImage *, NSError *))arg4;
- (id <SPCancellationToken>)searchIconForPersonProcessor:(id <SPPersonProcessor>)arg1 topic:(SPScenariosTopic *)arg2 hairStyleModel:(SPHairStyleModel *)arg3 size:(struct CGSize)arg4 callbackQueue:(NSObject<OS_dispatch_queue> *)arg5 completion:(void (^)(UIImage *, NSError *))arg6;
@end

