//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable;

@interface SPThreadSafeMapTable : NSObject
{
    struct _opaque_pthread_mutex_t _mutex;
    NSMapTable *_mapTable;
}

+ (id)weakToWeakObjectsMapTable;
@property(retain, nonatomic) NSMapTable *mapTable; // @synthesize mapTable=_mapTable;
- (void).cxx_destruct;
@property(readonly) unsigned long long count;
- (void)removeObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (id)initWithMapTable:(id)arg1;

@end

