//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AIText, NSArray, NSNumber, NSString, NSValue, SSFontResources, SSScenarioResources;

@interface SSScenario : NSObject
{
    _Bool _isCustomizable;
    _Bool _singleMode;
    _Bool _duoMode;
    _Bool _hidden;
    _Bool _featured;
    _Bool _isComposer;
    _Bool _swapPersons;
    _Bool _isCustomizedByUser;
    NSString *_scenarioId;
    NSString *_thumbnailPath;
    NSString *_previewAnimationPath;
    SSScenarioResources *_fullSizeResources;
    SSScenarioResources *_previewResources;
    SSScenarioResources *_previewFullLengthResources;
    SSScenarioResources *_previewHighFullLengthResources;
    SSFontResources *_fontResources;
    AIText *_printableText;
    struct NSArray *_printableLines;
    unsigned long long _personsCount;
    NSNumber *_duration;
    NSValue *_resolution;
    NSString *_lensId;
    NSArray *_scenarioFeatures;
}

@property(readonly, nonatomic) NSArray *scenarioFeatures; // @synthesize scenarioFeatures=_scenarioFeatures;
@property(readonly, nonatomic) NSString *lensId; // @synthesize lensId=_lensId;
@property(readonly, nonatomic) NSValue *resolution; // @synthesize resolution=_resolution;
@property(readonly, nonatomic) NSNumber *duration; // @synthesize duration=_duration;
@property(readonly) _Bool isCustomizedByUser; // @synthesize isCustomizedByUser=_isCustomizedByUser;
@property(readonly) unsigned long long personsCount; // @synthesize personsCount=_personsCount;
@property(readonly) _Bool swapPersons; // @synthesize swapPersons=_swapPersons;
@property(readonly) _Bool isComposer; // @synthesize isComposer=_isComposer;
@property(readonly) _Bool featured; // @synthesize featured=_featured;
@property(readonly) _Bool hidden; // @synthesize hidden=_hidden;
@property(readonly) _Bool duoMode; // @synthesize duoMode=_duoMode;
@property(readonly) _Bool singleMode; // @synthesize singleMode=_singleMode;
@property(readonly) _Bool isCustomizable; // @synthesize isCustomizable=_isCustomizable;
@property(readonly, nonatomic) NSArray *printableLines; // @synthesize printableLines=_printableLines;
@property(readonly, nonatomic) AIText *printableText; // @synthesize printableText=_printableText;
@property(readonly, nonatomic) SSFontResources *fontResources; // @synthesize fontResources=_fontResources;
@property(readonly, nonatomic) SSScenarioResources *previewHighFullLengthResources; // @synthesize previewHighFullLengthResources=_previewHighFullLengthResources;
@property(readonly, nonatomic) SSScenarioResources *previewFullLengthResources; // @synthesize previewFullLengthResources=_previewFullLengthResources;
@property(readonly, nonatomic) SSScenarioResources *previewResources; // @synthesize previewResources=_previewResources;
@property(readonly, nonatomic) SSScenarioResources *fullSizeResources; // @synthesize fullSizeResources=_fullSizeResources;
@property(readonly, nonatomic) NSString *previewAnimationPath; // @synthesize previewAnimationPath=_previewAnimationPath;
@property(readonly, nonatomic) NSString *thumbnailPath; // @synthesize thumbnailPath=_thumbnailPath;
@property(readonly, nonatomic) NSString *scenarioId; // @synthesize scenarioId=_scenarioId;
- (void).cxx_destruct;
- (id)initWithScenarioId:(id)arg1 thumbnailPath:(id)arg2 previewAnimationPath:(id)arg3 fullSizeResources:(id)arg4 previewResources:(id)arg5 previewFullLengthResources:(id)arg6 previewHighFullLengthResources:(id)arg7 fontResources:(id)arg8 printableText:(id)arg9 printableLines:(struct NSArray *)arg10 isCustomizable:(_Bool)arg11 singleMode:(_Bool)arg12 duoMode:(_Bool)arg13 hidden:(_Bool)arg14 featured:(_Bool)arg15 isComposer:(_Bool)arg16 isCustomizedByUser:(_Bool)arg17 personsCount:(unsigned long long)arg18 duration:(id)arg19 resolution:(id)arg20 swapPersons:(_Bool)arg21 lensId:(id)arg22 scenarioFeatures:(id)arg23;

@end

