//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface SSScenarioResources : NSObject
{
    NSString *_path;
    NSNumber *_predictorRatio;
    NSNumber *_predictorRequiredFirstFrames;
    NSArray *_previewDiffBorders;
}

@property(readonly, nonatomic) NSArray *previewDiffBorders; // @synthesize previewDiffBorders=_previewDiffBorders;
@property(readonly, nonatomic) NSNumber *predictorRequiredFirstFrames; // @synthesize predictorRequiredFirstFrames=_predictorRequiredFirstFrames;
@property(readonly, nonatomic) NSNumber *predictorRatio; // @synthesize predictorRatio=_predictorRatio;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (id)initWithPath:(id)arg1 predictorRatio:(id)arg2 predictorRequiredFirstFrames:(id)arg3 previewDiffBorders:(id)arg4;

@end

