//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSSet, NSString, TCV3FetchUserIdMapCallback, TCV3PresenceMessage, TCV3ResolveConversationIdCallback;

@protocol TCV3PresenceServiceDelegate
- (void)fetchUserIdMap:(NSString *)arg1 usernames:(NSSet *)arg2 callback:(TCV3FetchUserIdMapCallback *)arg3;
- (void)resolveConversationId:(NSString *)arg1 userId:(NSString *)arg2 callback:(TCV3ResolveConversationIdCallback *)arg3;
- (void)notifyActiveConversationsChanged;
- (void)sendPresenceMessage:(TCV3PresenceMessage *)arg1;
@end

