//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface TCV3SessionParameters : NSObject
{
    _Bool _isGroup;
    _Bool _audioOnly;
    NSArray *_participants;
}

+ (id)SessionParametersWithParticipants:(id)arg1 isGroup:(_Bool)arg2 audioOnly:(_Bool)arg3;
@property(readonly, nonatomic) _Bool audioOnly; // @synthesize audioOnly=_audioOnly;
@property(readonly, nonatomic) _Bool isGroup; // @synthesize isGroup=_isGroup;
@property(readonly, nonatomic) NSArray *participants; // @synthesize participants=_participants;
- (void).cxx_destruct;
- (id)description;
- (id)initWithParticipants:(id)arg1 isGroup:(_Bool)arg2 audioOnly:(_Bool)arg3;

@end

